### ISSUE TITLE
If the root package has a target with a null `include` sources then we'll hit an exception

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1042]
https://github.com/dart-lang/build/blob/9c93034455c5e134f2b18d1d4afefc1f153f582e/build_runner/lib/src/generate/options.dart#L106

```yaml
targets:
  $default:
    sources:
      exclude: ["lib/src/**"]
```

`target.sources.include` will be null and we'll hit an exception in the call to `.toList()`.

cc @nshahan
