### ISSUE TITLE
Possible to build web/a.dart (Dart2Js) and web/b.dart (DDC)?

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1073]
i.e. something like

```yaml
targets:
  $default:
    sources:
      - web/main.dart
  worker:
    sources:
      - web/worker.dart
```

**Comment by jakemac53** [comment]
Yes - but you would need to include all your other sources as well (probably in another target). Something like this:

```yaml
targets:
  $default:
    sources:
      include:
        - lib/**.dart
  web:
    sources:
      - web/main.dart
  worker:
    sources:
      - web/worker.dart
```
