### ISSUE TITLE
Source globs are used for all inputs (incorrectly)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#1076]
```
[WARNING] Instance of 'WebEntrypointBuilder' on web_worker_channel|web/main.dart: Unable to read web_worker_channel|lib/web_worker_channel.ddc.js, check your console for compilation errors.
[WARNING] Instance of 'WebEntrypointBuilder' on web_worker_channel|web/main.dart: Unable to read web_worker_channel|lib/src/js_interop.ddc.js, check your console for compilation errors.
[WARNING] Instance of 'WebEntrypointBuilder' on web_worker_channel|web/main.dart: Unable to read web_worker_channel|web/main.ddc.js, check your console for compilation errors.
```

I assume there is a good reason :)

This is _from_ my console, and yet, no compilation errors.

**Comment by jakemac53** [comment]
I think the issue is the action failed in a previous build but we don't re-run failing actions on subsequent builds unless something has changed. We really need the --rerun-failing-actions but that is now prioritized behind dart2js deferred loading (and its _much_ more complicated than you would think).

This does at least give you a link to the error log now - and I am working on publishing today hopefully.

**Comment by matanlurey** [comment]
So I `rm -rf'd` the `.dart_tool` folder and still get this.

> This does at least give you a link to the error log now - and I am working on publishing today hopefully.

Ah, well I will wait for that then :D

**Comment by jakemac53** [comment]
> So I rm -rf'd the .dart_tool folder and still get this.

huh... that sounds like a bug for sure no idea what would cause it.

**Comment by matanlurey** [comment]
I'll create a repro case if possible.

**Comment by matanlurey** [comment]
OK, it looks like the entrypoint builder is looking for (generated) DDC, and doesn't find it. That's a separate error (and should be fixed up), but the reproduction case is roughly:

```yaml
targets:
  # This library (package:web_worker_channel).
  $default:
    sources:
      - lib/**.dart
    dependencies:
      - js
      - stream_channel

  # Main Application (web/main.dart).
  main:
    sources:
      - web/main.dart
    dependencies:
      - web_worker_channel
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        options:
          compiler: dartdevc

  # Web Worker (web/worker.dart).
  worker:
    sources:
      - web/worker.dart
    dependencies:
      - web_worker_channel
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/worker.dart
        options:
          compiler: dart2js
```

(from https://github.com/dart-lang/build/issues/1073)

... it looks like not using the default (implicit) `build.yaml` disables modules/summaries/ddc, which in turn will make DDC (and other dependent builders) fail. Thoughts?

**Comment by jakemac53** [comment]
> ... it looks like not using the default (implicit) build.yaml disables modules/summaries/ddc, which in turn will make DDC (and other dependent builders) fail. Thoughts?

@natebosch that would be a bug right? I don't believe that is the intended behavior, only things you override should be changed.

**Comment by natebosch** [comment]
> it looks like not using the default (implicit) `build.yaml` disables modules/summaries/ddc

It definitely shouldn't. I think it's more likely an issue with deps

**Comment by jakemac53** [comment]
> It definitely shouldn't. I think it's more likely an issue with deps

Ah true that could cause you to see this for sure

**Comment by matanlurey** [comment]
@natebosch:

>  I think it's more likely an issue with deps

An issue of _mine_ or the system? 😈

**Comment by natebosch** [comment]
> An issue of mine or the system?

Possibly both ;)

I'll try to repro locally and see if I can figure it out. I think we aren't parsing the dependency to the local target correctly.

**Comment by natebosch** [comment]
Confirmed this is completely a bug in build_runner.

When we go to run the Summary or DDC builder our input is `lib/web_worker_channel.module` and we check whether we should run at all - but since that doesn't match the glob `lib/**.dart` we decide not to run.

The issue is we're using the `sources` globs for all inputs to all actions, when we should only consider it for source file inputs to actions.

**Comment by natebosch** [comment]
Hmm, we have some cleanup to do, we shouldn't need to check matching inputs in two places but we're currently doing it while creating the graph and while building.

**Comment by jakemac53** [comment]
There is a slight difference where at build time it needs to try and lazily build assets and the only select the assets which actually were output as primary inputs

**Comment by matanlurey** [comment]
Thanks for looking. I was able to work-around with this:

```yaml
targets:
  # This library (package:web_worker_channel).
  $default:
    sources:
      - lib/**.*
    dependencies:
      - js
      - stream_channel

  # Main Application (web/main.dart).
  main:
    sources:
      - web/main.*
    dependencies:
      - web_worker_channel
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        options:
          compiler: dartdevc

  # Web Worker (web/worker.dart).
  worker:
    sources:
      - web/worker.*
    dependencies:
      - web_worker_channel
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/worker.dart
        options:
          compiler: dart2js
```
