### ISSUE TITLE
Localhost Not Found (404)

### ISSUE THREAD

**Issue by Cododoc** [dart-lang/build#1088]
Hello!
I run serve command like this:
`pub run build_runner serve webDev`

Then a have erroe on localhost:8080:
Not Found
```
Request URL:http://localhost:8080/
Request Method:GET
Status Code:404 Not Found
```

If run serve without params all works fine.
`pub run build_runner serve`

OS: Windwos.
Dart: Dart VM version: 2.0.0-dev.30.0 (Thu Feb 22 14:08:47 2018 +0100) on "windows_x64"
angular-5.0.0-alpha+6

**Comment by jakemac53** [comment]
`pub run build_runner serve webDev` would serve the `webDev` directory on port 8080 - just to confirm do you have a webDev dir?

**Comment by Cododoc** [comment]
Yes, of course. I have 2 web folders. For production and development.

**Comment by jakemac53** [comment]
Oh, the issue here is going to be that you are using a non-standard directory (which is fine, but will require some config on your part). Basically, we have a whitelist of directories that we include as sources by default so we don't pick up output directories or editor specific directories etc.

You can fix this with a build.yaml, something like this:

```
targets:
  $default:
    sources:
      - lib/**
      - web/**
      - webDev/**
```

**Comment by jakemac53** [comment]
closing as I assume this will fix the issue, please re-open if you are still having issues

**Comment by natebosch** [comment]
I think we can identify situations like this and print something more helpful. Filed #1091 to track.

**Comment by Cododoc** [comment]
@jakemac53 I tried run serve with build.yaml file. Something changed but it doesn't work.

Now it can find index.html:
```
Request URL:http://localhost:8080/
Request Method:GET
Status Code:200 OK
```

But it can't find main.dart.js:
```
Request URL:http://localhost:8080/main.dart.js
Request Method:GET
Status Code:404 Not Found
```

**Comment by Cododoc** [comment]
It look like we need set entrypoint in build.yaml:
```
targets:
  $default:
    sources:
      - lib/**
      - web/**
      - webDev/**
    builders:
      build_web_compilers|entrypoint:
        generate_for:
        - webDev/**.dart
```

After that changes all work fine.
