### ISSUE TITLE
contents of build.yaml not overridden by --define values

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1105]
For these versions

```yaml
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.12"
  build_web_compilers:
    dependency: "direct dev"
    description:
      name: build_web_compilers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
```
