### ISSUE TITLE
build_runner not able to detect changes to certain files

### ISSUE THREAD

**Issue by dineshbhosale** [dart-lang/build#1178]
build_runner version : 
version: "0.8.0"

Following command to build new dart when they are changed

```bash
pub run build_runner watch --output build --config release
```

When changes are made to html, javascript or html files in vs-code `build_runner` is not able to detect them.

Therefore, user is forced to re-run above command to copy modified files.

Apps are made of various assets, `build_runner` should be able to detect changes to non-dart files and copy them to build folder.

Operating system:
Arch Linux 64-bit

dart --version output :
Dart VM version: 2.0.0-dev.38.0 (Thu Mar 15 16:53:42 2018 +0100) on "linux_x64"

pubscpec.yaml
```yaml
name: untitled2
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: coder <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dependencies:
  chrome: any
  js: any

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter:
  build_runner:
  build_web_compilers:

transformers:
- chrome
- $dart2js:
    csp: true
    commandLineOptions: [--use-old-frontend]
- dart_to_js_script_rewriter:
    csp: true

web:
  compiler:
    debug: dartdevc

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
```

build.release.yaml
```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
```
