### ISSUE TITLE
Build fails trying to resolve another package from sass_builder

### ISSUE THREAD

**Issue by 4cm4k1** [dart-lang/build#1181]
I went to build my project after bumping Angular and its sub-packages to the latest alpha versions and received the error output below. I've included my environment info and `pubspec.yaml` for additional context. `build_runner` indicated it ran into a bug, but based on the output, maybe it's an issue with [sass_builder](https://github.com/dart-league/sass_builder)?

**Dart:** 2.0.0-dev.39.0
**OS:** macOS 10.13.4 beta (17E182a)
**Browser:** N/A

**`pubspec.yaml`:**
```yaml
dependencies:
  angular: ^5.0.0-alpha+8
  angular_components: ^0.9.0-alpha+7
  angular_forms: ^2.0.0-alpha
  angular_router: ^2.0.0-alpha+8
  firebase: ^4.4.0
  pwa: ^0.1.9+1

dev_dependencies:
  angular_ast: ^0.4.4
  angular_compiler: ^0.4.0-alpha+8
  angular_test: ^2.0.0-alpha+6
  build_runner: ^0.8.0
  build_web_compilers: ^0.3.4+1
  sass_builder: ^1.1.4
  test: ^0.12.32+1

dependency_overrides:
  angular: ^5.0.0-alpha+8
  angular_forms: ^2.0.0-alpha
```

**Error output:**
```shell
[INFO] Generating build script completed, took 377ms

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

'package:sass_builder/sass_builder.dart': malformed type: line 34 pos 20: cannot resolve class 'Logger' from 'SassBuilder'
  final _log = new Logger('sass_builder');
                   ^

dart:core                                                          _TypeError._throwNew
package:sass_builder/sass_builder.dart 34:20                       new SassBuilder
package:angular_components/builder.dart 9:9                        scssBuilder
package:build_runner/src/package_graph/apply_builders.dart 150:37  new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner/src/package_graph/apply_builders.dart 261:27  _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                          List.addAll
package:build_runner/src/package_graph/apply_builders.dart 215:7   createBuildPhases
package:build_runner/src/generate/build_impl.dart 93:13            build
package:build_runner/src/generate/build.dart 66:5                  build
package:build_runner/src/entrypoint/options.dart 266:24            _BuildCommand.run
package:args/command_runner.dart 194:27                            CommandRunner.runCommand
package:args/command_runner.dart 109:29                            CommandRunner.run.<fn>
dart:async                                                         new Future.sync
package:args/command_runner.dart 109:11                            CommandRunner.run
package:build_runner/src/entrypoint/run.dart 15:24                 run
.dart_tool/build/entrypoint/build.dart 49:22                       main
```
