### ISSUE TITLE
`build_runner watch` is replacing new files with old files from memory

### ISSUE THREAD

**Issue by dineshbhosale** [dart-lang/build#1183]
build_runner version : 
version: "0.8.0"

Following command is used to build dart files and other assets used by web app : 

```bash
pub run build_runner watch --output build --config release
```

When changes are made to html, javascript or non-dart files then they are not detected.

Therefore most likely a user will decide to run another task runner alongside `build_runner watch`.
After that, second task runner will detect changes to non-dart files and copy them to `build/web` folder.

But as soon as user edits a dart file, `build_runner watch` will detect changes and replace newly copied non-dart files with old ones that `build_runner watch` stored in memory when it was first run.

In my opinion the `pub run build_runner watch` should fully support all files or provide an option to exclude non-dart files, or files that are not support.

Operating system:
Arch Linux 64-bit

dart --version output :
Dart VM version: 2.0.0-dev.38.0 (Thu Mar 15 16:53:42 2018 +0100) on "linux_x64"

pubscpec.yaml
```yaml
name: untitled2
description: An absolute bare-bones web app.
version: 0.0.1
#homepage: https://www.example.com
#author: coder <email@example.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

#dependencies:
#  path: ^1.4.1

dependencies:
  chrome: any
  js: any

dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter:
  build_runner:
  build_web_compilers:

transformers:
- chrome
- $dart2js:
    csp: true
    commandLineOptions: [--use-old-frontend]
- dart_to_js_script_rewriter:
    csp: true

web:
  compiler:
    debug: dartdevc

# Uncomment the following in sdk 1.24+ to make pub serve
# use dartdevc (webdev.dartlang.org/tools/dartdevc).
#web:
#  compiler:
#    debug: dartdevc
```

build.release.yaml
```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
```
