### ISSUE TITLE
 Heroku (Ubuntu 16) build fails with latest Dart SDK 

### ISSUE THREAD

**Issue by johnpryan** [dart-lang/build#1194]
Moving https://github.com/dart-lang/sdk/issues/32620 over here.

I have a [buildpack](https://github.com/johnpryan/heroku-buildpack-dart) I would like to use with the new build/ package, but need to add the `--use-old-frontend` flag in order to get it to work properly.

```
[INFO] build_web_compilers|entrypoint on web/main.dart:Running dart2js with --fast-startup --minify --trust-type-annotations --trust-primitives -ppackages -oweb/main.dart.js web/main.dart
[SEVERE] build_web_compilers|entrypoint on web/main.dart:
Dart2Js finished with:
Error: Could not resolve the package 'angular' in 'package:angular/angular.dart'.
```

With the `--use-old-frontend` flag it works:

```
[INFO] build_web_compilers|entrypoint on web/main.dart:Running dart2js with --fast-startup --minify --trust-type-annotations --trust-primitives --use-old-frontend -ppackages -oweb/main.dart.js web/main.dart
[INFO] 39.4s elapsed, 1552/1553 actions completed.
[INFO] 40.5s elapsed, 1552/1553 actions completed.
[INFO] 41.6s elapsed, 1552/1553 actions completed.
[INFO] 42.7s elapsed, 1552/1553 actions completed.
[INFO] 43.8s elapsed, 1552/1553 actions completed.
[INFO] 44.9s elapsed, 1552/1553 actions completed.
[INFO] 46.0s elapsed, 1552/1553 actions completed.
[INFO] 47.1s elapsed, 1552/1553 actions completed.
[INFO] 48.2s elapsed, 1552/1553 actions completed.
[INFO] 49.3s elapsed, 1552/1553 actions completed.
[INFO] 50.4s elapsed, 1552/1553 actions completed.
[INFO] 51.5s elapsed, 1552/1553 actions completed.
[INFO] 52.6s elapsed, 1552/1553 actions completed.
[INFO] 53.7s elapsed, 1552/1553 actions completed.
[INFO] 54.8s elapsed, 1552/1553 actions completed.
[INFO] 55.9s elapsed, 1552/1553 actions completed.
[INFO] 57.0s elapsed, 1552/1553 actions completed.
[INFO] 58.1s elapsed, 1552/1553 actions completed.
[INFO] 59.2s elapsed, 1552/1553 actions completed.
[INFO] 1m 0s elapsed, 1552/1553 actions completed.
[INFO] 1m 1s elapsed, 1552/1553 actions completed.
[INFO] 1m 2s elapsed, 1552/1553 actions completed.
[INFO] 1m 3s elapsed, 1552/1553 actions completed.
[INFO] build_web_compilers|entrypoint on web/main.dart:Dart2Js finished with:
Hint: 1 hint(s) suppressed in package:angular_components.
Hint: 1 hint(s) suppressed in package:angular.
Compiled 8,046,224 characters Dart to 845,758 characters JavaScript in 24.9 seconds
Dart file (web/main.dart) compiled to JavaScript: web/main.dart.js
[INFO] Running build completed, took 1m 4s
[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 227ms
[INFO] Creating merged output dir `build`...
[INFO] Creating merged output dir `build` completed, took 2.9s
[INFO] Writing asset manifest...
[INFO] Writing asset manifest completed, took 2ms
[INFO] Succeeded after 1m 7s with 1465 outputs
```

I believe this is using the [Heroku-16](https://devcenter.heroku.com/articles/heroku-16-stack) stack (ubuntu 16)

**Comment by johnpryan** [comment]
The pubspec I am tries to use the most up-to-date versions of the `build` package:

```
name: my_project
version: 0.0.1

environment:
  sdk: '>=1.24.0 <3.0.0'

dependencies:
  angular: ^5.0.0-alpha+8
  angular_components: ^0.9.0-alpha+8
  angular_forms: any
  angular_router: any

dev_dependencies:
  build_runner: ^0.8.0
  build_web_compilers: ^0.3.0
  sass_builder: ^1.1.2

dependency_overrides:
  # see override in web_client pubspec.yaml
  cli_util: '>=0.1.0 <0.2.0'

  # until http 0.12.0 lands
  async: ^2.0.0

```

my pubspec.lock file:

```
  build:
    dependency: "direct main"
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.0+2"
  build_barback:
    dependency: transitive
    description:
      name: build_barback
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.0+3"
  build_config:
    dependency: transitive
    description:
      name: build_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.5"
  build_modules:
    dependency: transitive
    description:
      name: build_modules
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0+2"
  build_resolvers:
    dependency: transitive
    description:
      name: build_resolvers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.0"
  build_web_compilers:
    dependency: "direct dev"
    description:
      name: build_web_compilers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.4"
```

**Comment by natebosch** [comment]
You want `build_web_compilers 0.3.4+2`, you have `0.3.4`. It should get picked up with a `pub upgrade`.

**Comment by johnpryan** [comment]
This is after running `pub upgrade`

**Comment by johnpryan** [comment]
To reproduce:

1. create a new directory
2. use this pubspec:

```
name: my_project
version: 0.0.1

environment:
  sdk: '>=1.24.0 <3.0.0'

dependencies:
  angular: ^5.0.0-alpha+8
  angular_components: ^0.9.0-alpha+8
  angular_forms: any
  angular_router: any

dev_dependencies:
  build_runner: ^0.8.0
  build_web_compilers: ^0.3.0
  sass_builder: ^1.1.2
```

3. observe build_web_compilers resolves to 0.3.4, not 0.3.4+2

**Comment by natebosch** [comment]
What version of the SDK are you on? I'm on `Dart VM version: 2.0.0-dev.38.0 (Thu Mar 15 16:53:42 2018 +0100) on "linux_x64"` and when I copy that pubspec and run a `pub get` I pick up the latest build_web_compilers

**Comment by matanlurey** [comment]
@johnpryan We require a very new version of the current SDK:

https://github.com/dart-lang/build/blob/ed3a78c65b9cd180c9e3d93f9982ebc21b1bfaa1/build_web_compilers/pubspec.yaml#L7-L8

**Comment by natebosch** [comment]
@matanlurey - SDKs older than that shouldn't require or support the `--use-old-frontend` flag so this _should_ be on a recent SDK but maybe something is wonky with pub.

**Comment by johnpryan** [comment]
This is still occurring in sdk 2.0.0-dev.42 - can this be reopened?

**Comment by johnpryan** [comment]
the main problem is that I am unable to upgrade to `build_web_compilers: 0.3.4+2` even when adding it as a dependency override

**Comment by matanlurey** [comment]
Why can't you upgrade?

**Comment by natebosch** [comment]
the new version solve algorithm was just enabled in pub. I'm not sure when it will be pulled in to the SDK but we should expect that problems like this will get easier to diagnose.

I'm not inclined to track this as an issue on the build repo since it's a problem with either the the version solver or the constraints on your package (or some other dependency).

> even when adding it as a dependency override

This is very surprising. What error are you seeing when you try to `pub upgrade` and force this package version?

**Comment by johnpryan** [comment]
It seems like I just had to upgrade build_runner from 0.7.13+1 to 0.8.0.

I was able to determine the issue by specifically running `pub upgrade build_web_compilers`:

```
pub upgrade build_web_compilers
Resolving dependencies... 
Package build_runner has no versions that match ^0.8.0 derived from:
- build_web_compilers 0.3.4+2 depends on version ^0.8.0
- my_app depends on version ^0.7.13
```

**Comment by johnpryan** [comment]
I think my mistake was setting `build_web_compilers: 0.3.4+2` as a dependency override, which doesn't show a very helpful message:

```
pub upgrade
Resolving dependencies... (3.5s)
Package build_web_compilers has no versions that match 0.3.4+2 derived from:
- census_app depends on version 0.3.4+2
```

**Comment by natebosch** [comment]
Yeah I think the error messages should be getting better once the SDK updates to the latest pub with the new version solver.

Glad you were able to track this down!

**Comment by johnpryan** [comment]
Sorry to keep bringing bad news, but**locally** (macOS) the build is working, but on heroku (Ubuntu 16) the build is still failing.  This is using Dart 2.0.0-dev.43.0 and build_web_compilers 0.3.4+2:

Here's the pubspec:

```
dependencies:
  angular: ^5.0.0-alpha+6
  angular_components: 0.9.0-alpha+7
  angular_forms: ^1.0.1-alpha+2
  angular_router: ^2.0.0-alpha+2
  transform_sass: any
  http: any
  yaml: any
  source_gen: any
  build: any
  path: any
  shelf: any
  shelf_gzip: any
  shelf_route: any
  requester: any
  rxdart: any
  apptree_shared:
    path: ../apptree_shared
dev_dependencies:
#  angular_test: any
  browser: any
  dart_to_js_script_rewriter: any
  test: any
  json_serializable: any
  build_runner: ^0.8.0
  build_web_compilers: ^0.3.4+2
  sass_builder: ^1.1.2

dependency_overrides:
  # see override in web_client pubspec.yaml
  cli_util: '>=0.1.0 <0.2.0'

  # until http 0.12.0 lands
  async: ^2.0.0
```

and the full heroku logs here:
[heroku_logs.txt](https://github.com/dart-lang/build/files/1857992/heroku_logs.txt)

with the following error:

```

You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues
'package:angular/builder.dart': error: line 29 pos 42: invalid arguments passed to constructor 'CompilerFlags' for class 'CompilerFlags': no optional formal parameter named 'useAstPkg'
const _defaultFlags = const CompilerFlags(
                                         ^
package:build_runner/src/package_graph/apply_builders.dart 150:37  new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner/src/package_graph/apply_builders.dart 261:27  _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                          List.addAll
package:build_runner/src/package_graph/apply_builders.dart 215:7   createBuildPhases
package:build_runner/src/generate/build_impl.dart 93:13            build
package:build_runner/src/generate/build.dart 66:5                  build
package:build_runner/src/entrypoint/options.dart 266:24            _BuildCommand.run
package:args/command_runner.dart 194:27                            CommandRunner.runCommand
package:args/command_runner.dart 109:29                            CommandRunner.run.<fn>
dart:async                                                         new Future.sync
package:args/command_runner.dart 109:11                            CommandRunner.run
package:build_runner/src/entrypoint/run.dart 15:24                 run
.dart_tool/build/entrypoint/build.dart 53:22                       main
 !     Push rejected, failed to compile Dart app.
 !     Push failed
```
