### ISSUE TITLE
Need a better error with poorly configured `build.yaml`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1221]
Configured a builder in my package:
```yaml
builders:
  build_cli:
    target: noop
    import: "package:build_cli/builder.dart"
    builder_factories: ["cliBuilder"]
    build_extensions: {".dart": [".g.dart"]}
    auto_apply: dependents
    build_to: source
```

I have a `lib/builder.dart` file, but it does not have a `cliBuilder` method.

Run `pbr build`

Expected: "You have a misconfigured builder...could not find `cliBuilder` function etc"

Actual:

```
You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


NoSuchMethodError: No top-level getter '_i2.cliBuilder' declared.
Receiver: top-level
Tried calling: _i2.cliBuilder
dart:core                                     NoSuchMethodError._throwNew
.dart_tool/build/entrypoint/build.dart 7:31   _builders
.dart_tool/build/entrypoint/build.dart 5:7    _builders
.dart_tool/build/entrypoint/build.dart 11:36  main
```

```
Dart SDK 2.0.0-dev.43.0

dependencies:
- build 0.12.0+2
- build_config 0.2.5

dev dependencies:
- build_runner 0.8.1
```
