### ISSUE TITLE
build should only remove files that match with generate_for

### ISSUE THREAD

**Issue by a14n** [dart-lang/build#1246]
With `Dart VM version: 2.0.0-dev.44.0 (Mon Apr 2 16:14:58 2018 +0200) on "linux_x64"` and `build_runner: ^0.8.1` I have the following `build.yaml`:

```yaml
targets:
  $default:
    builders:
      js_wrapping_generator|js_wrapping:
        generate_for:
        - 'lib/src/google_maps_src.dart'
    sources:
    - 'lib/**.dart'
```

And files:

```
lib
  src
    google_maps_src.dart
    google_maps_src.g.dart
    google_maps_src_places.dart
    google_maps_src_places.g.dart
```

`pub run build_runner build` generates correctly a `lib/src/google_maps_src.g.dart` but it removes `lib/src/google_maps_src_places.g.dart`. This file shouldn't be removed as it doesn't match the `generate_for` entry.
