### ISSUE TITLE
node_interop Travis builds are hanging when building with dart2js

### ISSUE THREAD

**Issue by pulyaevskiy** [dart-lang/build#1310]
Builds in this PR are hanging for unknown reason when compiling `node_interop` with dart2js:
https://travis-ci.org/pulyaevskiy/node-interop/builds/368300306

When running on my laptop I have no issues, only Travis is affected.

I tried enabling `--verbose` and `--low-resource-mode` with no luck. Wondering if there is anything else I can try?

```
Dart VM version: 2.0.0-dev.48.0 (Fri Apr 13 13:35:30 2018 +0200) on "macos_x64"
```

```yaml
dependencies:
  js: ^0.6.1

dev_dependencies:
  test: ^0.12.35
  build_runner: ^0.8.2+2
  build_node_compilers: ^0.1.2
  build_test:
```
