### ISSUE TITLE
Add a Global builder options section to build.yaml

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1370]
Strawman:

```yaml
global_options:
  builder_package|builder_name:
    options:
      key: "applies anywhere this builder is already running"
    release_options:
      key: "applies in release mode anywhere this builder is already running"
   another_package|another_builder:
     enabled: true # acts as if this builder was `apply_to: all_packages` and overrides any package disabling it?
    third_package|third_builder:
      enabled: false # builder will never run anywhere?
targets:
  $default:
    builders:
      builder_package|builder_name:
        options:
          key: "never applies because it's overridden globally?"
```

Open questions:

- Should global config take highest precedence in terms of overrides? This is the case today with `--define`
- Should we allow enabling and disabling builders globally? Note that this would change the structure of the build so would cause an invalidation and full-rebuild if flipping with `--config`
