### ISSUE TITLE
Make it cheaper to flip between DDC and Dart2Js

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1419]
Currently it's easy to go from `--release` back to dev and if nothing has changed very little work needs to be done, the DDC entrypoint builder is cheap and no actual compilation happens.

Going from dev back to `--release`, however, is slow. It requires re-running dart2js on all entrypoints because the work was overwritten by the ddc bootstrapping.

We could make it cheap to flip back and forth if we write dart2js output to a different file.
- Add an optional builder which mirrors the entrypoint builder for dart2js. Output to `.dart.dart2js` instead of `.dart.js`
- Change the entrypoint builder to do a direct copy from `.dart.dart2js` to `.dart.js`.

The tricky part here is handling `dart2js_args`. We probably will need this to be a breaking change and have users move args from `build_web_compilers|entrypoint` to `build_web_compilers|dart2js`.

**Comment by jakemac53** [comment]
> The tricky part here is handling dart2js_args. We probably will need this to be a breaking change and have users move args from build_web_compilers|entrypoint to build_web_compilers|dart2js.

We could just make it two builders wrapped up under the one though (add a builder factory). Then the options would get plumbed through correctly as is.

The new builder would be an optional builder so it only runs if the actual entrypoint builder asks for it.

**Comment by jakemac53** [comment]
Note also though that the use case for this is pretty narrow - it is only when switching from release to debug and back to release without making any code changes that you would get benefit, yet it comes with an extra cost in terms of actions and copying for all release builds.

**Comment by jakemac53** [comment]
> True. I think the cost in extra actions is probably fairly low and this does have a benefit when iterating on one or a small number of test files and checking behavior with both Dart2Js and DDC.

But if you are iterating on them then dart2js is going to re-run anyways ;)

**Comment by natebosch** [comment]
> But if you are iterating on them then dart2js is going to re-run anyways

Not for the tests you haven't touched, but that's only a problem until we're able to solve targeting builds down to the per-test level.

**Comment by jakemac53** [comment]
> Not for the tests you haven't touched

Oh true - if you are iterating on a specific test then this definitely does not give the desired behavior.

> but that's only a problem until we're able to solve targeting builds down to the per-test level.

Ya, I am still not completely sure how we want to solve this though. We can build the entrypoint and all the outputs of it, but I don't know how we can track what other potential files may need to be built (css, etc).

**Comment by natebosch** [comment]
@jakemac53 - should we do this while we're bumping to 2.0?

**Comment by jakemac53** [comment]
I think we decided we could do this without a breaking change? I would rather not block on it - we don't see complaints about this that I can remember.

**Comment by natebosch** [comment]
I took a brief look at this - I think it wouldn't be too hard to do, except we don't support a mix of optional and non-optional builder factories within the same builder definition. Either all of the individual builders are optional, or none are.

I don't know what it would take to allow individual factories in the list to be marked optional, but I do think that would be useful.

@jakemac53 - if we _do_ decide to allow optional builders by index within the list of factories, do you have any ideas how we might want to represent that in the yaml? I could imagine a list with the same length, something like

```yaml
builders:
  some_name:
    import: "package:foo/builders.dart"
    builder_factories:
      - firsBuilder
      - secondBuilder
    build_extensions:
      .dart:
        - .first_out
        - .second_out
    is_optional:
      - true
      - false
 ```
 
 Or maybe allow `builder_factories` as a map instead?
 
 ```yaml
builders:
  some_name:
    import: "package:foo/builders.dart"
    builder_factories:
      firsBuilder: true
      secondBuilder:
        is_optional: true
    build_extensions:
      .dart:
        - .first_out
        - .second_out
 ```

**Comment by jakemac53** [comment]
Hmmm I don't love either of those options, nor do I have a proposal for a better one. But it does seem generally useful.

**Comment by jakemac53** [comment]
Is it possible to limit the value entirely for certain entries?

**Comment by natebosch** [comment]
Yes, I think we could omit the `true` placeholder - when we parse it we'll get `null`.

```yaml
builders:
 some_name:
   import: "package:foo/builders.dart"
   builder_factories:
     firstBuilder:
     secondBuilder:
       is_optional: true
   build_extensions:
     .dart:
       - .first_out
       - .second_out
```

**Comment by jakemac53** [comment]
I don't think that looks too bad. It would just presumably be an override of the general setting? Is there any other setting that we should expose (source vs cache?)

**Comment by natebosch** [comment]
> Is there any other setting that we should expose (source vs cache)?

There likely is, but I don't think we should add generality without a specific use case in mind. I think we can add additional config options in a non-breaking way as we need them.

This would also require a breaking change to https://pub.dev/documentation/build_runner_core/latest/build_runner_core/apply.html


> It would just presumably be an override of the general setting?

Yeah I think so. Could consider making it an error to specify for both, but I don't see any reason to not allow something like

```yaml
   builder_factories:
     firstBuilder:
       is_optional: false
     secondBuilder:
     thirdBuilder:
   is_optional: true
```
