### ISSUE TITLE
Resolve relative paths for builders against the root of the package (not the .dart_tool/.../entrypoint

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1423]
Weird:

```yaml
builders:
  pana:
    import: "../../../tool/builder.dart"
```

Not weird:
```yaml
builders:
  pana:
    import: "tool/builder.dart"
```
