### ISSUE TITLE
webdev build - Hashing is unsupported for messages with more than 2^64 bits

### ISSUE THREAD

**Issue by normcf** [dart-lang/build#1495]
Just started with dart_2.0.0-dev.58.0-1_amd64.deb on a new install of Ubuntu 18.04

I managed to get pubspec.yaml to work with pub get then ran webdev build --output web:build
I have been using dart 1.24 with dartium on Ubuntu 14.04 for some time, but recent changes to the kernel were incompatible with amd proprietary drivers, so I am forced to upgrade.  This is my first day with dart 2.0 and I may have something incorrectly set up.  I haven't added any builders.

from pubspec.lock
```
build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.9"
```

```
You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


Unsupported operation: Hashing is unsupported for messages with more than 2^64 bits.
package:crypto/src/hash_sink.dart 124:7                         HashSink._finalizeData
package:crypto/src/hash_sink.dart 69:5                          HashSink.close
dart:convert                                                    _ByteAdapterSink.close
package:crypto/src/hash.dart 28:15                              Hash.convert
package:build_runner/src/util/constants.dart 31:43              _scriptHashFor
package:build_runner/src/util/constants.dart 17:18              assetGraphPathFor
package:build_runner/src/util/constants.dart 11:31              assetGraphPath
package:build_runner/src/util/constants.dart 11:14              assetGraphPath
package:build_runner/src/generate/build_definition.dart 180:54  _Loader._tryReadCachedAssetGraph
package:build_runner/src/generate/build_definition.dart 75:28   _Loader.prepareWorkspace
package:build_runner/src/generate/build_definition.dart 60:54   BuildDefinition.prepareWorkspace
package:build_runner/src/generate/build_impl.dart 115:29        _singleBuild
package:build_runner/src/generate/build_impl.dart 104:20        build
package:build_runner/src/generate/build.dart 71:5               build
package:build_runner/src/entrypoint/build.dart 28:24            BuildCommand.run
package:args/command_runner.dart 194:27                         CommandRunner.runCommand
package:args/command_runner.dart 109:29                         CommandRunner.run.<fn>
dart:async                                                      new Future.sync
package:args/command_runner.dart 109:11                         CommandRunner.run
package:build_runner/src/entrypoint/run.dart 22:31              run
.dart_tool/build/entrypoint/build.dart 59:22                    main
```

**Comment by natebosch** [comment]
How reliably can you reproduce this? We're hashing a file path there and I don't see how we could end up with a 2 exbibyte string... Maybe there is a bug in the crypto package. What version of that package do you have?

**Comment by normcf** [comment]
I just reran it and so I can repeat it for you.  Until I can get past this I will not be making any code changes so let me know what you need.  From pubspec.lock:
```
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
```

**Comment by jakemac53** [comment]
hmm, no nothing coming to mind

**Comment by natebosch** [comment]
Could you try a `pub upgrade`? Your version of `package:crypto` is stale and is missing the update to work with the new fixed sized ints in the SDK. I'm guess you have a checked in `pubspec.lock` file and when you ran a pub get you resolved an old version of that package.

**Comment by natebosch** [comment]
Thanks for the confirmation!

**Comment by jakemac53** [comment]
> and it seems to build through all of my "main"s. I had some folders with test code that failed to compile but, miraculously, there were no other errors. I did expect errors on Isolates I use, so there must be more going on.

Yes - by default if you have a `build_web_compilers` dependency then it is going to try and compile all your `mains` to Javascript. You can exclude specific ones like this to get rid of the errors:

```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          exclude:
            - test/vm/** # Exclude your non-web tests with globs here
          include:
            - test/web/** # Or optionally explicitly include your web tests with globs here
```
