### ISSUE TITLE
build_runner bug

### ISSUE THREAD

**Issue by kentcb** [dart-lang/build#1537]
Thank you for taking the time to file an issue!

`flutter doctor -v` output:
```
[√] Flutter (Channel master, v0.5.3-pre.9, on Microsoft Windows [Version 10.0.17134.48], locale en-US)
    • Flutter version 0.5.3-pre.9 at C:\Users\kent\Repository\flutter
    • Framework revision 0e4770e809 (4 hours ago), 2018-06-07 18:27:08 -0700
    • Engine revision fca976d8c7
    • Dart version 2.0.0-dev.60.0.flutter-a5e41681e5

[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
    • Android SDK at C:\Android\android-sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-27, build-tools 27.0.3
    • ANDROID_HOME = C:\Android\android-sdk
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)
    • All Android licenses accepted.

[√] Android Studio (version 3.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
    • Java version OpenJDK Runtime Environment (build 1.8.0_152-release-1024-b02)

[√] IntelliJ IDEA Community Edition (version 2017.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2017.3.2
    • Flutter plugin version 22.2.2
    • Dart plugin version 173.4548.30

[!] VS Code, 64-bit edition (version 1.23.1)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension not installed; install from
      https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

[!] Connected devices
    ! No devices available

! Doctor found issues in 2 categories.
```

`pubspec.yaml` contents:
```
# See https://www.dartlang.org/tools/pub/pubspec

name: <<redacted>>
description: The <<redacted>> mobile application.

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: "^0.1.2"
  built_collection: "^3.0.5"
  built_value: "^5.2.1"
  quiver: "^0.29.0+1"
  intl: "^0.15.2"
  flutter_redux: "^0.5.0"
  redux: "^3.0.0"
  redux_logging: "^0.3.0"
  json_annotation: "^0.2.4"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: "^2.2.3"
  build_runner: "^0.8.0"
  built_value_generator: "^5.2.1"
  json_serializable: "^0.5.2"

flutter:
  uses-material-design: true
```

Running on Windows, the output of `flutter packages pub run build_runner watch --delete-conflicting-outputs` is:

```
[INFO] Generating build script...
[INFO] Generating build script completed, took 662ms

[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 22ms

[INFO] Waiting for all file watchers to be ready...
[INFO] Waiting for all file watchers to be ready completed, took 242ms

[INFO] Initializing inputs
[INFO] Building new asset graph...


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


DuplicateAssetNodeError: GeneratedAssetNode: <<redacted>>|lib/actions.g.dart generated from input <<redacted>>|lib/actions.dart.
This probably means you have multiple actions that are trying to output the same file.
package:build_runner/src/asset_graph/graph.dart 468:11          AssetGraph._addGeneratedOutputs
package:build_runner/src/asset_graph/graph.dart 420:21          AssetGraph._addInBuildPhaseOutputs
package:build_runner/src/asset_graph/graph.dart 386:26          AssetGraph._addOutputsForSources
package:build_runner/src/asset_graph/graph.dart 55:11           AssetGraph.build
package:build_runner/src/generate/build_definition.dart 104:39  _Loader.prepareWorkspace.<fn>
package:build_runner/src/logging/logging.dart 25:30             logTimedAsync
package:build_runner/src/generate/build_definition.dart 103:13  _Loader.prepareWorkspace
package:build_runner/src/generate/build_definition.dart 60:54   BuildDefinition.prepareWorkspace
package:build_runner/src/generate/watch_impl.dart 307:48        WatchImpl._run.<fn>
package:build_runner/src/generate/watch_impl.dart 329:6         WatchImpl._run
package:build_runner/src/generate/watch_impl.dart 195:9         new WatchImpl
package:build_runner/src/generate/watch_impl.dart 128:9         _runWatch
package:build_runner/src/generate/watch_impl.dart 107:7         watch
package:build_runner/src/generate/build.dart 138:5              watch
package:build_runner/src/entrypoint/watch.dart 29:25            WatchCommand.run
package:args/command_runner.dart 194:27                         CommandRunner.runCommand
package:args/command_runner.dart 109:29                         CommandRunner.run.<fn>
dart:async                                                      new Future.sync
package:args/command_runner.dart 109:11                         CommandRunner.run
package:build_runner/src/entrypoint/run.dart 22:31              run
.dart_tool\build\entrypoint\build.dart 15:22                    main

pub finished with exit code 1
```

**Comment by jakemac53** [comment]
This error specifically is a result of having both `built_value` and `json_serializable` dependencies, which are trying to write the same file. To fix it, the easiest thing is to explicitly configure them to run on the files they actually need to run on. You can do this using a `build.yaml` file, which would look something like this:

```yaml
targets:
  $default:
    builders:
      json_serializable:
        generate_for:
          - lib/my_json_serializable_classes/*.dart
      built_value_generator:
        generate_for:
          - lib/my_built_value_classes/*.dart
```

There are docs on this format [here](https://github.com/dart-lang/build/blob/master/docs/build_yaml_format.md) and [here](https://github.com/dart-lang/build/blob/master/build_config/README.md)

It is a bug that we report this as a bug in build_runner though, @natebosch I thought we fixed this?
