### ISSUE TITLE
Add configuration set aliases

### ISSUE THREAD

**Issue by natebosch** [dart-lang/build#1544]
Allow builder to define a simple alias which represents multiple options. This would be an enhancement over release/dev option defaults.

Use case: To _truly_ debug in prod mode we would need to set options on multiple builders. The Dart source cleanup would need to stop filtering out Dart files, and the dart2js archive extractor would need to stop filtering out the source map. Our [instructions today](https://github.com/dart-lang/build/pull/1538) recommend running without `--release` and enabling dart2js becaus it's a smaller amount to `--define`, but it also means you're not getting release mode options for any other builder. We could allow both of these builders to agree on what the option alias `debug` or `keep_source_maps` should mean and provide the right configuration for that intention.

Configuration would look something like:

```yaml
builders:
  some_builder_name:
    ...
    defaults:
      release_options:
        compiler: dart2js
        dart2js_use_source_maps: false
    option_aliases:
      debug:
        help: "Keep source maps"
        options:
          dart2js_use_source_maps: true
```

Usage looks like:

`pub run build_runner build --release --define debug`

Behind the scenes we'd merge in the options in the following order:

1. Existing options as we're using them today:
    - builder defaults
    - builder defaults by mode
    - user options
    - user options by mode
2. [Global options from build.yaml](https://github.com/dart-lang/build/issues/1370)
3. **Option aliases**
4. "legacy" style `--define` options

**Comment by natebosch** [comment]
> Should we also enable using these aliases when statically configuring a builder somehow?

I don't see why not as long as we can make a decision about syntax and merge order.

```yaml
targets:
  $default:
    builders:
      some_package:
        option_sets:
          - debug
        options:
          foo: bar
        release_options:
          foo: baz
```

1. builder defaults
2. builder defaults by mode
3. **Option sets from build.yaml**
4. user options
5. user options by mode
6. [Global options from build.yaml](https://github.com/dart-lang/build/issues/1370)
7. **Option aliases**
8. "legacy" style `--define` options
