### ISSUE TITLE
Warn (or error) if `applies_builders` specifies a builder which doesn't exist

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1586]
```yaml
builders:
  json_serializable:
    import: "package:json_serializable/builder.dart"
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": [".g.dart"]}
    applies_builders: ['source_gen|silly_monkey']
#   ^^^^^^^ `silly_monkey` doesn't exist
    auto_apply: dependents
    build_to: cache
```

Tough to debug when you don't know if your code is running....
