### ISSUE TITLE
No .info.json in generated output with --dump-info

### ISSUE THREAD

**Issue by leonsenft** [dart-lang/build#1622]
* [x] Dart SDK Version 2.0.0-dev.64.1
* [x] What package(s) from this repo you are using, and the version
  * build 0.12.7
  * build_config 0.3.1
  * build_modules 0.2.3
  * build_resolvers 0.2.1
  * build_runner 0.9.1
  * build_runner_core 0.2.1
  * build_test 0.10.2+5
  * build_web_compilers 0.4.0+4
* [x] What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
  * angular
  * build_web_compilers
* [x] Whether you are using Windows, MacOSX, or Linux (if applicable) macOS

No .info.json file is generated with the --dump-info dart2js argument specified.

For example, [this project specifies](https://github.com/dart-lang/angular/blob/master/examples/hacker_news_pwa/build.yaml#L1-L14) the argument, and yet when running `pub run build_runner build -r`, no .info.json file is present in the generated output.

I noticed the `--dump-info` argument is forwarded to dart2js.

>[INFO] build_web_compilers|entrypoint on web/main.dart:Running dart2js with **--dump-info** --minify --no-source-maps --omit-implicit-checks --trust-primitives --packages=.package-66f1d85979114be20576af5e91492a11 -oweb/main.dart.js web/main.dart

I tested dart2js with `--dump-info` manually and it does produce the .info.json file, so perhaps a builder is deleting it / not copying it into the generated folder?

Support was added for it relatively recently https://github.com/dart-lang/build/issues/951, so perhaps we've regressed since then? Or is there a mistake in the configuration?

**Comment by jakemac53** [comment]
I think the issue here is that in `release` mode we clean it up. Probably the easiest thing to do is just turn on the dart2js compiler in dev mode, see https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-debug-my-release-mode-web-app-dart2js

**Comment by jakemac53** [comment]
Closing for now, feel free to re-open if you think we should do something further though

**Comment by leonsenft** [comment]
I suspected that was the cause. I tried disabling the postprocess cleaner but couldn't figure out how.

I guess switching the compiler is easy enough. Thanks!

**Comment by jakemac53** [comment]
Fwiw, disabling that can be done with this command line arg:

```
--define "build_web_compilers|dart2js_archive_extractor=filter_outputs=false"
``` 

Or this build.yaml config:

```yaml
targets:
  $default:
    builders:
      build_web_compilers|dart2js_archive_extractor:
        release_options:
          filter_outputs: false
```

The key with the yaml config is the `release_options` not `options`. The builder has a default config for `release_options` which will override your `options`.

**Comment by jakemac53** [comment]
cc @natebosch we should really add a section to the FAQ about options precedence, do we have that documented anywhere?

**Comment by leonsenft** [comment]
Thanks, I didn't realize `postprocessBuilders` were configurable under the `builders` key!

**Comment by lukepighetti** [comment]
Strange behavior indeed.

```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args:
            - --minify
            # - --fast-startup
            # - --trust-primitives
            # - --trust-type-annotations
            # - --omit-implicit-checks
            # - --lax-runtime-type-to-string
            # - --no-source-maps
            # - -O4
            - --dump-info
      build_web_compilers|dart2js_archive_extractor:
        release_options:
          filter_outputs: false
```
