### ISSUE TITLE
Builds on Linux Failing with UTF8 Parse Error

### ISSUE THREAD

**Issue by charliem** [dart-lang/build#1624]
Build runner appears to pause for 10 seconds then outputs the following:
```
run build_runner build
Unable to spawn isolate: .dart_tool/pub/bin/build_runner/build_runner.dart.snapshot.dart2:1:1: Error: Unable to decode bytes as UTF-8.
```

Version: 2.0.0 DEV 64.1 & 65
Platform: Linux, builds correctly on MacOSX 

I have tried reinstalling dart (from the recommend repo). As far as I can tell the installation is correct.

Below is the pubspec, however other similar projects also fail with the same error :
```
name: web_client
version: 6.0.0

environment:
  sdk: '>=2.0.0-dev.64.1 <3.0.0'

dependencies:
  angular: 5.0.0-alpha+15
  angular_components: any
  angular_router: ^2.0.0-alpha+14
  browser_detect: any
  cookie: any
  platform_io:
    path: ../../../../frontend-io
  intl: any
  sass_builder: any
  uuid: any

dev_dependencies:
  build_runner: 0.9.1
  build_web_compilers: 0.4.0+4
```
