### ISSUE TITLE
Failed to precompile build_runner:

### ISSUE THREAD

**Issue by Hexer10** [dart-lang/build#1676]
Hello,
 I'm getting these errors while running `pub get`

```
Working dir: C:\Users\Mattia\Dropbox\PHPStormProjects\Heroes
D:\Tools\DartSDK\dart-sdk\bin\pub.bat get
Resolving dependencies...
Overriding the upper bound Dart SDK constraint to <=2.0.0-dev.69.1 for the following packages:

auth_header, cli_repl, front_end, jaguar_common, kernel, node_preamble, perf_api, quiver_hashcode, sass, tuple

To disable this you can set the PUB_ALLOW_PRERELEASE_SDK system environment variable to `false`, or you can silence this message by setting it to `quiet`.
Got dependencies!
Precompiling executables...
Failed to precompile build_runner:graph_inspector:
file:///C:/Users/Mattia/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/analyzer-0.31.2-alpha.2/lib/src/dart/analysis/library_context.dart:96:34: Error: Can't return a value from a void function.
        return appendLibraryFiles(targetLibrary);
                                 ^
file:///C:/Users/Mattia/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/front_end-0.1.0-alpha.12/lib/src/fasta/deprecated_problems.dart:128:20: Error: This expression has type 'void' and can't be used.
      await client.close(force: true);
                   ^
file:///C:/Users/Mattia/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/front_end-0.1.0-alpha.12/lib/src/fasta/deprecated_problems.dart:148:16: Error: This expression has type 'void' and can't be used.
  await client.close(force: true);
               ^
Failed to precompile build_runner:build_runner:
file:///C:/Users/Mattia/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/front_end-0.1.0-alpha.12/lib/src/fasta/deprecated_problems.dart:128:20: Error: This expression has type 'void' and can't be used.
      await client.close(force: true);
                   ^
file:///C:/Users/Mattia/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/front_end-0.1.0-alpha.12/lib/src/fasta/deprecated_problems.dart:148:16: Error: This expression has type 'void' and can't be used.
  await client.close(force: true);
               ^
file:///C:/Users/Mattia/AppData/Roaming/Pub/Cache/hosted/pub.dartlang.org/analyzer-0.31.2-alpha.2/lib/src/dart/analysis/library_context.dart:96:34: Error: Can't return a value from a void function.
        return appendLibraryFiles(targetLibrary);
                                 ^
Process finished with exit code 0
```

Dart SDK Version: `2.0.0-dev.69.1 (Fri Jul 20 18:30:52 2018 +0200) on "windows_x64"` (Test on linux too)

My pubspec.yaml:
```
name: Heroes
description: An absolute bare-bones web app.
version: 0.0.1
homepage: https://github.com/Hexer10
author: Mattia <hexer504@gmail.com>

environment:
  sdk: '>=2.0.0-dev.68.0 <2.0.0'

dependencies:
    angular: ^5.0.0-beta
    angular_forms: ^2.0.0-beta
    angular_router: ^2.0.0-alpha+15
    http: ^0.11.0
    stream_transform: ^0.0.6
    angular_components: ^0.9.0-beta+1
    jaguar: ^2.1.30

dev_dependencies:
    angular_test: ^2.0.0-beta
    build_runner: ^0.9.2
    build_test: ^0.10.2
    build_web_compilers: ^0.4.1
```
