### ISSUE TITLE
Slow compilation after update build_web_compilers

### ISSUE THREAD

**Issue by Cododoc** [dart-lang/build#1725]
After update build web compilers from 0.4.0+4 to 0.4.1 I found out that compilation time increased.
I open file and add some changes to commented string to check speed.

When I use 
build_web_compilers: 0.4.0+4
Dart VM version: 2.0.0-dev.69.2 (Mon Jul 23 17:10:56 2018 +0200) on "windows_x64"
It take about 5 second.

After upgrade to dart 2.0.0 and use pub get:
```
[Soy.Budget.UI] pub get
Resolving dependencies...
> build_modules 0.3.1+1 (was 0.2.3)
> build_web_compilers 0.4.1 (was 0.4.0+4)
> font_awesome 4.7.0+1 (was 4.7.0)
Changed 3 dependencies!
Precompiling executables...
Precompiled build_runner:graph_inspector.
Precompiled build_runner:build_runner.
exit code 0
```

Changed 3 dependencies. After that the same compilation process take about 20 second.

pubspec.lock:

```
# Generated by pub
# See https://www.dartlang.org/tools/pub/glossary#lockfile
packages:
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.32.4"
  angular:
    dependency: "direct main"
    description:
      name: angular
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.0.0-beta+2"
  angular_ast:
    dependency: transitive
    description:
      name: angular_ast
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.5.4"
  angular_compiler:
    dependency: transitive
    description:
      name: angular_compiler
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.0-alpha+18"
  angular_forms:
    dependency: "direct main"
    description:
      name: angular_forms
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0-beta+2"
  angular_router:
    dependency: "direct main"
    description:
      name: angular_router
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0-alpha+17"
  archive:
    dependency: transitive
    description:
      name: archive
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.4"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.8"
  bazel_worker:
    dependency: transitive
    description:
      name: bazel_worker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.12"
  build:
    dependency: transitive
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.7+3"
  build_config:
    dependency: transitive
    description:
      name: build_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.1+2"
  build_modules:
    dependency: transitive
    description:
      name: build_modules
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.1+1"
  build_resolvers:
    dependency: transitive
    description:
      name: build_resolvers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.1+1"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.2"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.2+2"
  build_web_compilers:
    dependency: "direct dev"
    description:
      name: build_web_compilers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.1"
  built_collection:
    dependency: transitive
    description:
      name: built_collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.3"
  built_value:
    dependency: transitive
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.5.5"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  cli_util:
    dependency: transitive
    description:
      name: cli_util
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.3+2"
  code_builder:
    dependency: transitive
    description:
      name: code_builder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.2"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.14.11"
  config_budget:
    dependency: "direct dev"
    description:
      path: "tool\\config_budget"
      relative: true
    source: path
    version: "0.1.0"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"
  csslib:
    dependency: transitive
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.4+1"
  dart_style:
    dependency: transitive
    description:
      name: dart_style
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.3"
  fixnum:
    dependency: transitive
    description:
      name: fixnum
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.8"
  font_awesome:
    dependency: "direct main"
    description:
      name: font_awesome
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.7.0+1"
  front_end:
    dependency: transitive
    description:
      name: front_end
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.4"
  glob:
    dependency: transitive
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.7"
  graphs:
    dependency: transitive
    description:
      name: graphs
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2+1"
  html:
    dependency: transitive
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.13.3+2"
  http:
    dependency: "direct main"
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+17"
  http_multi_server:
    dependency: transitive
    description:
      name: http_multi_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.3"
  intl:
    dependency: transitive
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.7"
  io:
    dependency: transitive
    description:
      name: io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.3"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1+1"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.9+1"
  kernel:
    dependency: transitive
    description:
      name: kernel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.4"
  logging:
    dependency: transitive
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+2"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.4"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.6"
  mime:
    dependency: transitive
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.6+2"
  package_config:
    dependency: transitive
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.2"
  plugin:
    dependency: transitive
    description:
      name: plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0+3"
  pool:
    dependency: transitive
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.3.6"
  protobuf:
    dependency: transitive
    description:
      name: protobuf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.0+1"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.2"
  pubspec_parse:
    dependency: transitive
    description:
      name: pubspec_parse
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.2+2"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0+1"
  scratch_space:
    dependency: transitive
    description:
      name: scratch_space
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.3+1"
  shelf:
    dependency: transitive
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.3+3"
  source_gen:
    dependency: transitive
    description:
      name: source_gen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.8.3+1"
  source_maps:
    dependency: transitive
    description:
      name: source_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.7"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.1"
  soy_components:
    dependency: "direct main"
    description:
      path: "."
      ref: "0.13.0"
      resolved-ref: "077a5c94016552a8c94593623f8f747482c76ae8"
      url: "git://redmine.sodru.com/soy_components.git"
    source: git
    version: "0.13.0"
  soy_dialog:
    dependency: "direct main"
    description:
      path: "."
      ref: "0.2.0"
      resolved-ref: "06e67fc068eccedbff6d28997616a01063da1677"
      url: "git://redmine.sodru.com/soy_dialog.git"
    source: git
    version: "0.2.0"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.3"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.8"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.14+1"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  tuple:
    dependency: transitive
    description:
      name: tuple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.6"
  utf:
    dependency: transitive
    description:
      name: utf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.0+5"
  uuid:
    dependency: "direct main"
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  watcher:
    dependency: transitive
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+10"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.15"
sdks:
  dart: ">=2.0.0 <3.0.0"
```

**Comment by jakemac53** [comment]
With `build_modules` 0.3.1 we changed the default module strategy to "coarse", which in effect ends up creating larger modules.

There are several reasons for this change, primarily the coarse strategy doesn't require a resolver which helps a lot for projects that otherwise don't need one (simple vm tests for instance).

You can try opting into the "fine" strategy again, with a build.yaml like this:

```yaml
targets:
  $default:
    builders:
      build_modules|modules:
        options:
          strategy: coarse
```

**Comment by jakemac53** [comment]
I do think there is a lot of room to improve the module structure, even with the coarse strategy. For instance we could come up with a "maximum size" per module and then try to smartly create modules of that size. The problem there of course is the smart part :).

**Comment by matanlurey** [comment]
@Cododoc Could you please try the suggestions here and let us know?

**Comment by Cododoc** [comment]
I tried your suggestion. Look like it help.
My build file:
```
targets:
  $default:
    sources:
      - lib/**
      - web/**
    builders:
      build_modules|modules:
        options:
          strategy: fine
      config_budget:
        options:
          api_uri: 'http://localhost:54607/api'
        release_options:
          api_uri: './api'
      build_web_compilers|entrypoint:
        generate_for:
        - web/**.dart
        release_options:
          dart2js_args:
          - --fast-startup
          - --minify
          - --omit-implicit-checks
          - --trust-primitives
```

Before changing build file - **25.9s**: 
```
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 8ms
[INFO] Running build completed, took 25.5s
[INFO] Caching finalized dependency graph completed, took 311ms
[INFO] Succeeded after 25.9s with 77 outputs (77 actions)
```

After - **7.4s**:
```
[INFO] ------------------------------------------------------------------------
[INFO] Starting Build
[INFO] Updating asset graph completed, took 4ms
[INFO] Running build completed, took 6.7s
[INFO] Caching finalized dependency graph completed, took 678ms
[INFO] Succeeded after 7.4s with 76 outputs (76 actions)
```
