### ISSUE TITLE
"Cannot overwrite inputs"

### ISSUE THREAD

**Issue by filiph** [dart-lang/build#175]
When running the watcher for a while, it starts failing with "Cannot overwrite inputs."

```
[INFO] Build: Checking build script for updates completed, took 35ms
[INFO] Build: Finalizing build setup completed, took 207ms
[SEVERE] Build: Failed after 255ms
InvalidOutputException: Asset: edgehead|lib/fractal_stories/actor.g.dart
Cannot overwrite inputs.
package:build/src/generate/build_impl.dart 518:11  BuildImpl._runBuilder.<_runBuilder_async_gen_body>
dart:async                                         _AsyncStarStreamController.addError
package:build/src/generate/build_impl.dart 584:3   BuildImpl._runBuilder.<_runBuilder_async_gen_body>
dart:async                                         _StreamIterator.moveNext
package:build/src/generate/build_impl.dart 441:16  BuildImpl._runPhases.<async>.<fn>.<async>
dart:async                                         Future.wait
package:build/src/generate/build_impl.dart 438:20  BuildImpl._runPhases.<async>
dart:async                                         Future.Future.microtask
...
```

The thing is that this file (`actor.g.dart`) is generated. It's not an input, at least not to my understanding. Here's my setup.

```
final PhaseGroup phases = new PhaseGroup.singleAction(
    new GeneratorBuilder([new BuiltValueGenerator()]),
    new InputSet('edgehead', const [
      'lib/fractal_stories/actor.dart',
      'lib/fractal_stories/room.dart',
      'lib/fractal_stories/team.dart',
      'lib/src/**/*_situation.dart',
    ]));
```

This did not happen when I had a Watcher set up in IntelliJ (that watcher just ran build instead of watch). That worked well but it was also way too slow. So I thought I'd rather run build's watcher in a terminal. That's when I started encountering the problem.

**Comment by jakemac53** [comment]
That is definitely weird, but I can't seem to reproduce it (using the example in the built_json package). I tried switching back and forth between both the build and watch options as well.

Do you know of any consistent repro steps?

**Comment by jakemac53** [comment]
fwiw, you might be able to just delete your `.dart_tool/build` directory to solve the issue.

**Comment by filiph** [comment]
I just got to a repro, I think. And it's on a clean clone of the repo, so I assume deleting `.dart_tool/build` would not help me.

```
git clone https://github.com/filiph/edgehead.git
cd edgehead
```

Edit pubspec.yaml: delete the dependency on `egamebook` and switch to pub dependency of slot_machine. Your pubspec should now look like this:

```
name: edgehead
version: 0.0.1
description: A demo of fractal_stories.
author: Filip Hracek <filip.hracek@gmail.com>
homepage: https://www.egamebook.com

environment:
  sdk: '>=1.21.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^0.1.0'
  sass: '^0.4.2'
  built_collection: 1.2.0
  built_value: 0.4.3
#  egamebook:
#    path: ../egamebook
  meta: any
  logging: any
  path: any
  slot_machine: any

dev_dependencies:
  build: any
  built_value_generator: any
  simple_preprocessor: any
  source_gen: any
  test: any

transformers:
- simple_preprocessor
- dart_to_js_script_rewriter
- sass
```

Then:

```
pub get
dart tool/watch.dart
```

Wait for initial source gen to finish.

Then open `lib/src/fight/fight_situation.dart` and start editing that file. (I used sublime so that I know this is not an interference with IntelliJ.)

Add new field to the `FightSituation` abstract class. Like this:

```
int get something;
```

Save. Then immediately after that, add another field:

```
bool get elserg;
```

Save.

The build process should go into an infinite loop, complaining about `actor.g.dart`. If not, try adding more fields or saving with a syntax error.
