### ISSUE TITLE
Defining builder and target in same file not working

### ISSUE THREAD

**Issue by enyo** [dart-lang/build#1769]
```
Dart VM version: 2.0.0 (Fri Aug 3 10:53:23 2018 +0200) on "macos_x64"
build_runner: ^0.10.0
```

I'm trying to write a builder and use it in the same project.

This is my `build.yaml`:

```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
        - test/unit/web/**.browser_test.dart
        - web/**.dart
  icons:
    sources:
    - lib/src/web/shared/angular/components/icon/src/*.svg
    builders:
      exitlive|iconsBuilders:
        generate_for:
        - "*"

builders:
  exitlive|iconsBuilder:
    import: "package:exitlive/builders/icons_builder.dart"
    builder_factories: ["iconsBuilder"]
    build_extensions: {"$lib$": ["test_file"]}
    build_to: source
    auto_apply: root_package
```

The builder works initially (I assume because auf `auto_apply: root_package`) but I get a warning at the beginning:

```
[WARNING] Configuring `exitlive|iconsBuilders` in target `exitlive:icons` but this is not a known Builder
```

So any changes to the files aren't triggering a rebuild.

Is there something wrong with my `build.yaml` or is defining a builder and using it in the same `build.yaml` not supported?

**Comment by jakemac53** [comment]
Oh! I think I see the issue here now, in your builders section you are specifying the "full" name, including the package, but the package part is implicit. Can you try changing:

```yaml
builders:
  exitlive|iconsBuilder:
```

to:

```yaml
builders:
  iconsBuilder:
```

And see if that fixes the issue?

**Comment by jakemac53** [comment]
Ah ok, ill look into this then, it sounds like a bug.

As a temporary workaround you can explicitly enable it, by putting `enabled: true` under the builder config for your `icons` target. Note also that there is a bit of a weirdness where I believe you may need to include `$lib$` in the `icons` target sources.

**Comment by enyo** [comment]
Mh, adding `enabled: true` doesn't change anything (since I guess, the target can't find any suitable builder, so it can't enable it).

With a bit of weirdness you mean in my configuration, or in the way the builder requires it currently?

**Comment by jakemac53** [comment]
So your builder is operating on the `$lib$` placeholder file, but for that to work that file actually has to be included in the sources of the target (even though it isn't a real source). The "weirdness" is the fact that you need to reference a file as a source that doesn't actually exist.

**Comment by enyo** [comment]
Ok, thanks to the help from @jakemac53 I fixed the reason why my builder wasn't working:

I assumed that the builder would be invoked anytime files in the `sources` of my target are changed, but this is not enough. Inside the `build` method of my builder I still needed to actually find and read the assets with `buildStep.findAssets()` which is something that I need to do anyway but hadn't implemented yet because I thought I had run into another issue.

The Warning still appears though, so I'll leave it up to you when you want to close it!

Thanks

**Comment by jakemac53** [comment]
I was actually unable to reproduce the warning message, is it possible for you to create a minimal repro? 

My example build.yaml looks like this, for a package called `_test`:

```yaml
targets:
  $default:
    builders:
      _test|myBuilder:
        options:
          foo: bar
builders:
  myBuilder:
    import: 'package:_test/builder.dart'
    builder_factories: ["myBuilder"]
    build_extensions: {"$lib$": ["files.txt"]}
    auto_apply: root_package
```

**Comment by enyo** [comment]
I'll try next week

**Comment by natebosch** [comment]
In the first error message:

> ```Configuring `exitlive|iconsBuilders` in target `exitlive:icons` but this is not a known Builder```

Note that your builder was named `iconsBuilder` with no `s`.

In the second error message:

> ```Configuring `iconsBuilders|iconsBuilders` in target `exitlive:icons` but this is not a known Builder```

The part before the `|` is the package name - if you are defining the builder in the same package the first part of the key will always be `exitlive|`.

I think this is a combination of a typo in the key and some confusion over how the builder won't get reran if it didn't read any inputs that changed.

**Comment by enyo** [comment]
@natebosch omg, you're right. I've looked at this for hours, and a dozen people have gone over it, and nobody noticed the additional `s`...

You're completely right: it's a combination of this typo, and my confusion over changed inputs.

Thank you two for you help!

**Comment by fleepgeek** [comment]
Hi. I'm facing something similar. My generator reads a file that is outside my `models` package so i created a `build.yaml` file in the same level with my `pubspec.yaml` file. It generates the correct files in the `models` package but reads a file from some other package( `lib/scoped/` ) that is not part of my `built_value` classes. 
So, i created a build.yaml file as sussgested by @jakemac53  here [https://github.com/dart-lang/build/issues/1537#issuecomment-395768087](url)
Here is my build.yaml:
```
targets:
  $default:
    builders:
      built_value_generator:
        generate_for:
          - lib/models/*.dart
```

Then it gave me this:
```
[WARNING] Configuring `built_value_generator|built_value_generator` in target `property_finder:property_fin
der` but this is not a known Builder
```
And it still also outputs the previous error:
```
[SEVERE] built_value_generator|built_value on lib/scoped/property_scoped.dart:
Unknown error in BuiltValueGenerator for property_finder|lib/scoped/property_scoped.dart.
NoSuchMethodError: The getter 'displayName' was called on null.
Receiver: null
Tried calling: displayName
[WARNING] built_value_generator|built_value on lib/scoped/property_scoped.dart:
Missing "part 'property_scoped.g.dart';".
[INFO] Running build completed, took 11.5s

```

**Comment by jakemac53** [comment]
@fleepgeek it looks like the builder in built_value_generator is called `built_value_generator|built_value` not `built_value_generator|built_value_generator`, so actually your issue was even more similar to the original issue than you realized :D.

**Comment by fleepgeek** [comment]
Oh wow! Thanks @jakemac53 . This solved my issue.

**Comment by lukepighetti** [comment]
I ran into the exact same problem. Perhaps the docs need to be updated to reflect the format for builder keys

**Comment by jakemac53** [comment]
We do print warnings if a builder key is not recognized which is intended to help with this.

**Comment by lukepighetti** [comment]
It wasn't verbose enough to be helpful for me. I ended up having to search for this issue. It's one of those "THERE WAS A PROBLEM!" kinds of messages in this context.

**Comment by frank06** [comment]
I'm seeing `[WARNING] Configuring `ob_test:data_model_builder` in target `ob_test:ob_test` but this is not a known Builder`

The `build.yaml` starts with:

```yaml
targets:
  $default:
    builders:
      ob_test|data_model_builder:
        enabled: true

builders:
  ob_test|data_model_builder:
    import: "package:ob_test/builders/data_model_builder.dart"
    builder_factories: ["dataModelBuilder"]
    # ...
```

There are no typos.

And what's really weird, this 100% has worked with the same configuration. I then changed a few parameters in the yaml and I keep getting this warning.

If I remove the `enabled: true` block I don't get the warning but I also don't get any builds. Finishes the run with `with 0 outputs (0 actions)`

What is going on?

Is there a way to force builds? disregard the cache?  Deleting `.dart_tool` does not help. It only makes me have to run `dart pub get` again.

Too many hours on this seemingly simple task, I'm frustrated so maybe I'm missing something obvious. Thank you.

**Comment by natebosch** [comment]
> I keep getting this warning.

Do you get any other warnings? Can you try running `dart run build_runner doctor` to see if it has any warnings?

This looks like the builder definition could be invalid and it's getting filtered out, but there should be a warning for that, and I'm not sure if we would treat it as an error instead for the root package.

**Comment by frank06** [comment]
Doctor outputs this:
```
[INFO] Generating build script completed, took 401ms
[WARNING] Builder objectbox_generator:generator uses input extension $test$ which is not specified in the `build.yaml`
```

I found what causes it: I declared `objectbox_generator|generator` under `builders` in order to change a setting. It would be helpful if `build` complained about this.

I figured I have to name it something else (`ob_test|generator`?) and mark `objectbox_generator|generator` with `enabled: false`.

Is there another way of working with build via Dart directly, other than build.yaml?  I run into all sorts of problems and it's very difficult to understand what's happening.

**Comment by natebosch** [comment]
> I found what causes it: I declared `objectbox_generator|generator` under `builders` in order to change a setting. It would be helpful if `build` complained about this.
> 
> I figured I have to name it something else (`ob_test|generator`?) and mark `objectbox_generator|generator` with `enabled: false`.

FWIW when you want to refer to builders within your package you can prefix the builder name with `:` to fill in the package name automatically and not have to copy it from the pubspec into the `build.yaml`.

Under the `targets -> $default -> builders` section, use a `:` prefix and it will be filled in with the package name.
For the keys under the `builders` section you can even omit the leading `:`.

```yaml
targets:
  $default:
    builders:
      :data_model_builder:
        enabled: true

builders:
  data_model_builder:
    import: "package:ob_test/builders/data_model_builder.dart"
    builder_factories: ["dataModelBuilder"]
    # ...
```
