### ISSUE TITLE
Make is a lot easier to enable including source_maps in dart2js output

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#1779]
See https://stackoverflow.com/questions/51944375/webdev-serve-missing-output-for-js-map-files

This is the best example we have – crazy - https://github.com/dart-lang/angular_components_example/blob/master/example/angular_components_example/build.yaml

**Comment by natebosch** [comment]
To be precise, the code it takes to do this is:

```yaml
global_options:
  build_web_compilers|dart_source_cleanup:
    release_options:
      enabled: false
  build_web_compilers|dart2js_archive_extractor:
    release_options:
      filter_outputs: false
```

The main difficulty here is having to configure multiple builders so we could solve this easier after we implement #1544
