### ISSUE TITLE
RangeError: Value not in range: 49

### ISSUE THREAD

**Issue by darylrue** [dart-lang/build#1791]
About 3 times out of 4 when running the built-in Sample Angular Dart App in IntelliJ (using Chrome), the build fails. Here is the console output:

```
"C:\Program Files\Dart\dart-sdk\bin\pub.bat" global run webdev serve web:50842
[INFO] Setting up file watchers...
[INFO] Waiting for all file watchers to be ready...


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


RangeError: Value not in range: 49
dart:core                                                   _StringBase.substring
package:build_runner/src/watcher/graph_watcher.dart 105:34  PackageGraphWatcher._nestedPaths.<fn>
dart:core                                                   Iterable.toList
package:build_runner/src/watcher/graph_watcher.dart 106:10  PackageGraphWatcher._nestedPaths
package:build_runner/src/watcher/graph_watcher.dart 73:30   PackageGraphWatcher._watch.<fn>
dart:collection                                             MapView.forEach
package:build_runner/src/watcher/graph_watcher.dart 68:24   PackageGraphWatcher._watch
package:build_runner/src/watcher/graph_watcher.dart 49:17   PackageGraphWatcher.watch.<fn>.<fn>
package:build_runner_core/src/logging/logging.dart 43:24    logTimedSync
package:build_runner/src/watcher/graph_watcher.dart 46:25   PackageGraphWatcher.watch.<fn>
dart:async                                                  _ForwardingStream.listen
package:stream_transform/src/from_handlers.dart 59:29       _StreamTransformer.bind.<fn>
dart:async                                                  _StreamImpl.listen
package:stream_transform/src/take_until.dart 37:29          _TakeUntil.bind.<fn>
dart:async                                                  _StreamImpl.listen
package:stream_transform/src/buffer.dart 91:25              _Buffer.bind.<fn>
dart:async                                                  _StreamImpl.listen
package:stream_transform/src/from_handlers.dart 59:29       _StreamTransformer.bind.<fn>
dart:async                                                  _StreamImpl.listen
package:build_runner/src/generate/watch_impl.dart 299:10    WatchImpl._run
package:build_runner/src/generate/watch_impl.dart 204:20    new WatchImpl
package:build_runner/src/generate/watch_impl.dart 124:5     _runWatch
package:build_runner/src/generate/watch_impl.dart 86:15     watch
package:build_runner/src/generate/build.dart 168:5          watch
package:build_runner/src/entrypoint/serve.dart 69:25        ServeCommand.run
package:args/command_runner.dart 194:27                     CommandRunner.runCommand
package:args/command_runner.dart 109:29                     CommandRunner.run.<fn>
dart:async                                                  new Future.sync
package:args/command_runner.dart 109:11                     CommandRunner.run
package:build_runner/src/entrypoint/run.dart 22:31          run
.dart_tool\build\entrypoint\build.dart 102:22               main

Dart Dev Server terminated
```

This is the code referenced in the last line of the stack trace:

```
.map((node) => node.path.substring(rootNode.path.length + 1) + '/')
```

Here is the pubspec.yaml:

```
name: SampleAngularDartApp
description: A web app that uses AngularDart Components
# version: 1.0.0
# homepage: https://www.example.com
# author: daryl.rue <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_components: ^0.9.0

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^0.10.0
  build_test: ^0.10.2
  build_web_compilers: ^0.4.0
  test: ^1.0.0
```
