### ISSUE TITLE
Automatically skip applications that we know aren't supported for the current platform 

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1810]
## Problem

For most multi-platform packages there are some entrypoints that can only be compiled with a certain platform. Today, you are required to create a special `build.yaml` script which disables the builders for that platform, something like this:

```
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          exclude:
            - test/vm_only_test.dart
      build_vm_compilers|entrypoint:
        generate_for:
          exclude:
            - test/web_only_test.dart
```

## Proposal

We now have enough information to know whether or not an individual library supports a specific platform, so we could instead make those builders bail out if any of their transitive modules were not supported for the current platform.

We could add a boolean flag to each module, `isSupported`, which could propagate to anything that depends on that module, which would make the check cheap (only look at immediate deps).

## Benefits

- Removes custom build.yaml config, everything "just works"
- Relatively simple

## Potential Issues

- Unless we output a warning or error in this scenario (another option?), it could be confusing why a certain application wasn't being compiled for a specific platform when you thought it should be.
