### ISSUE TITLE
Switching between fine and coarse modules causes unrecoverable build failures

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#1833]
Using the `_test` project if you do a build and then add the following to the build.yaml:

```
global_options:
  build_modules|dartdevc:
    options:
      strategy: fine
```

And do another build you get a bunch of errors about missing `.module` files.
