### ISSUE TITLE
NoSuchMethodError: The method 'packageNodes' was called on null.

### ISSUE THREAD

**Issue by aasirmutwalli22** [dart-lang/build#1877]

**Comment by jakemac53** [comment]
I am not sure how you got in this particular state, but the general error that this was trying to warn about is you are attempting to serve a directory which doesn't have any sources.

The most likely cause is that you are using a non-standard directory (see https://www.dartlang.org/tools/pub/package-layout). If you want to use a different directory, you will need to set up a custom `build.yaml` file with those sources, something like:

```yaml
targets:
  $default:
    sources:
      - lib/**
      - other/**
```
