### ISSUE TITLE
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart in Travis

### ISSUE THREAD

**Issue by skybur** [dart-lang/build#1900]
Hello, 
I've encountered this error when running build_runner for Flutter built_value in travis.
Is there anything I can do to solve this problem? Thank you.
This is my .travis.yml configuration:
```
os: linux
language: android
licenses:
  - android-sdk-preview-license-.+
  - android-sdk-license-.+
  - google-gdk-license-.+
android:
  components:
    - tools
    - platform-tools
    - build-tools-26.0.2
    - build-tools-27.0.3
    - build-tools-28.0.2
    - android-27
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
jdk: oraclejdk8
sudo: false
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++6
      - fonts-droid
before_script:
  - wget http://services.gradle.org/distributions/gradle-4.1-all.zip
  - unzip -qq gradle-4.1-all.zip
  - export GRADLE_HOME=$PWD/gradle-4.1
  - export PATH=$GRADLE_HOME/bin:$PATH
  - git clone https://github.com/flutter/flutter.git -b beta --depth 1
  - export PATH=$PWD/flutter/bin:$PATH
script:
  - ./build.sh
  - flutter build apk --flavor stage -t lib/main-stage.dart
cache:
  directories:
    - $HOME/.pub-cache
    - .dart_tool/build
branches:
  only:
    - master
    - travis-test
```
build.sh:
```
echo "Running Flutter Doctor"
flutter doctor
echo "Updating Packages"
flutter packages get
echo "Generating Code"
flutter packages pub run build_runner build
echo "Copying Icon"
flutter pub pub run flutter_launcher_icons:main
```

* [ ] Dart VM version: 2.1.0-dev.8.0.flutter-bf26f760b1
* [ ] `build: ^1.0.1` and `build_runner: ^1.1.1`
* [ ] `built_value_generator: ^6.1.5`
* [ ] Linux
