### ISSUE TITLE
--delete-output-path config option :: cli and yml support

### ISSUE THREAD

**Issue by zanuka** [dart-lang/build#1902]
It would be handy to have the same `--delete-output-path` build option that angular-cli has, especially when testing apps via Docker/nginx locally. 

Then you can just create a link once like:
```
docker run -d -p 80:80 -v $(pwd)/build/web:/usr/share/nginx/html nginx:latest
```

And in your dev workflow, running build_runner command with `--delete-output-path` set or set it in the build.yaml like:

```
options:
          compiler: dart2js
          dart2js_args:
          - --no-delete-output-path (example)
```

then you don't have to recreate the link to nginx each time for local docker testing. 

or perhaps there's already a way to do this I'm just unaware of...
