### ISSUE TITLE
Is deferred loading not supported by webdev build?

### ISSUE THREAD

**Issue by stephan-gruen** [dart-lang/build#1922]
```
<div *ngIf="loginStatus == '2'">
	<geo-users-app @deferred></geo-users-app>
</div>
```
	
```
dev_dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.0
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3+3
  build_web_compilers: ^0.4.4+3
  test: ^1.3.4	
```

Build with  
"D:\dart-sdk\dart-sdk 2.2.0-dev.0.0\bin\pub.bat" global run webdev build --output=web:build

As I just noticed the output is now only one file: main.dart.js 

Prior to dart 2 the component I want to lazy load was transpiled to a second file called main.dart.js_1.part.js

Do I have to add a directive now? Is it no longer supported?

**Comment by jakemac53** [comment]
Webdev should generally support deferred libraries - but I don't know what the `@deferred` for angular does.

**Comment by natebosch** [comment]
Deferred loading can be tricky to get right, if you have something else which imports that code without deferred on the import it will cause it to be pulled in to the main output.

There may also be a bug in angular around this currently. cc @leonsenft who I think had been looking at something similar.

**Comment by jakemac53** [comment]
@kevmoo can you move this to the angular repo? (you have to be an admin to use that feature...)

**Comment by stephan-gruen** [comment]
If I user 
```
dependencies:
  angular: ^5.0.0-beta+3
  angular_components: ^0.9.0-beta+3

dev_dependencies:
  angular_test: ^2.0.0-beta+3
  build_runner: ^0.10.0
  build_test: ^0.10.3+1
  build_web_compilers: ^0.4.1
  test: ^1.3.0
```

instead of

```
dependencies:
  angular: ^5.1.0
  angular_components: ^0.10.0

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.1.2
  build_test: ^0.10.3+3
  build_web_compilers: ^0.4.4+3
  test: ^1.3.4 
```

with 

`"D:\dart-sdk\dart-sdk 2.2.0-dev.0.0\bin\pub.bat" global run webdev build --output=web:build`

it totally works again. So it is a bug.
I also created a new simple project with the stagehand example "todolist" and changed

`<todo-list></todo-list>`

to 

```
<div *ngIf="loginStatus == '2'">
    <todo-list @deferred></todo-list>
</div>
```

and I get exactly the same results.
