### ISSUE TITLE
Missing null check causes crash on version checking

### ISSUE THREAD

**Issue by miyoyo** [dart-lang/build#1923]
Using a fresh dart install from Chocolatey (`Dart VM version: 2.1.0 (Tue Nov 13 18:22:02 2018 +0100) on "windows_x64"`), and the web-simple project from `stagehand`, when running `webdev serve -r`, this error occurs.

```
NoSuchMethodError: The method '>=' was called on null.
Receiver: null
Tried calling: >=(Instance of 'Version')
dart:core                                              Object.noSuchMethod
package:build_runner/src/entrypoint/test.dart 144:26   _packageTestSupportsSymlinks
package:build_runner/src/entrypoint/test.dart 26:15    new TestCommand
package:build_runner/src/entrypoint/runner.dart 28:16  new BuildCommandRunner
package:build_runner/src/entrypoint/run.dart 21:16     run
.dart_tool\build\entrypoint\build.dart 88:22           main
```
[Here is the line mentionned by the stack trace](https://github.com/dart-lang/build/blob/5d4ef81f9cd846013c147671bd54b1dcfbe2eb9c/build_runner/lib/src/entrypoint/test.dart#L144)

Pubspec:
```yaml
name: test
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com
#author: Miyoyo <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

#dependencies:
#  path: ^1.4.1

dev_dependencies:
  build_runner: ^1.1.2
  build_web_compilers: ^0.4.0
```
