### ISSUE TITLE
PackageGraph chokes on 'hosted' dependencies

### ISSUE THREAD

**Issue by lpodmolik** [dart-lang/build#193]
PackageGraph only understands pub, git and path dependencies.  In our projects we often use hosted dependencies like this:

```
some_package:
    hosted:
        name: some_package
        url: http://bld-01.acme.com:8085
    version: ^0.1.3
```

In checked mode this results in:

```
Unhandled exception:
'package:build_runner/src/package_graph/package_graph.dart': Failed assertion: line 162 pos 10: 'source.keys.length == 1': is not true.
```

Unchecked, it hits the default case in the subsequent switch statement on type, and throws a different exception.
