### ISSUE TITLE
Error running `pub run build_runner build` from package:resource

### ISSUE THREAD

**Issue by corwinsheahan-wf** [dart-lang/build#1966]
Hi there! 

I'm hitting an issue when running `pub run build_runner build`. This is the error:
```
[SEVERE] build_web_compilers|ddc on package:resource/resource.dartdevc.module:
Error compiling dartdevc module:resource|lib/resource.ddc.js

[error] Target of URI doesn't exist: 'io_none.dart'. (package:resource/src/resource_loader.dart, line 8, col 8)

Please fix all errors before compiling (warnings are okay).
}
```
The repo this is happening in was building successfully as recently as two days ago. I also tried checking out commits from that time and have still gotten the same error. Basically, I don't _think_ that a change in the repo I was working in caused this error to pop up. 

The package `resource` is brought in transitively through `dart_dev` and only `dart_dev` (verified via pubviz). Commenting out the usages of `resource` in `dart_dev` allows builds to run without error. I also don't get an analysis error when looking at the offending line in `resource_loader.dart`, and `io_none.dart` definitely exists, so I'm not sure why this is happening. 

Any ideas?

* Dart SDK Version (`dart --version`): 2.1.0
```
build:
    dependency: "direct dev"
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  build_config:
    dependency: transitive
    description:
      name: build_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.1+4"
  build_modules:
    dependency: transitive
    description:
      name: build_modules
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  build_resolvers:
    dependency: transitive
    description:
      name: build_resolvers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.2+7"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  build_test:
    dependency: "direct dev"
    description:
      name: build_test
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.4"
  build_web_compilers:
    dependency: "direct dev"
    description:
      name: build_web_compilers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
```

**Comment by jakemac53** [comment]
I think this is related to the conditional imports not working fully in analyzer (or at least not how we expect them to).

For the web platform, we should be selecting the `io_html.dart` import here - it should never attempt to load the `io_none.dart` file at all. Thus, we don't copy that file to the sandbox directory where we run DDC.

**Comment by jakemac53** [comment]
Ah ya, see https://github.com/dart-lang/sdk/issues/34177.

Essentially, package:resource could add `// ignore: URI_DOES_NOT_EXIST` comments on all the conditional imports as a temporary fix.

**Comment by jakemac53** [comment]
cc @stereotype441 @jmesserly what do we want to do here?

**Comment by stereotype441** [comment]
@MichaelRFairhurst, I believe you were going to look into dart-lang/sdk#34177.  Do you have an opinion?

**Comment by georgelesica-wf** [comment]
I'm seeing what might be a related issue (if not I can create a new issue). My package has its own builder that I want run, and I'm also using `json_serializable`. When I run a build, all the `.g.dart` files get deleted and then the build fails (see below), and the files end up deleted. If I check the files out again to restore them and run the build again, it succeeds.

```
[INFO] Generating build script completed, took 231ms
[INFO] Reading cached asset graph completed, took 61ms
[INFO] Checking for updates since last build completed, took 444ms
[WARNING] Invalidating asset graph due to build script update!
[INFO] Cleaning up outputs from previous builds. completed, took 6ms
[INFO] Generating build script completed, took 52ms
[INFO] Creating build script snapshot... completed, took 4.5s
[SEVERE] Failed to snapshot build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
[SEVERE] lib/src/models/class.dart:4:6: Error: Error when reading 'lib/src/models/class.g.dart': No such file or directory
part 'class.g.dart';
     ^
... snip ...
```

So if I want a new build to happen, here's what I have to do: `prbr build; git checkout -- lib/src/models/*.g.dart; prbr build --delete-conflicting-outputs`.

Here's my `build.yaml`:

```
builders:
  semver_audit:
    import: 'package:semver_audit/semver_audit.dart'
    builder_factories:
      - semverBuilder
    build_extensions:
      .dart:
        - .semver
    auto_apply: root_package
    build_to: source
```

I really don't know if this is something I'm doing wrong, a problem with `build_runner`, a problem with `json_serializable`, or something entirely different.
