### ISSUE TITLE
generic functions not supported

### ISSUE THREAD

**Issue by jimmyff** [dart-lang/build#206]
I'm getting the following error when trying to run my build script:

> jimmypro:dn jimmyff$ pub run tool/build.dart
> 'package:build/src/builder/logging.dart': error: line 12 pos 11: generic functions not supported
> `T scopeLog<T>(T fn(), Logger log) => runZoned(fn, zoneValues: {logKey: log});`

deps:
```
environment:
  sdk: '>=1.9.1 <2.0.0'

dependencies:
  build: ^0.7.0 # Angular2 needs 0.5.0
  # build_test: ^0.4.0 // todo: not yet implemented
  crypto: ^2.0.0
  http: ^0.11.3+9
  uuid: ^0.5.3

dev_dependencies:
  test: ^0.12.7
  build_runner: ^0.3.0
```
