### ISSUE TITLE
Importing a subclass to deserialize using json_serializer throws build errors

### ISSUE THREAD

**Issue by jasonlewicki** [dart-lang/build#2073]
I want to be able to import subclass models that would be used in other json objects. to do that and not replicate code they need to be in separate files and imported.

this works: 

**http_errors.dart**
```dart
import 'package:json_annotation/json_annotation.dart';
import 'package:xxx/objects/error.dart';
part 'http_errors.g.dart';

@JsonSerializable()
class HTTPErrors {
  
  List<Error> errors;

  HTTPErrors(this.errors);
  factory HTTPErrors.fromJson(Map<String, dynamic> json) => _$HTTPErrorsFromJson(json);
  
  Map<String, dynamic> toJson() => _$HTTPErrorsToJson(this);
}

@JsonSerializable()
class Error {
  Error(this.field, this.detail);

  String field;
  String detail;

  factory Error.fromJson(Mapx<String, dynamic> json) => _$ErrorFromJson(json);
  Map<String, dynamic> toJson() => _$ErrorToJson(this);
}
```

this does not:
**http_errors.dart**
```dart
import 'package:json_annotation/json_annotation.dart';
import 'package:xxx/objects/error.dart';
part 'http_errors.g.dart';

@JsonSerializable()
class HTTPErrors {
  
  List<Error> errors;

  HTTPErrors(this.errors);
  factory HTTPErrors.fromJson(Map<String, dynamic> json) => _$HTTPErrorsFromJson(json);
  
  Map<String, dynamic> toJson() => _$HTTPErrorsToJson(this);
}
```

**error.dart**
```dart
import 'package:json_annotation/json_annotation.dart';
part 'error.g.dart';
@JsonSerializable()
class Error {
  Error(this.field, this.detail);

  String field;
  String detail;

  factory Error.fromJson(Mapx<String, dynamic> json) => _$ErrorFromJson(json);
  Map<String, dynamic> toJson() => _$ErrorToJson(this);
}
```

the build output is:
```
[INFO] Running build...
[SEVERE] json_serializable on lib/objects/http_errors.dart:
Error running JsonSerializableGenerator
Could not generate `fromJson` code for `errors` because the type is undefined.
package:xxx/objects/http_errors.dart:10:15
  ╷
10│   List<Error> errors
```

the build.yaml file is this:
```yaml
targets:
  $default:
    builders:
      json_serializable:
        options:
          # Options configure how source code is generated for every
          # `@JsonSerializable`-annotated class in the package.
          #
          # The default value for each is listed.
          #
          # For usage information, reference the corresponding field in
          # `JsonSerializableGenerator`.
          any_map: false
          checked: false
          create_factory: true
          create_to_json: true
          disallow_unrecognized_keys: false
          explicit_to_json: true
          field_rename: none
          generate_to_json_function: true
          include_if_null: true
          nullable: true
          use_wrappers: false
```
the `explicit_to_json` flag has been tried both true and false.

rolled back build_runner from 1.2.8 -> 1.2.3 and it works

From my .packages file:
`analyzer-0.34.3` works
`analyzer-0.35.3` doesn't work
