### ISSUE TITLE
Slow angular dart builds with ddk

### ISSUE THREAD

**Issue by nshahan** [dart-lang/build#2115]
Performance page attached of an incremental build making an edit to a file in the angular_components_example package.
[$perf.html.zip](https://github.com/dart-lang/build/files/3023858/perf.html.zip)

Repro:
1) Checkout https://github.com/dart-lang/angular_components master.
2) Add dependency overrides in https://github.com/dart-lang/angular_components/blob/master/examples/angular_components_example/pubspec.yaml.
```
  build_modules:
    git:
      url: git@github.com:dart-lang/build.git
      ref: kernel-caching-incremental
      path: build_modules
  build_web_compilers:
    git:
      url: git@github.com:dart-lang/build.git
      ref: kernel-caching-incremental
      path: build_web_compilers
```
3) run a `pub upgrade` and `build_runner serve web` (initial build should take roughly 1min).
4) Make an edit to https://github.com/dart-lang/angular_components/blob/master/examples/angular_components_example/lib/gallery/home.html (incremental build should take roughly 5sec).
