### ISSUE TITLE
testBuilder method does not work with GenerateForAnnotated generators

### ISSUE THREAD

**Issue by elnurvl** [dart-lang/build#2292]
I have a custom generator that extends from `GenerateForAnnotated `class. I want to debug my generator with breakpoints. In order to do that, I am using `testBuilder `method of `build_test ` package.

However, the debugger does not hit `generateForAnnotatedElement `method and testBuilder’s result is an empty asset.

When I change my generator to inherit from `Generator `class, the package works and the debugger hits the `generate `method.

Why does it happen? Is it a bug? How can I debug the generator?

Test file:
```
void main() {
  group('generator tests', () {
    test('generator test', () async {
      var builder = PartBuilder([TestGeneratorAnnot()], '.g.dart');
      var assets = {
        'annotations|lib/annotations.dart': annotations,
        'source_gen_test|lib/test.dart': input
      };
      await testBuilder(builder, assets,
       rootPackage: 'source_gen_test');
    });
  });
}

var input = r'''
library source_gen_test;
import 'package:annotations/annotations.dart';

part 'test.g.dart';

@TestAnnot()
class Test {
  
}
''';

var annotations= r'''
library annotations;

class TestAnnot{
  const TestAnnot();
}
''';
```
TestAnnot file:
```
class TestAnnot{
  const TestAnnot();
}

```
Generator file:
```
class TestGeneratorAnnot extends GeneratorForAnnotation<TestAnnot> {
  const TestGeneratorAnnot();

  @override
  generateForAnnotatedElement(
      Element element, ConstantReader annotation, BuildStep buildStep) {
    var code = '''
    It worked!
    ''';
    return code;
  }
}
```
pubspec.yaml:
```
environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  annotations:
    path: ../annotations
  analyzer: ^0.34.0
  build: ^1.0.0
  logging: ^0.11.0
  source_gen: ^0.9.0
  meta: ^1.1.5

dev_dependencies:
  test: ^1.3.0
  build_runner: ^1.1.0
  build_test: ^0.10.3
  collection: ^1.14.10
  path: ^1.6.2
```
