### ISSUE TITLE
Uncaught Error: type arguments should not be null

### ISSUE THREAD

**Issue by lucasdidur** [dart-lang/build#2304]
```
Uncaught Error: type arguments should not be null: T => {
    class JsObjectWrapper extends core.Object {
      get jsObject() {
        return this[jsObject$];
      }
      set jsObject(value) {
        super.jsObject = value;
      }
    }
    (JsObjectWrapper.fromJsObject = function(jsObject) {
      this[jsObject$] = jsObject;
      ;
    }).prototype = JsObjectWrapper.prototype;
    dart.addTypeTests(JsObjectWrapper);
    JsObjectWrapper.prototype[_is_JsObjectWrapper_default] = true;
    const jsObject$ = Symbol("JsObjectWrapper.jsObject");
    dart.setFieldSignature(JsObjectWrapper, () => ({
      __proto__: dart.getFields(JsObjectWrapper.__proto__),
      jsObject: dart.finalFieldType(T)
    }));
    return JsObjectWrapper;
  }
    at Object.dart.throwInternalError (dart_sdk.js:3610)
    at Object.makeGenericType [as JsObjectWrapper$] (dart_sdk.js:3773)
    at top_level.dart:23
    at Object.execCb (require.js:1696)
    at Module.check (require.js:878)
    at Module.<anonymous> (require.js:1139)
    at require.js:134
    at require.js:1189
    at each (require.js:59)
    at Module.emit (require.js:1188)
    at Module.check (require.js:938)
    at Module.enable (require.js:1176)
    at Module.init (require.js:788)
    at callGetModule (require.js:1203)
    at Object.completeLoad (require.js:1590)
    at HTMLScriptElement.onScriptLoad (require.js:1717)
```

---

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`)
`Dart VM version: 2.3.1 (Unknown timestamp) on "linux_x64"`
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)

```yaml
  build:
    version: "1.1.4"
  build_config:
    version: "0.4.0"
  build_daemon:
    version: "1.0.0"
  build_modules:
    version: "2.3.0"
  build_resolvers:
    version: "1.0.5"
  build_runner:
    version: "1.5.1"
  build_runner_core:
    version: "3.0.6"
  build_test:
    version: "0.10.8"
  build_web_compilers:
    version: "2.1.0"
```
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
`webdev 2.0.7`
* Whether you are using Windows, MacOSX, or Linux (if applicable)
`Linux`
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
`Google Chrome`
* Any other packages or constraints we should know about
```yaml
environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  ng_bootstrap: ^1.1.1
  angular: ^5.3.0
  angular_components: ^0.13.0+1
  angular_forms: ^2.1.2
  angular_router: ^2.0.0-alpha+22
  rxdart: ^0.22.0
  firebase: ^5.0.3
  googleapis: ^0.53.0
  googleapis_auth: ^0.2.5+2
  service_worker: ^0.2.3
  sass: ^1.5.0
  markdown: ^2.0.2
  intl: ^0.15.8

dev_dependencies:
  sass_builder: ^2.0.0
  angular_test: ^2.2.0
  build_runner: ^1.5.1
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  test: ^1.6.3
```
