### ISSUE TITLE
Cannot reliably include generated class from cache

### ISSUE THREAD

**Issue by Antoniossss** [dart-lang/build#2311]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart VM version: 2.3.2 (Tue Jun 11 15:29:47 2019 +0200) on "windows_x64"
* build runner   version: "1.5.2"

I am creating a builder that generates class file that contains constant fields (generation works just fine)

* Windows

This is builder config:
```
builders:
  env|builder:
    import: "env/EnvBuilder.dart"
    builder_factories: ["builderFactory"]
    is_optional: false
    build_extensions:
      "$lib$": ["environment.g.dart"]
    auto_apply: root_package
    runs_before: ["build_test:test_bootstrap","build_modules:module_library","build_modules:dartdevc","build_web_compilers:ddc","build_modules:vm","build_modules:dart2js","build_web_compilers:entrypoint"]
    build_to: source
````
So the problem is, that if I generate my class into `soruce` using `build_to:source`,  following import works just fine

`import 'package:buildertest/environment.g.dart';`

however if i generate to cache (build_to:cache) which is what I want eventually as generated class is not part of codebase, build fails with following error:

```
[SEVERE] build_web_compilers:entrypoint on web/main.dart:
Unable to find modules for some sources, this is usually the result of either a
bad import, a missing dependency in a package (or possibly a dev_dependency
needs to move to a real dependency), or a build failure (if importing a
generated file).

Please check the following imports:

`import '../.dart_tool/build/generated/buildertest/lib/environment.g.dart';` from buildertest|web/main.dart at 4:1
```

So how to reliably import generated source file?

I ran some trial and error testing of such imports

In general this is how it goes
Compilation: `pub run_builder build`
Test execution: `dart web/main.dart`
IDE: IntellJ

destination | import | IDE| command result | build result
-------------|--------|-------------|--- | ----
source | import 'package:buildertest/environment.g.dart'; | file recognized | OK | OK
cache |  import 'package:buildertest/environment.g.dart'; | file not recognized | Error when reading 'lib/environment.g.dart': The system cannot find the file specified. | OK
source | import '../.dart_tool/build/generated/buildertest/lib/environment.g.dart'; | file recognized | runs fine | Invalid import error |
cache | import '../.dart_tool/build/generated/buildertest/lib/environment.g.dart'; | file recognized | runs fine | Invalid import error
