### ISSUE TITLE
Can't run script with build_to set to "cache". Works with "source" however.

### ISSUE THREAD

**Issue by Pacane** [dart-lang/build#2338]
* Dart SDK Version (`dart --version`) 
> Dart VM version: 2.4.0 (Wed Jun 19 11:53:45 2019 +0200) on "linux_x64"

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
```
  build:
    dependency: transitive
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.4"
  build_config:
    dependency: transitive
    description:
      name: build_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.0"
  build_daemon:
    dependency: transitive
    description:
      name: build_daemon
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  build_resolvers:
    dependency: transitive
    description:
      name: build_resolvers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.1"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.6"
  build_test:
    dependency: "direct dev"
    description:
      name: build_test
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.8"
  built_collection:
    dependency: transitive
    description:
      name: built_collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.2"
  built_value:
    dependency: transitive
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.6.0"
```

  * _If you are not sure, try checking your `pubspec.lock` file._
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
> inject.dart

* Whether you are using Windows, MacOSX, or Linux (if applicable)
> Linux

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
> Server side

* Any other packages or constraints we should know about
> I've [forked inject.dart](https://github.com/BitBoxUSA/inject.dart/tree/updated_analyzer) to fix the warnings, update the analyzer

I've been trying to use inject.dart and one thing that has been a pain so far is the need to override the build.yaml file to set the build_to switch to `source` instead of `cache`.

The things I'm trying to do are:

- Generate to .dart_tool [works, the files are there with `build_to` set to `cache`]
- Run the script through IntelliJ and debug it [It doesn't run, even with CLI `dart bin/main.dart`, I get an error saying the generated files can't be found (See error below). The IntelliJ editor can however jump to the generated files.]
- Build snapshot of my main. [Can't build it from CLI because of the same error]

Error message I get when trying to run/build snapshots:

```
/opt/dart-sdk/bin/dart --enable-asserts --pause_isolates_on_start --enable-vm-service:34301 /home/joel/code/bitbox/DartCode/rest_client_link/bin/run.dart -b http://localhost:9090/conn
Observatory listening on http://127.0.0.1:34301/XMfyWxkBS-M=/

lib/app_injector.dart:6:8: Error: Error when reading 'lib/app_injector.inject.dart': No such file or directory
import 'app_injector.inject.dart' as g;
       ^
lib/app_injector.dart:15:9: Error: Getter not found: 'AppInjector$Injector'.
      g.AppInjector$Injector.create(productionModule);
        ^^^^^^^^^^^^^^^^^^^^
```

If I set the `build_to` flag to `source`, everything works fine.

Here's my `app_injector.dart` file just for reference.

```dart
library rest_client;

import 'package:inject/inject.dart';
import 'package:rest_client_link/src/rest_client.dart';

import 'app_injector.inject.dart' as g;
import 'src/production_module.dart';

@Injector(const [ProductionModule])
abstract class AppInjector {
  @provide
  RestClient get restClient;

  static Future<AppInjector> create(ProductionModule productionModule) =>
      g.AppInjector$Injector.create(productionModule);
}
```

my module

```dart
import 'package:http/http.dart' as http;
import 'package:inject/inject.dart';

/// Provides various objects to create a drip coffee brewer.
@module
class ProductionModule {
  @provide
  http.Client provideHttpClient() => http.Client();
}
```

and here's my main

```dart
import "dart:async";

import 'package:rest_client_link/src/production_module.dart';
import 'package:rest_client_link/app_injector.dart';


Future<void> main(List<String> args) async {
  final container = await AppInjector.create(ProductionModule());

  // Do something with the container.
}
```

Note that if the switch is set to `cache` I can run the app with `pub run build_runner run bin/main.dart` although I can't easily debug it with (gotta use the observatory), and I cannot build snapshots at all.
