### ISSUE TITLE
Building with DDC after building with dart2js with --no-minify option incorrectly uses the cached dart2js build

### ISSUE THREAD

**Issue by smaifullerton-wk** [dart-lang/build#2373]
Hi there! I'm using Dart 2.4 and build_runner 1.6.2. Both build_web_compilers 2.1.4 and 1.2.2 reproduces.

If I specify the `--no-minify` dart2js option in a build.yaml like so:

```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          compiler: dart2js
          dart2js_args:
            - --no-minify
```

And then run `pub run build_runner build -r` -- life is good, the code compiles using unminified dart2js as expected.

If I then make no code changes, and run `pub run build_runner build`

The cached dart2js build from the first command is the build output; it doesn't rebuild using DDC the second time. I determined this via stack traces when running tests this same way, as well as the 1 second build time (versus around 9 for a DDC build):

```
➜  json_schema git:(master) ✗ pub run build_runner build
[INFO] Generating build script completed, took 337ms
[INFO] Reading cached asset graph completed, took 327ms
[INFO] Checking for updates since last build completed, took 818ms
[INFO] Running build completed, took 920ms
[INFO] Caching finalized dependency graph completed, took 161ms
[INFO] Succeeded after 1.1s with 8 outputs (2203 actions)
```

I saw this behavior reproduce in multiple repos. [Here is a small open source one to test with](https://github.com/Workiva/json_schema). It doesn't have a build.yaml committed to it, but if you add one with what I specified above, it will reproduce. 

Thank you!
