### ISSUE TITLE
Source maps do not work with dart2js

### ISSUE THREAD

**Issue by smaifullerton-wk** [dart-lang/build#2377]
Dart 2.4 and BWC 2.1.4.

I'm trying to get sourcemaps when running tests with dart2js. I've tried setting this in my build.yaml:

```yaml
      build_web_compilers|entrypoint:
        generate_for:
          include:
            - "my_entrypoint.dart"
        options:
          compiler: dart2js
          dart2js_args:
            - --no-minify
```

and not using the `--release` flag, [per this documentation](https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-debug-my-release-mode-web-app-dart2js).

My build compiles unminified with dart2js but stack traces don't have sourcemaps, and there isn't a .map file digging around .dart_tool.

I've also tried this based on the guidance in #1779  - same result:

```yaml
global_options:
  build_web_compilers|dart_source_cleanup:
    release_options:
      enabled: false
  build_web_compilers|dart2js_archive_extractor:
    release_options:
      filter_outputs: false
```

I originally asked about this in Gitter. Here's the resulting conversation:

Nate Bosch @natebosch 14:55
dart2js_archive_extractor is where I'd focus my digging I think, if there isn't a .map file inside .dart_tool. @jakemac53 - Should dart2js output that always?

Jacob MacDonald @jakemac53 15:16
I think it does unless we tell it not to - but we might not be declaring the output or something?

Nate Bosch @natebosch 15:22
I should show up in the archive I think

Jacob MacDonald @jakemac53 15:22
Ya I believe it should - we should be able to declare it explicitly as well though

Nate Bosch @natebosch 15:23
@smaifullerton-wk - since you aren't running in --release mode you might try changing you release_options: under global_options: to just options:...
but I think in non-release filter_outputs should be false by default anyway

Jacob MacDonald @jakemac53 15:25
Ya from peeking at the code it seems like this should be working the way you have it set up
Ok so I can see the source map is loading because the dart sources in the chrome console are visible, but the stack trace doesn't seem to get mapped properly

Jacob MacDonald @jakemac53 15:44
oh interesting the expanded stack trace does get mapped properly.. I think the one it shows by default is coming from the custom formatter and that is what doesn't seem to work properly
My suggestion for now would be to set the debugger in chrome to pause on exceptions, that seems to work properly and jump you to the right place

Smai Fullerton @smaifullerton-wk 15:53
awesome, thanks for looking into that. I'm able to get it to work running tests using pause on exceptions with --pause-after-load. would you like me to file an issue?

Jacob MacDonald @jakemac53 15:55
sure
