### ISSUE TITLE
Debugging web tests does not generate *.dart.js files

### ISSUE THREAD

**Issue by e-belair** [dart-lang/build#2427]
Create a sample app from dart angular template in Webstorm
Then execute ` pub run build_runner serve test`

All files seem to be generated but not the app_test.dart.js

![image](https://user-images.githubusercontent.com/596562/64246111-7de18680-cf0c-11e9-9846-2ab89e6d8aec.png)

dart 2.4.1 on ubuntu 18.04
build_test 0.10.8
build_web_compilers 2.2.3

**Comment by jakemac53** [comment]
@e-belair you will have to explicitly enable this, by default we only compile the `.browser_test.dart` files.

You can add this in your build.yaml to override it:

```yaml
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
        - test/**_test.dart
        - web/**.dart
```
