### ISSUE TITLE
'WebSocketProtocolTransformer' is not a subtype of type 'StreamTransformer

### ISSUE THREAD

**Issue by nigeltiany** [dart-lang/build#2440]
* Dart SDK Version (`2.5.0`)
* What package(s) from this repo you are using (`build_runner 1.5.2`)
```yaml
name: Web App
description: A web app that uses AngularDart Components

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  angular: ^5.1.0
  angular_components: 0.13.0+1
  angular_router: 2.0.0-alpha+21
  bootstrap_sass: any
  grpc: ^2.1.2
  json_annotation: ^2.0.0
  firebase: ^5.0.3
  observable: 0.22.2
  protobuf: ^0.13.6
  uuid: 1.0.3

dev_dependencies:
  angular_test: ^2.1.0
  build_runner: ^1.5.2
  build_test: ^0.10.3
  build_web_compilers: ^2.1.1
  json_serializable: ^2.0.0
  sass_builder: ^2.1.2
  test: ^1.5.1
```
* Windows, MacOSX, or Linux (`Linux`)
* Chrome, Safari, Firefox, Edge (`Chrome`)
* Any other packages or constraints we should know about
Not really sure what could be causing this. Version solving between protobuf, grpc-dart, angular_components, and this package is not flexible. I am unable to incrementally update versions to really find out what is causing the issue.

```log
[INFO] Building new asset graph completed, took 2.2s
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms
[SEVERE] ERROR - 2019-09-12 02:01:00.997617
[SEVERE] Asynchronous error
[SEVERE] type '_WebSocketProtocolTransformer' is not a subtype of type 'StreamTransformer<Uint8List, dynamic>' of 'streamTransformer'
[SEVERE] dart:async                                                       Stream.transform
[SEVERE] package:web_socket_channel/src/copy/web_socket_impl.dart 728:28  new WebSocketImpl.fromSocket
[SEVERE] package:web_socket_channel/src/channel.dart 94:26                new WebSocketChannel
[SEVERE] package:shelf_web_socket/src/web_socket_handler.dart 77:25       WebSocketHandler.handle.<fn>

```
