### ISSUE TITLE
build_web_compilers - We're sorry, you've found a bug in our compiler.

### ISSUE THREAD

**Issue by normcf** [dart-lang/build#2455]
While developing, this suddenly began.  Restarting webdev does not seem to make a difference.
```
$ webdev  serve -v --log-requests --no-injected-client web 
[INFO] Connecting to the build daemon...
[INFO] Generating build script...
[INFO] Generating build script completed, took 801ms
[INFO] 
[INFO] Starting daemon...
[INFO]BuildDefinition: Initializing inputs
[INFO]BuildDefinition: Reading cached asset graph...
[INFO]BuildDefinition: Reading cached asset graph completed, took 782ms

[INFO]BuildDefinition: Checking for updates since last build...
[INFO]BuildDefinition: Checking for updates since last build completed, took 1.9s

[INFO] Initializing inputs
[INFO] Reading cached asset graph...
[INFO] Reading cached asset graph completed, took 782ms
[INFO] 
[INFO] Checking for updates since last build...
[INFO] Checking for updates since last build completed, took 1.9s
[INFO] 
[INFO] Setting up file watchers...
[INFO] Setting up file watchers completed, took 5ms
[INFO] 
[INFO] Registering build targets...
[INFO] Starting initial build...
[INFO] Starting resource servers...
[INFO] Serving `web` on http://127.0.0.1:8080

[INFO] About to build [web]...
[INFO]Build: Running build...
[INFO]Build: Running build completed, took 784ms

[INFO]Build: Caching finalized dependency graph...
[INFO]Build: Caching finalized dependency graph completed, took 503ms

[SEVERE]build_web_compilers:entrypoint on web/pusr/sheet.dart (cached): AssetNotFoundException: tact|web/pusr/sheet.ddc.js
#0      bootstrapDdc (package:build_web_compilers/src/dev_compiler_bootstrap.dart:122:34)
<asynchronous suspension>
#1      WebEntrypointBuilder.build (package:build_web_compilers/src/web_entrypoint_builder.dart:101:15)
<asynchronous suspension>
#2      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:45:21)
<asynchronous suspension>
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#5      Future.wait (dart:async/future.dart:393:26)
#6      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:51:36)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1500:12)
#11     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
#12     runBuilder (package:build/src/generate/run_builder.dart:51:9)
<asynchronous suspension>
#13     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:472:19)
#14     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
#15     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:470:23)
<asynchronous suspension>
#16     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#17     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:429:22)
#18     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#19     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:425:17)
#20     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:373:38)
#21     MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
#22     Future.wait (dart:async/future.dart:393:26)
#23     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:372:36)
#24     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#25     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:370:40)
#26     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:20)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#33     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#34     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#35     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#36     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#37     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#38     _rootRunUnary (dart:async/zone.dart:1132:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#41     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#42     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#43     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#44     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#45     _rootRunUnary (dart:async/zone.dart:1132:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#49     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#50     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#51     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#52     _rootRun (dart:async/zone.dart:1124:13)
#53     _CustomZone.run (dart:async/zone.dart:1021:19)
#54     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#55     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#56     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#57     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#58     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


[SEVERE]build_web_compilers:ddc on web/usr/sheet.ddc.module (cached): Error compiling dartdevc module:tact|web/usr/sheet.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/usr/lib/dart/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o web/usr/sheet.ddc.js --source-map --summary=packages/quiver/core.ddc.dill=packages/quiver/core --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/convert/convert.ddc.dill=packages/convert/convert --summary=packages/crypto/crypto.ddc.dill=packages/crypto/crypto --summary=packages/archive/src/archive.ddc.dill=packages/archive/src/archive --summary=packages/archive/archive.ddc.dill=packages/archive/archive --summary=packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols --summary=packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols --summary=packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data --summary=packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules --summary=packages/intl/intl.ddc.dill=packages/intl/intl --summary=web/super/resizable.ddc.dill=web/super/resizable --summary=web/include/debug.ddc.dill=web/include/debug --summary=web/include/tactmainmenu.ddc.dill=web/include/tactmainmenu --summary=packages/intl/intl_browser.ddc.dill=packages/intl/intl_browser --summary=web/not/lib.ddc.dill=web/not/lib --summary=web/not/not.ddc.dill=web/not/not --summary=web/usr/lib.ddc.dill=web/usr/lib --summary=web/trk/lib.ddc.dill=web/trk/lib --summary=web/include/sheet.ddc.dill=web/include/sheet --summary=web/pusr/lib.ddc.dill=web/pusr/lib --packages=file:///tmp/kernel_builder_IHMASP/.packages --module-name=web/usr/sheet --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///usr/lib/dart/lib/libraries.json web/usr/sheet.dart
    dart --version: 2.5.0 (Unknown timestamp) on "linux_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2207:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:393:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:271:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:259:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///tmp/tmpKEDbZK/dart-2.5.0/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///tmp/tmpKEDbZK/dart-2.5.0/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///tmp/tmpKEDbZK/dart-2.5.0/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




[SEVERE]build_web_compilers:entrypoint on web/usr/sheet.dart (cached): AssetNotFoundException: tact|web/usr/sheet.ddc.js
#0      bootstrapDdc (package:build_web_compilers/src/dev_compiler_bootstrap.dart:122:34)
<asynchronous suspension>
#1      WebEntrypointBuilder.build (package:build_web_compilers/src/web_entrypoint_builder.dart:101:15)
<asynchronous suspension>
#2      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:45:21)
<asynchronous suspension>
#3      MappedListIterable.elementAt (dart:_internal/iterable.dart:415:29)
#4      ListIterator.moveNext (dart:_internal/iterable.dart:344:26)
#5      Future.wait (dart:async/future.dart:393:26)
#6      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:51:36)
#7      _rootRun (dart:async/zone.dart:1124:13)
#8      _CustomZone.run (dart:async/zone.dart:1021:19)
#9      _runZoned (dart:async/zone.dart:1516:10)
#10     runZoned (dart:async/zone.dart:1500:12)
#11     scopeLogAsync (package:build/src/builder/logging.dart:22:3)
#12     runBuilder (package:build/src/generate/run_builder.dart:51:9)
<asynchronous suspension>
#13     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:472:19)
#14     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:300:15)
#15     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:470:23)
<asynchronous suspension>
#16     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#17     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:429:22)
#18     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#19     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:425:17)
#20     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:373:38)
#21     MappedIterator.moveNext (dart:_internal/iterable.dart:393:18)
#22     Future.wait (dart:async/future.dart:393:26)
#23     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:372:36)
#24     _AsyncAwaitCompleter.start (dart:async-patch/async_patch.dart:43:6)
#25     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:370:40)
#26     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:20)
#27     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#28     _rootRunUnary (dart:async/zone.dart:1132:38)
#29     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#30     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#31     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#32     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#33     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#34     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:30:15)
#35     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:288:13)
#36     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#37     _asyncThenWrapperHelper.<anonymous closure> (dart:async-patch/async_patch.dart:71:64)
#38     _rootRunUnary (dart:async/zone.dart:1132:38)
#39     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#40     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#41     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#42     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#43     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#44     Future.wait.<anonymous closure> (dart:async/future.dart:400:22)
#45     _rootRunUnary (dart:async/zone.dart:1132:38)
#46     _CustomZone.runUnary (dart:async/zone.dart:1029:19)
#47     _FutureListener.handleValue (dart:async/future_impl.dart:137:18)
#48     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:678:45)
#49     Future._propagateToListeners (dart:async/future_impl.dart:707:32)
#50     Future._completeWithValue (dart:async/future_impl.dart:522:5)
#51     Future._asyncComplete.<anonymous closure> (dart:async/future_impl.dart:552:7)
#52     _rootRun (dart:async/zone.dart:1124:13)
#53     _CustomZone.run (dart:async/zone.dart:1021:19)
#54     _CustomZone.runGuarded (dart:async/zone.dart:923:7)
#55     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:963:23)
#56     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#57     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#58     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:116:13)
#59     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:173:5)


[SEVERE]build_web_compilers:ddc on web/pusr/sheet.ddc.module (cached): Error compiling dartdevc module:tact|web/pusr/sheet.ddc.js

We're sorry, you've found a bug in our compiler.
You can report this bug at:
    https://github.com/dart-lang/sdk/issues/labels/web-dev-compiler
Please include the information below in your report, along with
any other information that may help us track it down. Thanks!
-------------------- %< --------------------
    dartdevc -k arguments: --dart-sdk-summary=/usr/lib/dart/lib/_internal/ddc_sdk.dill --modules=amd --no-summarize -o web/pusr/sheet.ddc.js --source-map --summary=packages/intl/date_symbols.ddc.dill=packages/intl/date_symbols --summary=packages/intl/number_symbols.ddc.dill=packages/intl/number_symbols --summary=packages/intl/number_symbols_data.ddc.dill=packages/intl/number_symbols_data --summary=packages/intl/src/plural_rules.ddc.dill=packages/intl/src/plural_rules --summary=packages/intl/intl.ddc.dill=packages/intl/intl --summary=web/include/debug.ddc.dill=web/include/debug --summary=packages/quiver/core.ddc.dill=packages/quiver/core --summary=packages/collection/src/utils.ddc.dill=packages/collection/src/utils --summary=packages/collection/src/algorithms.ddc.dill=packages/collection/src/algorithms --summary=packages/collection/src/iterable_zip.ddc.dill=packages/collection/src/iterable_zip --summary=packages/collection/src/comparators.ddc.dill=packages/collection/src/comparators --summary=packages/collection/src/priority_queue.ddc.dill=packages/collection/src/priority_queue --summary=packages/collection/src/canonicalized_map.ddc.dill=packages/collection/src/canonicalized_map --summary=packages/collection/collection.ddc.dill=packages/collection/collection --summary=packages/typed_data/typed_buffers.ddc.dill=packages/typed_data/typed_buffers --summary=packages/typed_data/typed_data.ddc.dill=packages/typed_data/typed_data --summary=packages/charcode/ascii.ddc.dill=packages/charcode/ascii --summary=packages/convert/convert.ddc.dill=packages/convert/convert --summary=packages/crypto/crypto.ddc.dill=packages/crypto/crypto --summary=packages/archive/src/archive.ddc.dill=packages/archive/src/archive --summary=packages/archive/archive.ddc.dill=packages/archive/archive --summary=web/super/resizable.ddc.dill=web/super/resizable --summary=web/include/tactmainmenu.ddc.dill=web/include/tactmainmenu --summary=web/include/sheet.ddc.dill=web/include/sheet --summary=web/pusr/lib.ddc.dill=web/pusr/lib --packages=file:///tmp/kernel_builder_EUEDFY/.packages --module-name=web/pusr/sheet --multi-root-scheme=org-dartlang-app --multi-root=. --track-widget-creation --inline-source-map --libraries-file=file:///usr/lib/dart/lib/libraries.json web/pusr/sheet.dart
    dart --version: 2.5.0 (Unknown timestamp) on "linux_x64"

RangeError (index): Index out of range: no indices are valid: 0
#0      Uint8List.[] (dart:typed_data-patch/typed_data_patch.dart:2207:7)
#1      BinaryBuilder.readByte (package:kernel/binary/ast_from_binary.dart:104:27)
#2      BinaryBuilder.readUint32 (package:kernel/binary/ast_from_binary.dart:124:13)
#3      BinaryBuilder.readComponent (package:kernel/binary/ast_from_binary.dart:444:17)
#4      ProcessedOptions.loadComponent (package:front_end/src/base/processed_options.dart:393:10)
#5      initializeIncrementalCompiler (package:front_end/src/api_unstable/ddc.dart:271:14)
<asynchronous suspension>
#6      _compile (package:dev_compiler/src/kernel/command.dart:259:27)
<asynchronous suspension>
#7      compile (package:dev_compiler/src/kernel/command.dart:42:18)
<asynchronous suspension>
#8      compile (package:dev_compiler/src/compiler/shared_command.dart:394:12)
#9      _CompilerWorker.performRequest.<anonymous closure> (file:///tmp/tmpKEDbZK/dart-2.5.0/dart/pkg/dev_compiler/bin/dartdevc.dart:64:13)
#10     _rootRun (dart:async/zone.dart:1124:13)
#11     _CustomZone.run (dart:async/zone.dart:1021:19)
#12     _runZoned (dart:async/zone.dart:1516:10)
#13     runZoned (dart:async/zone.dart:1463:12)
#14     _CompilerWorker.performRequest (file:///tmp/tmpKEDbZK/dart-2.5.0/dart/pkg/dev_compiler/bin/dartdevc.dart:62:24)
<asynchronous suspension>
#15     AsyncWorkerLoop.run.<anonymous closure> (package:bazel_worker/src/worker/async_worker_loop.dart:33:41)
#16     _rootRun (dart:async/zone.dart:1124:13)
#17     _CustomZone.run (dart:async/zone.dart:1021:19)
#18     _runZoned (dart:async/zone.dart:1516:10)
#19     runZoned (dart:async/zone.dart:1463:12)
#20     AsyncWorkerLoop.run (package:bazel_worker/src/worker/async_worker_loop.dart:33:26)
<asynchronous suspension>
#21     main (file:///tmp/tmpKEDbZK/dart-2.5.0/dart/pkg/dev_compiler/bin/dartdevc.dart:28:57)
<asynchronous suspension>
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:301:32)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:172:12)




[SEVERE]Build: Failed after 1.3s
[INFO] ----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by natebosch** [comment]
Can you post your pubspec.lock file? What version of the SDK are you using?

**Comment by normcf** [comment]
```
john@transition:~/workspace/tact$ dart --version
Dart VM version: 2.5.0 (Unknown timestamp) on "linux_x64"
john@transition:~/workspace/tact$ cat pubspec.lock
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  analyzer:
    dependency: "direct main"
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.35.4"
  archive:
    dependency: "direct main"
    description:
      name: archive
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.10"
  args:
    dependency: "direct main"
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.2"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.3.0"
  bazel_worker:
    dependency: transitive
    description:
      name: bazel_worker
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.22"
  build:
    dependency: transitive
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.6"
  build_config:
    dependency: transitive
    description:
      name: build_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.1+1"
  build_daemon:
    dependency: transitive
    description:
      name: build_daemon
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  build_modules:
    dependency: transitive
    description:
      name: build_modules
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.5.0"
  build_resolvers:
    dependency: transitive
    description:
      name: build_resolvers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.7"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.9"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.1"
  build_web_compilers:
    dependency: "direct dev"
    description:
      name: build_web_compilers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.3"
  built_collection:
    dependency: transitive
    description:
      name: built_collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.2.2"
  built_value:
    dependency: transitive
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.7.1"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  checked_yaml:
    dependency: transitive
    description:
      name: checked_yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  code_builder:
    dependency: transitive
    description:
      name: code_builder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.14.12"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
  csv:
    dependency: "direct main"
    description:
      name: csv
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.0.3"
  dart_style:
    dependency: transitive
    description:
      name: dart_style
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.3"
  fixnum:
    dependency: transitive
    description:
      name: fixnum
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.9"
  front_end:
    dependency: transitive
    description:
      name: front_end
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.14"
  glob:
    dependency: transitive
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.7"
  graphs:
    dependency: transitive
    description:
      name: graphs
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  http:
    dependency: transitive
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.0+2"
  http_multi_server:
    dependency: transitive
    description:
      name: http_multi_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.3"
  intl:
    dependency: "direct main"
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.16.0"
  io:
    dependency: transitive
    description:
      name: io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.3"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1+1"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.0"
  kernel:
    dependency: transitive
    description:
      name: kernel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.14"
  logging:
    dependency: transitive
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+2"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.5"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.7"
  mime:
    dependency: transitive
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.6+3"
  package_config:
    dependency: transitive
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  package_resolver:
    dependency: transitive
    description:
      name: package_resolver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.10"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.4"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0+1"
  pool:
    dependency: transitive
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  protobuf:
    dependency: transitive
    description:
      name: protobuf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.1"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.2"
  pubspec_parse:
    dependency: transitive
    description:
      name: pubspec_parse
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.5"
  quiver:
    dependency: "direct main"
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.5"
  scratch_space:
    dependency: transitive
    description:
      name: scratch_space
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.4"
  shelf:
    dependency: transitive
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.5"
  shelf_web_socket:
    dependency: transitive
    description:
      name: shelf_web_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.3"
  source_maps:
    dependency: transitive
    description:
      name: source_maps
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.8"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.5"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.3"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.19"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  timing:
    dependency: transitive
    description:
      name: timing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1+2"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.6"
  watcher:
    dependency: transitive
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+12"
  web_socket_channel:
    dependency: transitive
    description:
      name: web_socket_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.15"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.16"
sdks:
  dart: ">=2.4.0 <3.0.0"
john@transition:~/workspace/tact$
```
