### ISSUE TITLE
NoSuchMethodError: The getter 'futureDynamicType' was called on null. Receiver: null Tried calling: futureDynamicType

### ISSUE THREAD

**Issue by pushpankq** [dart-lang/build#2502]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`)
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  * _If you are not sure, try checking your `pubspec.lock` file._
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* Any other packages or constraints we should know about

Missing some or all of the above might make the issue take longer or be impossible to act on.

----

For general questions consider using Stack Overflow instead:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/build

-----

**Comment by jakemac53** [comment]
You need to upgrade your dependencies to fix this, specifically the `build_resolvers` package needs to be updated to the latest. This is a transitive dependency of build_runner, but you might need to update your `build_runner` version in order to get the latest.

**Comment by u007** [comment]
hitting the same error trying to build bean of jaguar_orm_gen:
```
 pub run build_runner build
[INFO] Generating build script completed, took 406ms


You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


NoSuchMethodError: The getter 'futureDynamicType' was called on null.
Receiver: null
Tried calling: futureDynamicType
dart:core                                                       Object.noSuchMethod
package:analyzer/src/dart/element/element.dart 5853:40          LibraryElementImpl.createLoadLibraryFunctionForLibrary
package:analyzer/src/dart/element/element.dart 5703:9           LibraryElementImpl.createLoadLibraryFunction
package:analyzer/src/summary/resynthesize.dart 339:24           SummaryResynthesizer.getLibraryElement.<fn>
dart:collection                                                 _LinkedHashMapMixin.putIfAbsent
package:analyzer/src/summary/resynthesize.dart 327:36           SummaryResynthesizer.getLibraryElement
package:analyzer/src/summary/resynthesize.dart 390:20           SummaryResynthesizer._buildTypeProvider
package:analyzer/src/summary/resynthesize.dart 178:5            new SummaryResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 346:9   new StoreBasedSummaryResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 322:26  ResynthesizerResultProvider.createResynthesizer
package:analyzer/src/summary/package_bundle_reader.dart 80:5    new InputPackagesResultProvider
package:analyzer/src/dart/sdk/sdk.dart 96:19                    AbstractDartSdk.context
package:analyzer/src/context/context.dart 1884:46               PartitionManager.forSdk
package:analyzer/src/context/context.dart 681:50                AnalysisContextImpl.createCacheFromSourceFactory.createCache
package:analyzer/src/context/context.dart 686:38                AnalysisContextImpl.createCacheFromSourceFactory
package:analyzer/src/context/context.dart 413:14                AnalysisContextImpl.sourceFactory=
package:build_resolvers/src/resolver.dart 95:14                 new AnalyzerResolver
package:build_resolvers/src/resolver.dart 449:32                new AnalyzerResolvers
package:build_runner_core/src/generate/options.dart 136:19      BuildOptions.create
package:build_runner/src/generate/build.dart 90:36              build
package:build_runner/src/entrypoint/build.dart 28:24            BuildCommand.run
package:args/command_runner.dart 197:27                         CommandRunner.runCommand
package:args/command_runner.dart 112:25                         CommandRunner.run.<fn>
dart:async                                                      new Future.sync
package:args/command_runner.dart 112:14                         CommandRunner.run
package:build_runner/src/entrypoint/run.dart 23:31              run
.dart_tool/build/entrypoint/build.dart 18:22                    main

```

**Comment by natebosch** [comment]
@u007 - please upgrade your dependencies to resolve.

**Comment by u007** [comment]
already run the upgrade twice, here is my lock file
```
# Generated by pub
# See https://dart.dev/tools/pub/glossary#lockfile
packages:
  analyzer:
    dependency: transitive
    description:
      name: analyzer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.34.3"
  angel_auth:
    dependency: transitive
    description:
      name: angel_auth
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.5+1"
  angel_client:
    dependency: transitive
    description:
      name: angel_client
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  angel_container:
    dependency: transitive
    description:
      name: angel_container
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  angel_framework:
    dependency: "direct main"
    description:
      name: angel_framework
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4+1"
  angel_hot:
    dependency: "direct main"
    description:
      name: angel_hot
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.6"
  angel_http_exception:
    dependency: transitive
    description:
      name: angel_http_exception
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  angel_migration:
    dependency: "direct main"
    description:
      name: angel_migration
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  angel_model:
    dependency: transitive
    description:
      name: angel_model
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  angel_mongo:
    dependency: "direct main"
    description:
      name: angel_mongo
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  angel_orm:
    dependency: "direct main"
    description:
      name: angel_orm
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2"
  angel_route:
    dependency: transitive
    description:
      name: angel_route
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.0.6"
  angel_serialize:
    dependency: "direct main"
    description:
      name: angel_serialize
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.3+3"
  angel_static:
    dependency: "direct main"
    description:
      name: angel_static
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3+2"
  angel_websocket:
    dependency: transitive
    description:
      name: angel_websocket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.3"
  args:
    dependency: transitive
    description:
      name: args
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.2"
  async:
    dependency: transitive
    description:
      name: async
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.0"
  bson:
    dependency: transitive
    description:
      name: bson
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  build:
    dependency: transitive
    description:
      name: build
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  build_config:
    dependency: transitive
    description:
      name: build_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.2"
  build_daemon:
    dependency: transitive
    description:
      name: build_daemon
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.3"
  build_resolvers:
    dependency: transitive
    description:
      name: build_resolvers
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.3"
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.3"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.1"
  built_collection:
    dependency: transitive
    description:
      name: built_collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "4.3.0"
  built_value:
    dependency: transitive
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "6.7.1"
  charcode:
    dependency: transitive
    description:
      name: charcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.2"
  checked_yaml:
    dependency: transitive
    description:
      name: checked_yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  code_buffer:
    dependency: transitive
    description:
      name: code_buffer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1"
  code_builder:
    dependency: transitive
    description:
      name: code_builder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.2.0"
  collection:
    dependency: transitive
    description:
      name: collection
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.14.12"
  combinator:
    dependency: transitive
    description:
      name: combinator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  convert:
    dependency: transitive
    description:
      name: convert
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.1"
  crypto:
    dependency: transitive
    description:
      name: crypto
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.3"
  csslib:
    dependency: transitive
    description:
      name: csslib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.16.1"
  dart2_constant:
    dependency: transitive
    description:
      name: dart2_constant
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2+dart2"
  dart_style:
    dependency: transitive
    description:
      name: dart_style
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.3"
  dotenv:
    dependency: "direct main"
    description:
      name: dotenv
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  file:
    dependency: transitive
    description:
      name: file
      url: "https://pub.dartlang.org"
    source: hosted
    version: "5.1.0"
  fixnum:
    dependency: transitive
    description:
      name: fixnum
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.10.11"
  front_end:
    dependency: transitive
    description:
      name: front_end
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.9+1"
  glob:
    dependency: transitive
    description:
      name: glob
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.2.0"
  graphs:
    dependency: transitive
    description:
      name: graphs
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0"
  html:
    dependency: transitive
    description:
      name: html
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.14.0+3"
  html_builder:
    dependency: transitive
    description:
      name: html_builder
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  http:
    dependency: transitive
    description:
      name: http
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.0+2"
  http2:
    dependency: transitive
    description:
      name: http2
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.0"
  http_multi_server:
    dependency: transitive
    description:
      name: http_multi_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.0"
  http_parser:
    dependency: transitive
    description:
      name: http_parser
      url: "https://pub.dartlang.org"
    source: hosted
    version: "3.1.3"
  http_server:
    dependency: transitive
    description:
      name: http_server
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.8+3"
  intl:
    dependency: transitive
    description:
      name: intl
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.15.8"
  io:
    dependency: transitive
    description:
      name: io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.3"
  jaguar_orm:
    dependency: transitive
    description:
      name: jaguar_orm
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.7"
  jaguar_orm_gen:
    dependency: "direct dev"
    description:
      name: jaguar_orm_gen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.29"
  jaguar_query:
    dependency: transitive
    description:
      name: jaguar_query
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.9"
  jaguar_query_sqljocky:
    dependency: "direct main"
    description:
      name: jaguar_query_sqljocky
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.4"
  js:
    dependency: transitive
    description:
      name: js
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.1+1"
  json_annotation:
    dependency: transitive
    description:
      name: json_annotation
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.4.0"
  json_god:
    dependency: transitive
    description:
      name: json_god
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0-beta+3"
  kernel:
    dependency: transitive
    description:
      name: kernel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.9+1"
  logger:
    dependency: "direct main"
    description:
      name: logger
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.6.0"
  logging:
    dependency: transitive
    description:
      name: logging
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.11.3+2"
  matcher:
    dependency: transitive
    description:
      name: matcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.12.6"
  merge_map:
    dependency: transitive
    description:
      name: merge_map
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.2"
  meta:
    dependency: transitive
    description:
      name: meta
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.8"
  mime:
    dependency: transitive
    description:
      name: mime
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.6+3"
  mock_request:
    dependency: transitive
    description:
      name: mock_request
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.6"
  mongo_dart:
    dependency: transitive
    description:
      name: mongo_dart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.0"
  mongo_dart_query:
    dependency: transitive
    description:
      name: mongo_dart_query
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.4.1"
  more:
    dependency: transitive
    description:
      name: more
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.18.2"
  mysql1:
    dependency: "direct main"
    description:
      name: mysql1
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.17.0+1"
  node_interop:
    dependency: transitive
    description:
      name: node_interop
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  node_io:
    dependency: transitive
    description:
      name: node_io
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.1+2"
  package_config:
    dependency: transitive
    description:
      name: package_config
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  package_resolver:
    dependency: transitive
    description:
      name: package_resolver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.10"
  path:
    dependency: transitive
    description:
      name: path
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.6.4"
  pedantic:
    dependency: transitive
    description:
      name: pedantic
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.8.0+1"
  plugin:
    dependency: transitive
    description:
      name: plugin
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.0+3"
  pool:
    dependency: transitive
    description:
      name: pool
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.0"
  pub_semver:
    dependency: transitive
    description:
      name: pub_semver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.4.2"
  pubspec_parse:
    dependency: transitive
    description:
      name: pubspec_parse
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.5"
  quiver:
    dependency: transitive
    description:
      name: quiver
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.1.2+1"
  quiver_hashcode:
    dependency: transitive
    description:
      name: quiver_hashcode
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  range_header:
    dependency: transitive
    description:
      name: range_header
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.2+2"
  shelf:
    dependency: transitive
    description:
      name: shelf
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.7.5"
  shelf_web_socket:
    dependency: transitive
    description:
      name: shelf_web_socket
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.2.3"
  source_gen:
    dependency: transitive
    description:
      name: source_gen
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.4+1"
  source_span:
    dependency: transitive
    description:
      name: source_span
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.5"
  sqljocky5:
    dependency: transitive
    description:
      name: sqljocky5
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  stack_trace:
    dependency: transitive
    description:
      name: stack_trace
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.9.3"
  stream_channel:
    dependency: transitive
    description:
      name: stream_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.0"
  stream_transform:
    dependency: transitive
    description:
      name: stream_transform
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.0.20"
  string_scanner:
    dependency: transitive
    description:
      name: string_scanner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.5"
  synchronized:
    dependency: transitive
    description:
      name: synchronized
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.5.3+2"
  term_glyph:
    dependency: transitive
    description:
      name: term_glyph
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  timing:
    dependency: transitive
    description:
      name: timing
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.1.1+2"
  tuple:
    dependency: transitive
    description:
      name: tuple
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.0.3"
  typed_buffer:
    dependency: transitive
    description:
      name: typed_buffer
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.1"
  typed_data:
    dependency: transitive
    description:
      name: typed_data
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.6"
  uuid:
    dependency: transitive
    description:
      name: uuid
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.0.4"
  vm_service_lib:
    dependency: transitive
    description:
      name: vm_service_lib
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.3.10+2"
  watcher:
    dependency: transitive
    description:
      name: watcher
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.9.7+12"
  web_socket_channel:
    dependency: transitive
    description:
      name: web_socket_channel
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.1.0"
  yaml:
    dependency: transitive
    description:
      name: yaml
      url: "https://pub.dartlang.org"
    source: hosted
    version: "2.2.0"
sdks:
  dart: ">=2.6.0 <3.0.0"

```
