### ISSUE TITLE
Build Runner generates .inject.dart and .inject.summary for every dart file.

### ISSUE THREAD

**Issue by erluxman** [dart-lang/build#2511]
So I was trying to use `inject-dart` and after setting up everything with DI, when I run the command, 

`flutter packages pub run build_runner build,`
it generates files for every dart file. 

Each dart gets a`  .inject.dart` (most of them are empty dart file without a single char) and a `.inject.summary.`

Looking at the extension seems like it's the issue of` 'inject-dart'` but as they are also using this library, there might be some way I can generate only the classes that need to be used.  Is there anything in build_runner itself to mitigate this issue?

**Comment by jakemac53** [comment]
You can use the `generate_for` option to limit what files it generates. In your `build.yaml` file (you may need to create one): 

```yaml
builders:
  # This name may have to be more specific but I would have to look at the package
  inject_dart:
    generate_for:
      - lib/some_file.dart
      - web/**/*_globs_too.dart
```

I could not actually find this package on pub so I can't tell you specifically the name of the builder - you can find it in the `builders` section of their build.yaml if its not documented in their readme.

**Comment by erluxman** [comment]
So this is my `inject_generator.build.yam`the file where I suppose the code you mentioned should be passed. 

```
# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  inject_generator:
    target: ":inject_generator"
    import: "package:inject_generator/inject_generator.dart"
    builder_factories:
      - "summarizeBuilder"
      - "generateBuilder"
    build_extensions:
      ".dart":
        - ".inject.summary"
        - ".inject.dart"
    auto_apply: dependents
    build_to: source

```

Couldn't figure out where to put the code you mentioned.
