### ISSUE TITLE
generate_for does not prevent builder conflicts

### ISSUE THREAD

**Issue by lexaknyazev** [dart-lang/build#2529]
Some time ago, it was possible to have two similar builders that work on different sources in the same project. For instance:

**build.yaml**
```yaml
targets:
  $default:
    sources:
      - "node/**"
      - "web/**"
    builders:
      build_node_compilers|entrypoint:
        generate_for:
          - node/**.dart
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
```

---

Such configuration does not work on the latest package versions:

**web/main.dart** and **node/main.dart**:
```dart
void main() {
  print('Hello world!');
}
```
**pubspec.yaml**
```yaml
dev_dependencies:
  build_runner: '^1.7.2'
  build_web_compilers: '^2.7.0'
  build_node_compilers: '^0.2.3' 
```

```
> dart --version
Dart VM version: 2.6.0-dev.8.2 (Thu Oct 24 09:35:58 2019 +0200) on "windows_x64"

> pub run build_runner build -v --output web:build\web --release
[INFO] Generating build script completed, took 298ms
[INFO] Creating build script snapshot... completed, took 11.3s
[SEVERE] build_web_compilers:ddc_modules:

The platform `ddc`, has already been registered.
package:build_modules/src/platform.dart 41:7                            DartPlatform.register
package:build_web_compilers/src/platforms.dart 7:34                     ddcPlatform
package:build_web_compilers/src/platforms.dart 7:7                      ddcPlatform
package:build_web_compilers/builders.dart 21:34                         ddcMetaModuleBuilder
package:build_runner_core/src/package_graph/apply_builders.dart 181:47  new BuilderApplication.forBuilder.<fn>.<fn>.<fn>
dart:async                                                              runZoned
package:build_runner_core/src/package_graph/apply_builders.dart 393:10  _scopeLogSync
package:build_runner_core/src/package_graph/apply_builders.dart 181:13  new BuilderApplication.forBuilder.<fn>.<fn>
package:build_runner_core/src/package_graph/apply_builders.dart 349:27  _createBuildPhasesForBuilderInCycle.<fn>.<fn>
dart:core                                                               Iterable.toList
package:build_runner_core/src/package_graph/apply_builders.dart 296:8   createBuildPhases
package:build_runner_core/src/generate/build_impl.dart 111:29           BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 33:42          BuildRunner.create
package:build_runner                                                    BuildCommand.run
package:args/command_runner.dart 197:27                                 CommandRunner.runCommand
package:args/command_runner.dart 112:25                                 CommandRunner.run.<fn>
dart:async                                                              new Future.sync
package:args/command_runner.dart 112:14                                 CommandRunner.run
package:build_runner                                                    run
.dart_tool\build\entrypoint\build.dart 142:22                           main

[SEVERE] build_web_compilers:ddc_modules:
Failed to instantiate builder for args with configuration:
{}
```

The error suggests that different builders cannot register the same platform names. Changing [platforms](https://github.com/pulyaevskiy/node-interop/blob/305dbe4fd73694df25d2f9266d1f3c51922b0aca/build_node_compilers/lib/src/platforms.dart) in `build_node_compilers` to `ddc-node` and `dart2js-node` gives another error:

```
[INFO] Generating build script completed, took 304ms
[WARNING] Deleted previous snapshot due to missing asset graph.
[INFO] Creating build script snapshot... completed, took 11.7s
[INFO] BuildDefinition:Initializing inputs
[INFO] BuildDefinition:Building new asset graph...
[SEVERE] BuildDefinition:
Conflicting outputs
Both build_node_compilers:ddc and build_web_compilers:ddc may output package:args/args.ddc.dill. Potential outputs must be unique across all builders. See https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs
package:build_runner_core/src/asset_graph/graph.dart 492:11          AssetGraph._addGeneratedOutputs
package:build_runner_core/src/asset_graph/graph.dart 437:21          AssetGraph._addInBuildPhaseOutputs
package:build_runner_core/src/asset_graph/graph.dart 394:26          AssetGraph._addOutputsForSources
package:build_runner_core/src/asset_graph/graph.dart 56:9            AssetGraph.build
package:build_runner_core/src/generate/build_definition.dart 237:41  _Loader.prepareWorkspace.<fn>
package:build_runner_core/src/logging/logging.dart 25:30             logTimedAsync
package:build_runner_core/src/generate/build_definition.dart 235:13  _Loader.prepareWorkspace
package:build_runner_core/src/generate/build_definition.dart 67:50   BuildDefinition.prepareWorkspace
package:build_runner_core/src/generate/build_impl.dart 116:49        BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 33:42       BuildRunner.create
package:build_runner                                                 BuildCommand.run
package:args/command_runner.dart 197:27                              CommandRunner.runCommand
package:args/command_runner.dart 112:25                              CommandRunner.run.<fn>
dart:async                                                           new Future.sync
package:args/command_runner.dart 112:14                              CommandRunner.run
package:build_runner                                                 run
.dart_tool\build\entrypoint\build.dart 142:22                        main
```

This error is especially strange because none of app sources use `package:args` and moreover the FAQ says:
> Add a `generate_for` configuration for one or both Builders so they do not both operate on the same primary input.

**Comment by natebosch** [comment]
You are adding a `generate_for` for the `:entrypoint` builders, but these are not the builders with a conflict. The builders with a conflict are the `:ddc` builders.

**Comment by lexaknyazev** [comment]
OK. Now I'm even more confused.
- The same config worked fine with older versions of `build*` packages (about 2-3 months ago).
- `build_runner` is called with `--release`. Why are `:ddc` builders even involved?

**Comment by jakemac53** [comment]
Changing the platform name is the correct thing here. There are currently usually two builders under the `:ddc` name - a kernel builder and a ddc builder. It looks like maybe you only changed the `Platform` for ddc but not kernel.

> * `build_runner` is called with `--release`. Why are `:ddc` builders even involved?

They still exist in the asset graph - that is completely static and doesn't change based on `--release`. All that `--release` does is give a hook for builders to change their default options in release mode.

**Comment by lexaknyazev** [comment]
Renaming `ddcKernelExtension` constant from `.ddc.dill` to `.node.ddc.dill` in `build_node_compilers/builders.dart` helps.

How should platforms for `DartPlatform.register` call be named? For example, renaming `ddc` to `node.ddc` leads to a failure:
> Both `build_node_compilers:ddc_modules` and `build_web_compilers:ddc_modules` may output `package:args/.node.ddc.meta_module.clean`.

Calling it `ddc.node` instead, works fine.

**Comment by jakemac53** [comment]
> Renaming `ddcKernelExtension` constant from `.ddc.dill` to `.node.ddc.dill` in `build_node_compilers/builders.dart` helps.

Ya I guess that isn't directly tied to the platform :/, I am not really sure why we didn't do it that way but probably not worth changing at this point.

> Calling it `ddc.node` instead, works fine.

That looks like a quirk of `.ddc.meta_module.raw` being a suffix of `.node.ddc.meta_module.raw`. You will have to be a bit careful with the platform names here, and choose something that doesn't end in `ddc`.

**Comment by lexaknyazev** [comment]
`build.yaml` for `build_node_compilers` lists these file extensions for different builders. Some of them are the same as in `build_web_compilers`, while others end with the same patterns. Should all of them be changed?

It's just not self-evident how platform names, extensions from `build.yaml`, and similar consts in `dev_compiler_builder.dart` are connected.

```yaml
builders:
  dart2js_modules:
    build_extensions:
      $lib$:
        - .dart2js.meta_module.raw
        - .dart2js.meta_module.clean
      .dart:
        - .dart2js.module
    required_inputs: [".dart", ".module.library"]
  ddc_modules:
    build_extensions:
      $lib$:
        - .ddc.meta_module.raw
        - .ddc.meta_module.clean
      .dart:
        - .ddc.module
    required_inputs: [".dart", ".module.library"]
  ddc:
    build_extensions:
      .ddc.module:
        - .node.ddc.dill
        - .node.ddc.js.errors
        - .node.ddc.js
        - .node.ddc.js.map
    required_inputs:
      - .ddc.module
  entrypoint:
    build_extensions:
      .dart:
        - .dart.bootstrap.js
        - .dart.js
        - .dart.js.map
        - .digests
    required_inputs:
      - .dart
      - .node.ddc.js
      - .ddc.module
      - .dart2js.module
```
