### ISSUE TITLE
Unexpected Null Value on some classes

### ISSUE THREAD

**Issue by e-belair** [dart-lang/build#2553]
Excuse my English, I don't know how to explain well but I encounter a weird issue.
One of the main error is a comparison of DateTime

![](https://files.gitter.im/dart-lang/angular/Ay5K/image.png)

If I continue the script execution, the line 26 fails, I get the following error :
```
Error: NoSuchMethodError: '<Unexpected Null Value>'
method not found
Receiver: null
Arguments: []
    at Object.throw_ [as throw] (dart_sdk.js:4593)
    at Object.throwNullValueError (dart_sdk.js:4546)
    at Object._notNull [as notNull] (dart_sdk.js:4897)
    at Duration.get inMilliseconds [as inMilliseconds] (dart_sdk.js:40424)
    at core.DateTime._withValue.add (dart_sdk.js:40166)
    at cache_item.CacheItem.new.isValid (cache_item.dart:26)
    at get (browser_cache.dart:15)
    at get.next (<anonymous>)
```
I could solve this problem by removing the const keyword and change some of the code.
But, after starting webdev serve and I get the same kind of error on every material dropdown select:
```
EXCEPTION: NoSuchMethodError: '<Unexpected Null Value>'
method not found
Receiver: null
Arguments: []
STACKTRACE: 
dart:sdk_internal 28290:14                                            createTimer
package:angular/src/core/zone/ng_zone.dart 222:25                     [_createTimer]
dart:sdk_internal 28026:33                                            new
package:angular_components/material_popup/material_popup.dart 517:25  [_onPopupOpened]
package:angular_components/material_popup/material_popup.dart 479:11  <fn>
package:angular/src/core/zone/ng_zone.dart 156:18                     <fn>
dart:sdk_internal 28247:14                                            runUnary
package:angular/src/core/zone/ng_zone.dart 153:18                     [_runUnary]
dart:sdk_internal 23631:24                                            add
package:angular_components/material_popup/material_popup.dart 869:29  <fn>
```

I report this issue as @jakemac53 recommended to me including what you told me on Gitter:

> Actually I just talked with a coworker about this and it looks like you probably need a newer build_web_compilers
> let me find the actual version you need
> https://github.com/dart-lang/build/blob/master/build_web_compilers/CHANGELOG.md#261
> the fix mentioned there is what you need, its in version 2.6.1
> Previous versions included the old dart_sdk.js (compiled with the analyzer frontend and old DDC) instead of the new dart_sdk.js (compiled with the kernel frontend and new DDC)
> this only matters in a few weird edge cases but specifically const Durations is one of them
> Please link the sdk issue if you do open it - I can close it with these same instructions so if other people hit the same problem hopefully they can find it

I'm using build_web_compilers 2.4.1, unfortunately I can't upgrade to 2.6.1 because of dependencies conflicts. I tried some depdnency_override but that break the app compiling every time.
Here is my pubspec.yam file:

```
name: agde_mobilite_web
description: A web app that uses AngularDart
version: 0.4.20

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  analyzer: ^0.37.1+1
  angular: ^6.0.0-alpha+1
  angular_components: ^0.14.0-alpha+1
  angular_forms: ^2.1.4
  angular_router: ^2.0.0-alpha+24
  build: ^1.1.6
  build_config: ^0.4.1+1
  bulma_sass: ^0.7.5
  collection: ^1.14.12
  cookie_jar: ^1.0.1
  crypto: ^2.1.3
  date_calendar: ^0.2.1
  dio: ^3.0.5
  http: ^0.12.0+2
  injector: ^1.0.8
  intl: ^0.15.8
  mdc_web: ^0.4.1+1
  recase: ^2.0.1
  reflectable: ^2.1.0
  sass_builder: ^2.1.3
  stream_transform: ^0.0.20
  uuid: ^2.0.4

dev_dependencies:
  angular_test: ^2.4.0
  built_html: ^0.1.3
  build_runner: ^1.6.9
  build_test: ^0.10.8
  build_vm_compilers: ^1.0.4
  build_web_compilers: ^2.6.1
  coverage: ^0.13.3+1
  grinder: ^0.8.3+1
  intl_translation: ^0.17.7
  json_serializable: ^3.2.3
  logging: ^0.11.3+2
  mockito: ^4.1.1
  pageloader: ^3.2.2
  path: ^1.6.4
  pedantic: ^1.8.0+1
  test: ^1.9.4

dependency_overrides:
```
