### ISSUE TITLE
I have hit a bug in build_runner, apparently

### ISSUE THREAD

**Issue by domesticmouse** [dart-lang/build#2566]
## Dart SDK Version 

```bash
$ flutter --version
Flutter 1.13.1-pre.59 • channel master • https://github.com/flutter/flutter.git
Framework • revision e58dc16d7b (26 hours ago) • 2019-12-06 18:21:52 -0800
Engine • revision e7b69ced2e
Tools • Dart 2.7.0 (build 2.7.0-dev.2.1 a9c77229c2)
```

## What package(s) from this repo you are using, and the version 

- `build`: 1.2.2
- `build_config`: 0.4.1+1
- `build_daemon`: 2.1.2
- `build_resolvers`: 1.2.1
- `build_runner`: 1.7.2
- `build_runner_core`: 4.2.0

## What builder(s) you are using (or writing yourself). 

- `built_collection`: 4.3.0
- `built_value`: 7.0.0
- `built_value_generator`: 7.0.0

## Whether you are using Windows, MacOSX, or Linux 

macOS 10.14.6 (18G1012)

## Whether you are using Chrome, Safari, Firefox, Edge 

Chrome | 79.0.3945.74 (Official Build) beta (64-bit)

### build.yaml

```
targets:
  $default:
    builders:
      built_value_generator|built_value:
        enabled: true

builders:
  built_value:
    target: ":built_value_generator"
    import: "package:built_value_generator/builder.dart"
    builder_factories: ["builtValue"]
    build_extensions: {".dart": [".built_value.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
```

###  Error log

```
  
  InvalidOutputException: flutter_desktop_app|lib/src/serializers.g.dart
  Should not delete assets outside of desktop_photo_search
  
  package:build_runner_core/src/asset/file_based.dart 98:7             FileBasedAssetWriter.delete
  package:build_runner_core/src/generate/build_definition.dart 385:38  _Loader._cleanupOldOutputs.<fn>.<fn>
  dart:async                                                           Future.wait
  package:build_runner_core/src/generate/build_definition.dart 381:20  _Loader._cleanupOldOutputs.<fn>
  package:build_runner_core/src/logging/logging.dart 25:30             logTimedAsync
  package:build_runner_core/src/generate/build_definition.dart 378:11  _Loader._cleanupOldOutputs
  package:build_runner_core/src/generate/build_definition.dart 340:13  _Loader._tryReadCachedAssetGraph.<fn>
  package:build_runner_core/src/logging/logging.dart 25:30             logTimedAsync
  package:build_runner_core/src/generate/build_definition.dart 329:12  _Loader._tryReadCachedAssetGraph
  package:build_runner_core/src/generate/build_definition.dart 198:28  _Loader.prepareWorkspace
  package:build_runner_core/src/generate/build_definition.dart 67:50   BuildDefinition.prepareWorkspace
  package:build_runner_core/src/generate/build_impl.dart 116:49        BuildImpl.create
  package:build_runner_core/src/generate/build_runner.dart 33:42       BuildRunner.create
  package:build_runner/src/generate/build.dart 99:35                   build
  package:build_runner/src/entrypoint/build.dart 28:24                 BuildCommand.run
  package:args/command_runner.dart 197:27                              CommandRunner.runCommand
  package:args/command_runner.dart 112:25                              CommandRunner.run.<fn>
  dart:async                                                           new Future.sync
  package:args/command_runner.dart 112:14                              CommandRunner.run
  package:build_runner/src/entrypoint/run.dart 24:31                   run
  .dart_tool/build/entrypoint/build.dart 25:22                         main
  pub finished with exit code 1
```
