### ISSUE TITLE
Config option for disabling all auto-applied builders for a target

### ISSUE THREAD

**Issue by evanweible-wf** [dart-lang/build#2601]
We have a few projects that are large enough to warrant some not-so-pretty `build.yaml` configuration in order to improve build times. This requires specifying some custom targets, which in turn requires disabling of some auto-applied builders in each target that would otherwise produce conflicting outputs. The config for this looks like so:

```yaml
targets:
  $default:
    sources:
      include:
        - lib/**
    dependencies:
      - :module_bootstrap
    builders:
      # disable all auto-applied builders except compiler builders (bwc and bvc)
      build_modules|module_library:
        enabled: false
      build_test|test_bootstrap:
        enabled: false
      # etc.

  module_bootstrap:
    sources:
      include:
        - example/**
        - lib/**
        - test/**
        - web/**
    builders:
      # disable all the compiler builders, but allow the rest of the auto-applied
      # builders to run in this target so that all dart codegen is done here.
      build_web_compilers|ddc_modules:
        enabled: false
      build_web_compilers|dart2js_modules:
        enabled: false
      build_web_compilers|ddc:
        enabled: false
      build_web_compilers|entrypoint:
        enabled: false
      # also disable build_vm_compilers builders here, too, if used

# The following targets are defined for the common top-level directories
# and must have all auto-applied builders disabled except the compiler builders

  example:
    sources:
      include:
        - example/**
    dependencies:
      - $default
    builders:
      build_modules|module_library:
        enabled: false
      build_test|test_bootstrap:
        enabled: false
      # etc.

      build_web_compilers|entrypoint:
        generate_for:
          include:
            - "example/**.dart"

  test:
    sources:
      include:
        - test/**
    dependencies:
      - $default
    builders:
      build_modules|module_library:
        enabled: false
      build_test|test_bootstrap:
        enabled: false
      # etc.

      build_web_compilers|entrypoint:
        generate_for:
          include:
            - "test/**.browser_test.dart"

  web:
    sources:
      include:
        - web/**
    dependencies:
      - $default
    builders:
      build_modules|module_library:
        enabled: false
      build_test|test_bootstrap:
        enabled: false
      # etc.

      build_web_compilers|entrypoint:
        generate_for:
          include:
            - "web/**.dart"
```

There are two main disadvantages of this approach:

- It's verbose
- It will break as soon as a new builder is added (either directly or transitively through a dependency)

---

Adding a config option for a target that disables the auto-application of builders would make the config _slightly_ less verbose, but primarily it would protect it from breaking as new auto-applied builders are added (either in the project or when consumed downstream). When used, builders would need to be explicitly enabled in order to run for that target.

An example of what this might look like:

```diff
  targets:
    $default:
      sources:
        include:
          - lib/**
      dependencies:
        - :module_bootstrap
+     auto_apply_builders: false
      builders:
-       # disable all auto-applied builders except compiler builders (bwc and bvc)
-       build_modules|module_library:
-         enabled: false
-       build_test|test_bootstrap:
-         enabled: false
-       # etc.
+       build_web_compilers|ddc_modules:
+         enabled: true
+       build_web_compilers|dart2js_modules:
+         enabled: true
+       build_web_compilers|ddc:
+         enabled: true
   
    module_bootstrap:
      sources:
        include:
          - example/**
          - lib/**
          - test/**
          - web/**
      builders:
        # disable all the compiler builders, but allow the rest of the auto-applied
        # builders to run in this target so that all dart codegen is done here.
        build_web_compilers|ddc_modules:
          enabled: false
        build_web_compilers|dart2js_modules:
          enabled: false
        build_web_compilers|ddc:
          enabled: false
        build_web_compilers|entrypoint:
          enabled: false
        # also disable build_vm_compilers builders here, too, if used

  # The following targets are defined for the common top-level directories
  # and must have all auto-applied builders disabled except the compiler builders

    example:
      sources:
        include:
          - example/**
      dependencies:
        - $default
+     auto_apply_builders: false
      builders:
-       build_modules|module_library:
-         enabled: false
-       build_test|test_bootstrap:
-         enabled: false
-       # etc.

        build_web_compilers|entrypoint:
+         enabled: true
          generate_for:
            include:
              - "example/**.dart"

    test:
      sources:
        include:
          - test/**
      dependencies:
        - $default
+     auto_apply_builders: false
      builders:
-       build_modules|module_library:
-         enabled: false
-       build_test|test_bootstrap:
-         enabled: false
-       # etc.

        build_web_compilers|entrypoint:
+         enabled: true
          generate_for:
            include:
              - "test/**.browser_test.dart"

    web:
      sources:
        include:
          - web/**
      dependencies:
        - $default
+     auto_apply_builders: false
      builders:
-       build_modules|module_library:
-         enabled: false
-       build_test|test_bootstrap:
-         enabled: false
-       # etc.

      build_web_compilers|entrypoint:
+         enabled: true
          generate_for:
            include:
              - "web/**.dart"
```

fyi @jakemac53
