### ISSUE TITLE
GET http://localhost:8080/main.dart.js net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by LightYagami200** [dart-lang/build#2621]
Hi,

I'm using `webdev serve` to serve the angular dart application, but suddenly I started getting the error "GET http://localhost:8080/main.dart.js net::ERR_ABORTED 404 (Not Found)"

![image](https://user-images.githubusercontent.com/35832598/74082241-eadbe800-4a79-11ea-8549-3bd00611fe42.png)

Dart VM Version: 2.7.1

Pubspec Dependencies: 

```
dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0+1
  angular_router: ^2.0.0-alpha
  markdown: ^2.1.3
  sembast: ^2.1.3

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.5.1
  build_test: ^0.10.0
  build_web_compilers: ^2.4.0
  test: ^1.6.0
  sass_builder: ^2.1.3

```

I've tried both `webdev serve` and `build_runner` but neither is creating main.dart.js

Operating System: Windows

Browser: Tried in Chrome & Edge
