### ISSUE TITLE
dart2js_bootstrap does not respect the `--out` dart2js arg in build.yaml

### ISSUE THREAD

**Issue by StorminGorman** [dart-lang/build#2628]
Dart Version 2.7.1
build_runner latest

Consider the following build.production.yaml:
```
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          - web/mainProduction.dart
        options:
          compiler: dart2js
          # List any dart2js specific args here, or omit it.
          dart2js_args:
          - --fast-startup
          - --minify
          - --trust-primitives
          - --out=web/main.dart.js
```

The `--out=web/main.dart.js` option is overridden due to https://github.com/dart-lang/build/blob/master/build_web_compilers/lib/src/dart2js_bootstrap.dart#L72
