### ISSUE TITLE
How fix this?

### ISSUE THREAD

**Issue by kaparray** [dart-lang/build#2629]
Failed to precompile build_runner:graph_inspector:
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.2.1/lib/src/resolver.dart:263:31: Error: Too many positional arguments: 2 allowed, but 3 found.
Try removing the extra positional arguments.
  var sdk = FolderBasedDartSdk(resourceProvider, dartSdkFolder, true)
                              ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/src/dart/sdk/sdk.dart:465:3: Context: Found this candidate, but the arguments don't match.
  FolderBasedDartSdk(ResourceProvider resourceProvider, Folder sdkDirectory)
  ^^^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.2.1/lib/src/resolver.dart:273:25: Error: The argument type 'Set<dynamic>' can't be assigned to the parameter type 'Iterable<Source>'.
 - 'Set' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'Source' is from 'package:analyzer/src/generated/source.dart' ('../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/src/generated/source.dart').
  return SummaryBuilder(sdkSources, sdk.context).build();
                        ^
Failed to precompile build_runner:build_runner:
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.2.1/lib/src/resolver.dart:263:31: Error: Too many positional arguments: 2 allowed, but 3 found.
Try removing the extra positional arguments.
  var sdk = FolderBasedDartSdk(resourceProvider, dartSdkFolder, true)
                              ^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/src/dart/sdk/sdk.dart:465:3: Context: Found this candidate, but the arguments don't match.
  FolderBasedDartSdk(ResourceProvider resourceProvider, Folder sdkDirectory)
  ^^^^^^^^^^^^^^^^^^
../../development/flutter/.pub-cache/hosted/pub.dartlang.org/build_resolvers-1.2.1/lib/src/resolver.dart:273:25: Error: The argument type 'Set<dynamic>' can't be assigned to the parameter type 'Iterable<Source>'.
 - 'Set' is from 'dart:core'.
 - 'Iterable' is from 'dart:core'.
 - 'Source' is from 'package:analyzer/src/generated/source.dart' ('../../development/flutter/.pub-cache/hosted/pub.dartlang.org/analyzer-0.39.4/lib/src/generated/source.dart').
  return SummaryBuilder(sdkSources, sdk.context).build();

```yaml
...
environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  kiwi: ^0.2.0
  signalr_client: ^0.1.6
  signalr_core: ^1.0.2
  pedantic: ^1.7.0
  http: ^0.12.0+4

  # built libs
  built_value:
  built_collection:
  built_redux:
  flutter_built_redux:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build:
  build_config:
  built_value_generator:
  build_runner:
  kiwi_generator: '>=0.4.0'


dependency_overrides:
  build: ^1.2.2
  analyzer: ^0.39.4

```
