### ISSUE TITLE
Watcher error for emacs temp file

### ISSUE THREAD

**Issue by bradyt** [dart-lang/build#2635]
Seems to be similar to this issue: https://github.com/dart-lang/build/issues/1134.

If I use `pub run build_runner watch`, and edit a file with Emacs, 

```
[SEVERE] built_value_generator:built_value on lib/src/.#types.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
[SEVERE] Unhandled build failure!
FileSystemException: Cannot create file, path = '.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache/cone_lib/0/lib/src/.' (OS Error: Is a directory, errno = 21)
[SEVERE] Failed after 7ms
```

Environment information:
```
$ dart --version
Dart VM version: 2.7.1 (Thu Jan 23 13:02:26 2020 +0100) on "macos_x64"
```

```yaml
# pubspec.lock
...
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      url: "https://pub.dartlang.org"
    source: hosted
    version: "1.7.4"
...
  built_value:
    dependency: "direct main"
    description:
      name: built_value
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.0.9"
  built_value_generator:
    dependency: "direct dev"
    description:
      name: built_value_generator
      url: "https://pub.dartlang.org"
    source: hosted
    version: "7.0.9"
...
```

**Comment by jakemac53** [comment]
Looks like it is using a `#` as a prefix for the file names which confuses things unsurprisingly as that is a uri fragment. It seems to be getting stripped. This could be a problem with the watcher package or something in our code although we don't really work with uris, I would guess its something in watcher.

**Comment by jakemac53** [comment]
Hmm we do actually allow getting uris for AssetIds, which it looked like is partly where we had issues before.

Given that I don't think its even possible to create a sensible uri from this I am inclined to close this as not planned.

cc @natebosch

**Comment by jakemac53** [comment]
See here which I think is the actual culprit https://github.com/dart-lang/build/blob/master/build_runner_core/lib/src/logging/failure_reporter.dart#L116.

Any idea why we are using `p.fromUri` for that @natebosch ?

**Comment by natebosch** [comment]
> Any idea why we are using `p.fromUri` for that @natebosch ?

It's because the argument is the `path` part, which is always URI separator, not the OS separator.

The real problem is that we aren't escaping properly when we go from OS to URI style path somewhere I think. That `path` should really have the `#` escaped as `%23`

**Comment by natebosch** [comment]
@bradyt - can you try a git override for `build_runner_core` and see if it's working? Assuming it is I can publish.

We expect there may be build errors when you have files named `.dart` that aren't valid Dart files, but we hope that this resolves the stack trace.

**Comment by bradyt** [comment]
Ah, maybe there wasn't really anything broken. If I try this:

```yaml
dependency_overrides:
  build_runner_core:
    version: '4.4.1-dev'
    git:
      url: https://github.com/dart-lang/build.git
      path: build_runner_core
```

**Comment by bradyt** [comment]
Ah, maybe there wasn't really anything broken. I tried the following as you suggested.

```yaml
dependency_overrides:
  build_runner_core:
    version: '4.4.1-dev'
    git:
      url: https://github.com/dart-lang/build.git
      path: build_runner_core
```

Then I no longer see this:

```
FileSystemException: Cannot create file, path = '.dart_tool/build/098d3ee73e6cc294616d3a2e2c3c81ad/error_cache/cone_lib/0/lib/src/.' (OS Error: Is a directory, errno = 21)

```

But I still see the following:

```
[SEVERE] built_value_generator:built_value on lib/src/.#types.dart:

NoSuchMethodError: The getter 'element' was called on null.
Receiver: null
Tried calling: element
```

But nothing actually "breaks".

(Almost completely unrelated, but for context; if for example, I had an incorrect name in a Built class, then I would see logs like, `Please make the following changes to use BuiltValue:`, the `.g.dart` file would disappear, and that would break my usage of tools like `ls lib/**/*.dart | entr -s 'pub run test'`.)
