### ISSUE TITLE
Trying to create a custom builder results in a non unique output error

### ISSUE THREAD

**Issue by Olegas** [dart-lang/build#2670]
Dart: 2.7.2
Packages:
 - build_runner: ^1.8.0
 - built_value_generator: ^7.0.9
OS: macOS

I'm trying to create custom builder for my Flutter project. I want to achieve something similar to built_value code generation.

I've started by creating `build.yaml` in the root folder of my project

```
targets:
  $default:
    builders:
      app|db_builder:
        enabled: true

builders:
  db_builder:
    target: ":db_builder"
    import: "package:app/db/build/builder.dart"
    builder_factories: ["dbBuilder"]
    build_extensions: {".dart": [".db.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
```

Then implemented `dbBuilder` factory at `app/db/build/builder.dart`

```
import 'package:build/build.dart';
import 'package:source_gen/source_gen.dart';

import 'db_generator.dart';

Builder dbBuilder(BuilderOptions _) =>
    SharedPartBuilder([DBAccessGenerator()], 'built_value');
```

`DBAccessGenerator` is an empty class inherited from `Generator`

My project also contains built_value_generator.

After the above mentioned steps, when running `flutter pub run build_runner build` I've got the following error:

```
Both app:db_builder and built_value_generator:built_value may output
test/widget_test.built_value.g.part. Potential outputs must be unique across all builders.
```

Why this happens? I've seen the [source code](https://github.com/google/built_value.dart/blob/master/built_value_generator/build.yaml) of built_value_generator and it declares build extensions as `build_extensions: {".dart": [".built_value.g.part"]}` but my declaration differs, I'm using another target extension.
