### ISSUE TITLE
buildStep.writeAsString() does not work

### ISSUE THREAD

**Issue by comerc** [dart-lang/build#2771]
Dart SDK version: 2.10.0-2.0.dev.flutter-bd528bfbd6 (be) (Thu Jul 30 19:12:38 2020 +0000) on "linux_x64"

build_runner: 1.10.2

`common/markdown_builder.dart`

```dart
import 'package:build/build.dart';
import 'package:markdown/markdown.dart';

Builder markdownBuilder(_) => MarkdownBuilder();

class MarkdownBuilder implements Builder {
  @override
  void build(BuildStep buildStep) async {
    var inputId = buildStep.inputId;
    var contents = await buildStep.readAsString(inputId);
    var markdownContents = markdownToHtml(contents);
    var outputId = inputId.changeExtension('.html');
    await buildStep.writeAsString(outputId, markdownContents);
  }

  @override
  Map<String, List<String>> get buildExtensions => {
        '.md': ['.html']
      };
}
```

`build.yaml`

```yaml
builders:
  markdown:
    import: "package:my_app/common/markdown_builder.dart"
    builder_factories:
      - markdownBuilder
    build_extensions:
      .md:
        - .html
    auto_apply: root_package
    required_inputs:
      - .md
```
