### ISSUE TITLE
Just started seeing a warning for missing $package$ in my build.yaml

### ISSUE THREAD

**Issue by talamaska** [dart-lang/build#2781]
I'm using rosetta package and it's generator
I have upgraded to flutter 1.20.1 and build_runner 1.10.1
I started seeing a warning
```
[WARNING] The package `my_app_name` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - $package$
```

my build.yaml looks like this 

```
targets:
  $default:
    sources:
      include:
      - i18n/**
      - lib/**
```

flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 1.20.1, on Microsoft Windows [Version 10.0.18362.959], locale bg-BG)

[√] Android toolchain - develop for Android devices (Android SDK version 28.0.3)
[√] Android Studio (version 4.0)
[√] VS Code, 64-bit edition (version 1.47.3)
[√] Connected device (1 available)

• No issues found!

flutter --version
Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (35 hours ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0

Already asked in gitter, so far no response.
So I'm wondering what I'm missing from the build.yaml that I have to add in order to avoid this warning.

**Comment by jakemac53** [comment]
Ah, yes so we added this extra placeholder file (meant to replace other placeholder files). You will need to add `$package$` to your sources list (see the updated docs [here](https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-include-additional-sources-in-my-build))

```yaml
targets:
  $default:
    sources:
      include:
      - i18n/**
      - lib/**
      - $package$
```
