### ISSUE TITLE
buildRunner issue

### ISSUE THREAD

**Issue by ptyagicodecamp** [dart-lang/build#2785]
Hi,
I'm using `buildRunner` to generate moor file(s) using `flutter packages pub run build_runner build --delete-conflicting-outputs` command. 

I'm working on Mac with following Flutter and Dart versions:

Flutter 1.20.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2ae34518b8 (5 days ago) • 2020-08-05 19:53:19 -0700
Engine • revision c8e3b94853
Tools • Dart 2.9.0

Getting following message on console when running command mentioned above.
```
$ flutter packages pub run build_runner build --delete-conflicting-outputs
Precompiling executable...
Precompiled build_runner:build_runner.
[INFO] Generating build script...
[INFO] Generating build script completed, took 613ms



You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues


Unimplemented handling of missing static target
package:path/src/context.dart 347:12                                   Context.canonicalize
package:path/path.dart 317:45                                          canonicalize
package:build_runner_core/src/package_graph/package_graph.dart 163:31  PackageNode._toAbsolute
package:build_runner_core/src/package_graph/package_graph.dart 150:16  new PackageNode
package:build_runner_core/src/package_graph/package_graph.dart 86:29   PackageGraph.forPath
package:build_runner_core/src/package_graph/package_graph.dart 110:20  PackageGraph.forThisPackage
package:build_runner/src/entrypoint/run.dart 22:64                     run
.dart_tool/build/entrypoint/build.dart 30:22                           main

pub finished with exit code 1

```

Moor package related `pubspec.yaml` config:
```
  moor: ^2.2.0

  # Database for mobile and Desktop
  moor_ffi: ^0.3.0
  # Helper to find the database path on mobile
  path_provider: ^1.5.1
  path: ^1.6.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.4.0
  moor_generator: ^2.2.0
```
