### ISSUE TITLE
Pub get fails on build_runner: 1.10.2

### ISSUE THREAD

**Issue by AbelSAnderson** [dart-lang/build#2792]
Dart VM version: 2.9.0-14.1.beta (beta) (Tue Jun 9 10:52:57 2020 +0200) on "windows_x64"

build_runner version: 1.10.2

pubspec.yaml:
```
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3

dev_dependencies:
  build_runner: ^1.10.2

  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
```

Running pub get sends back an error:
```
Running "flutter pub get" in test_app...                        

The current Dart SDK version is 2.9.0-14.1.beta.

Because test_app depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.
pub get failed (1; Because test_app depends on build_runner >=1.10.2 which requires SDK version >=2.10.0-0.0 <3.0.0, version solving failed.)
Process finished with exit code 1
```

Previous versions of build_runner resolve without errors.
