### ISSUE TITLE
Error while trying to build: The method 'MultiHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.a dd'

### ISSUE THREAD

**Issue by feinstein** [dart-lang/build#2833]
I got this error while trying to run `flutter packages pub run build_runner watch`. Honestly I have no idea what's going on, it has been some time that I didn't run `build_runner`, but I think all my versions are compatible, these are the versions on pubspec.yaml:

```yaml
environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  built_value: ^7.1.0
  built_collection: ^4.3.2



dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^1.10.1
  built_value_generator: ^7.1.0
```

And this is the error:

```
>flutter packages pub run build_runner watch

Precompiling executable...
Failed to precompile build_runner:build_runner:
/C:/Programming/Flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/http_multi_server-2.1.0/lib/src/multi_headers.dart:97:8: Error: The method 'MultiHeaders.add' has fewer named arguments than those of overridden method 'HttpHeaders.a
dd'.
  void add(String name, Object value) {
       ^
org-dartlang-sdk:///sdk/lib/_http/http.dart:699:8: Context: This is the overridden method ('add').
  void add(String name, Object value,
       ^
/C:/Programming/Flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/http_multi_server-2.1.0/lib/src/multi_headers.dart:129:8: Error: The method 'MultiHeaders.set' has fewer named arguments than those of overridden method 'HttpHeaders.
set'.
  void set(String name, Object value) {
       ^
org-dartlang-sdk:///sdk/lib/_http/http.dart:708:8: Context: This is the overridden method ('set').
  void set(String name, Object value,
       ^
/C:/Programming/Flutter/sdk/flutter/.pub-cache/hosted/pub.dartlang.org/dart_style-1.3.3/lib/src/dart_formatter.dart:105:30: Error: Too many positional arguments: 0 allowed, but 1 found.
Try removing the extra positional arguments.
    scanner.configureFeatures(featureSet);
                             ^
pub finished with exit code 1
```

This was invoked from the IntelliJ IDEA Terminal on Windows 10 with Flutter 1.20.4 and Dart 2.9.2.
