### ISSUE TITLE
flutter packages pub run build_runner build takes a long time

### ISSUE THREAD

**Issue by lyqiai** [dart-lang/build#2861]
[INFO] 2m 42s elapsed, 1585/1599 actions completed.
[INFO] 2m 43s elapsed, 1601/1613 actions completed.
[INFO] 2m 44s elapsed, 1613/1629 actions completed.
[INFO] 2m 45s elapsed, 1629/1645 actions completed.
[INFO] 2m 46s elapsed, 1645/1657 actions completed.
[INFO] 2m 49s elapsed, 1662/1662 actions completed.
[INFO] Running build completed, took 2m 50s

[INFO] Caching finalized dependency graph...
[INFO] 2m 51s elapsed, 1673/1673 actions completed.
[INFO] Caching finalized dependency graph completed, took 1.9s
----------------------------end log-----------------------------
Is there a way to optimize？

**Comment by jakemac53** [comment]
You can see this faq entry for how to evaluate where the time is going https://github.com/dart-lang/build/blob/master/docs/measuring_performance.md, as a starting point.

Most likely you have a lot of builders which are using full analysis for their inputs (all source_gen builders do this), and the best way to optimize those is to configure the `generate_for` setting in a `build.yaml` file so they only run on the required inputs. That would look something like this:

```yaml
targets:
  $default:
    builders:
      # Typically the builder key is just the package name, run `pub run build_runner doctor` to check your config.
      <builder-key>:
        generate_for:
          # Example glob for only the Dart files under `lib/models`
          - lib/models/*.dart
```
