### ISSUE TITLE
How to forbid build cache

### ISSUE THREAD

**Issue by v7lin** [dart-lang/build#2868]
I want to use post_process_builders to clean build cache, but i seem does not work

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`)

```shell
Dart SDK version: 2.10.2 (stable) (Tue Oct 13 15:50:27 2020 +0200) on "macos_x64"
```

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)

```
  build_runner: 1.7.2
```

* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.

```
# Read about `build.yaml` at https://pub.dartlang.org/packages/build_config
builders:
  router_compiler:
    import: 'package:router_compiler/builder.dart'
    builder_factories: ['routerCompiler']
    build_extensions: { '.dart': ['.router_compiler.g.part'] }
    auto_apply: dependents
    build_to: cache
    applies_builders: ['source_gen|combining_builder', '|router_cleanup']
post_process_builders:
  router_cleanup:
    import: 'package:router_compiler/builder.dart'
    builder_factory: 'routerCleanup'
```

```dart
import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:logging/logging.dart';
import 'package:router_annotation/router_annotation.dart';
import 'package:router_compiler/src/info/info.dart';
import 'package:router_compiler/src/parser/page_parser.dart';
import 'package:router_compiler/src/util/exceptions.dart';
import 'package:router_compiler/src/writer/page_writer.dart';
import 'package:source_gen/source_gen.dart';

final Logger _log = Logger('RouterCompiler');

class RouterCompilerGenerator extends GeneratorForAnnotation<Page> {
  RouterCompilerGenerator();

  @override
  dynamic generateForAnnotatedElement(Element element, ConstantReader annotation, BuildStep buildStep) {
    if (element is! ClassElement) {
      throw RouterCompilerException('Page annotation can only be defined on a class.');
    }

    try {
      PageInfo info = PageParser.parse(element as ClassElement, annotation, buildStep);
      _log.info('${info.name}-${info.routeName}-${info.displayName};');

      PageWriter writer = PageWriter(info);

      writer.generate();
      return writer.toString();
    } on Exception catch (e, s) {
      _log.severe(e);
      _log.severe(s);
      return '// $e \n\n';
    }
  }
}

Builder routerCompilerBuilder({Map<String, dynamic> config}) => SharedPartBuilder(
      <Generator>[
        RouterCompilerGenerator(),
      ],
      'router_compiler',
    );

class RouterCleanupBuilder implements PostProcessBuilder {
  const RouterCleanupBuilder();

  @override
  void build(PostProcessBuildStep buildStep) {
    _log.info('clean ${buildStep.inputId.uri}');
    buildStep.deletePrimaryInput();
  }

  @override
  Iterable<String> get inputExtensions => <String>[
        '.router_compiler.g.part',
      ];
}

PostProcessBuilder routerCleanupBuilder({Map<String, dynamic> config}) => const RouterCleanupBuilder();
```

* Whether you are using Windows, MacOSX, or Linux (if applicable)

MacOSX

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Flutter Android/iOS
