### ISSUE TITLE
build_runner test sourcemaps are ignored

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/build#2901]
**Short summary:**

Running `pub run build_runner test -r -- -p chrome` command, I'd expect Dart stack traces to be reported in console. It is not the case.

**Things I tried**

In build yaml, I have the following to ensure that after building the assets, I retain the sourcemaps.

```yaml
global_options:
  build_web_compilers|dart_source_cleanup:
    release_options:
      enabled: false
  build_web_compilers|dart2js_archive_extractor:
    release_options:
      filter_outputs: false
```

I verified that they are in fact loaded, by starting tests with `--pause-after-load` and opening a dart file in chrome's dev toolbar. I'm not sure where the issue is but:

- I have sourcemaps
- they get loaded in browser
- I see non-mapped JS stack trace in console for errors

Anything I can do to get Dart traces?

Extra info:

* Dart SDK version: 2.9.3 (stable)
```
  build_runner:
    version: "1.9.0"
  build_runner_core:
    version: "5.1.0"
  build_test:
    version: "1.0.0"
  build_web_compilers:
    version: "2.10.0"
```
* Using it for an Angular 5.3.1 app

This issue might be related to https://github.com/dart-lang/build/issues/2377 but I'm not sure.
