### ISSUE TITLE
Add support for nullsafety

### ISSUE THREAD

**Issue by vanlooverenkoen** [dart-lang/build#2920]
I am upgrading my package (Kiwi) vanlooverenkoen/kiwi#51

But it seems that build & build_runner is not yet migrated to support nullsafety. Is there a timeline on when this could be added?

**Comment by jakemac53** [comment]
We are blocked for a while on upstream dependencies, namely `analyzer`.

Once we are unblocked we will migrate, but there is no timeline right now.

**Comment by vanlooverenkoen** [comment]
Alright thanks. :) I already created some tickets for some dart-lang packages. So we can track this.

**Comment by jakemac53** [comment]
Ya, analyzer itself has a lot of deps as well, we have been working on migrating those though. But they have a large and very legacy codebase (originally ported from Java) so its going to be..... something to migrate it 🤣

**Comment by vanlooverenkoen** [comment]
@jakemac53 do you know if ther already is a ticket for tracking the nullsafety support for analyzer? otherwise we can link these tickets together. If not I will create a new ticket

**Comment by jakemac53** [comment]
It is being tracked somewhere, but I think not in a github issue (that team doesn't use them for tracking generally). It definitely doesn't hurt to file one though so its easier to be notified when it is completed, and I can link it on a separate tracking sheet we have so hopefully it does get closed when the migration finishes.

**Comment by vanlooverenkoen** [comment]
Alright prefect I will create another one

**Comment by vanlooverenkoen** [comment]
Blocked because of: https://github.com/dart-lang/sdk/issues/44290

**Comment by mnordine** [comment]
This is really too bad. I'm guessing there's a ton of packages/apps blocked on this, including our own, ☹️

**Comment by jakemac53** [comment]
Note that this does not block builders from _generating_ null safe code (these already exist actually).

It blocks the build script from running with sound null safety, and blocks code generators from migrating their _generator_ code.

That is a long way of saying that this doesn't need to block _applications which use generated code_.

**Comment by mnordine** [comment]
We're using a library that uses `build_runner` and `build_web_compilers`, and we use them in our app as well (convert tank to json). Where does that leave us? I'm getting analyzer static errors due to `build_runner`

**Comment by jakemac53** [comment]
> We're using a library that uses `build_runner` and `build_web_compilers`, and we use them in our app as well (convert yaml to json).

I don't understand fully the situation here - you generally wouldn't have imports of these libraries within your app. If you do, then that will be blocked until we can migrate.

Code generators should generally be split up into two libraries - one for the generator (only imported by the build script), and one for any runtime libs which should not import `package:build`, `package:analyzer`, etc.

**Comment by jakemac53** [comment]
It might be good to also clarify that you can opt out individual libs using a language version comment before any declarations in your file:

``
// @dart=2.9
``

**Comment by mnordine** [comment]
On a phone, but I will clarify later today

**Comment by vanlooverenkoen** [comment]
@jakemac53 yes indeed. For kiwi only the generator needs to be updated. So I will have to wait

**Comment by mnordine** [comment]
@jakemac53 

Package in question is `StageXL`. I think it uses `build_runner`, `build_web_compilers` as dev deps to run the example in that repo.

As I mentioned, our app uses a build configuration that converts yaml files to json. So our `build.yaml` looks like:

```yaml
targets:

  $default:
    sources:
      {"exclude" : ["bin/**"]}
    builders:
      build_web_compilers|dart_source_cleanup:
        release_options:
          enabled: false
      build_web_compilers|dart2js_archive_extractor:
        options:
          filter_outputs: true
      build_web_compilers|entrypoint:
        generate_for:
          - web/main.dart
        dev_options:
          compiler: dartdevc
        release_options:
          compiler: dart2js
          dart2js_args:
            # See https://webdev.dartlang.org/tools/dart2js#size-and-speed-options
            - --show-package-warnings
            - -O4
            - -Ddebug=false

builders:
  yaml2JsonBuilder:
    import: "package:main/builder.dart"
    builder_factories: ["yaml2JsonBuilder"]
    build_extensions: {".yaml": [".json"]}
    auto_apply: root_package
    defaults:
      generate_for:
        include:
          - web/assets/**.yaml

global_options:
  build_web_compilers:ddc:
    options:
      environment:
        debug: 'true'
```

And we have a builder like so:

```dart
import 'dart:convert';
import 'package:build/build.dart';
import 'package:yaml/yaml.dart';

Builder yaml2JsonBuilder(BuilderOptions options) => Yaml2JsonBuilder();

class Yaml2JsonBuilder implements Builder
{
  @override
  Future<void> build(BuildStep buildStep) async
  {
    final inputId = buildStep.inputId;
    final asset = inputId.changeExtension('.json');
    final yaml = await buildStep.readAsString(inputId);
    await buildStep.writeAsString(asset, _convert(yaml));
  }

  String _convert(String yaml)
  {
    const encoder = JsonEncoder();
    final map = loadYaml(yaml);
    return encoder.convert(map);
  }

  @override
  final buildExtensions = {'.yaml': ['.json']};
}
```

So we have a dev dep on `build_runner`, `build_web_compilers`, like so:

```yaml
dev_dependencies:
  yaml: ^3.0.0-nullsafety
  meta: ^1.2.3
  build_runner: any
  build_web_compilers: any
```

But pub can't resolve without errors:

```
Because build_config >=0.3.1+1 depends on yaml ^2.1.11 and build_config >=0.1.1 <=0.3.1 requires SDK version >=1.22.1 <2.0.0 or >=2.0.0-dev.54 <2.0.0, build_config >=0.1.1 requires yaml ^2.1.11.
Thus, every version of build_web_compilers requires yaml ^2.1.11.
So, because main depends on both yaml ^3.0.0-nullsafety and build_web_compilers any, version solving failed.

```
