### ISSUE TITLE
What causes build_runner to output stars at the end of type references?

### ISSUE THREAD

**Issue by marcodafonseca** [dart-lang/build#2929]
I am new to Flutter/Dart so please bare with me if this is a stupid question. I have spent the last couple hours on Google and I just can't seem to find an answer to this situation.

I am trying to run the following command to generate files:
`flutter clean && flutter pub get && flutter pub run build_runner build --delete-conflicting-outputs --verbose`

The outputted files are full of stars at the end of type references and I don't understand why. 
Here is an example of what I mean:

```

  ///region currentUser
  Stream<User*>* _currentUserState;

  @override
  Stream<User*>* get currentUser => _currentUserState ??= _mapToCurrentUserState();

  Stream<User*>* _mapToCurrentUserState();
  ///endregion currentUser
  
```

Here is an extract example of the output from the CLI:
```
An error `FormatterException` occurred while formatting the generated source for
  `package:application/feature_sign_up/blocs/sign_up_bloc.dart`
which was output to
  `lib/feature_sign_up/blocs/sign_up_bloc.rxb.g.dart`.
This may indicate an issue in the generator, the input source code, or in the
source formatter.
Could not format because the source could not be parsed:

line 113, column 10: Expected to find '>'.
    ╷
113 │   Stream<String*>* get emailErrorMessage => _emailErrorMessageState ??= _mapToEmailErrorMessageState();
    │          ^^^^^^
    ╵

```

dart -- version output
Dart SDK version: 2.10.4 (stable) (Wed Nov 11 13:35:58 2020 +0100) on "windows_x64"

flutter --version output
Flutter 1.22.4 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 1aafb3a8b9 (3 weeks ago) • 2020-11-13 09:59:28 -0800
Engine • revision 2c956a31c0
Tools • Dart 2.10.4

dependencies from my pubspec.yaml file
```

environment:
  sdk: ">=2.10.4 <3.0.0"
  flutter: ">=1.22.4"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.24.1
  retry: ^3.0.1
  css_colors: ^1.0.2
  rx_bloc: ^1.0.4
  flutter_rx_bloc: ^1.1.1
  retrofit: ^1.3.4+1
  json_annotation: ^3.1.1
  auto_route: ^0.6.9
  provider: ^4.3.2+2
  flutter_svg: ^0.19.1
  sliding_up_panel: ^1.0.2
  flutter_secure_storage: ^3.3.5
  path_provider: ^1.6.24
  open_file: ^3.0.3
  image_picker: ^0.6.7+14
  image: ^2.1.19
  share: ^0.6.5+4
  loading_overlay: ^0.2.1
  flutter_keyboard_visibility: ^4.0.2
  firebase_dynamic_links: ^0.6.3
  firebase_analytics: ^6.3.0
  timeago: ^2.0.29
  transparent_image: ^1.0.0
  pull_to_refresh: ^1.6.3
  webview_flutter: ^1.0.7
  cached_network_image: ^2.4.1
  device_info: ^1.0.0
  dots_indicator: ^1.2.0
  intl: ^0.16.1
  location: ^3.1.0
  flutter_swiper: ^1.1.6
  timezone: ^0.5.9
  flutter_native_timezone: ^1.0.4
  flutter_image_compress: ^0.7.0
  stripe_payment: ^1.0.9
  modal_bottom_sheet: ^1.0.0+1
  webfeed: ^0.6.0
  uuid: ^2.2.2
  dio_http_cache: ^0.2.11
  shared_preferences: ^0.5.12+4
  geocoder: ^0.2.1
  cron: ^0.2.4
  flutter_local_notifications: ^3.0.1+7
  flutter_apns:
    git:
      url: git://github.com/mwaylabs/flutter-apns.git
  after_layout: ^1.0.7+2
  prime_chat:
    path: packages/prime_chat
  connecty_cube_chat_adapter:
    path: packages/connecty_cube_chat_adapter
  flutter_webrtc: ^0.5.7
  url_launcher: ^5.5.0
  keyboard_avoider: ^0.1.2
  flutter_callkeep:
    path: packages/flutter_callkeep
  flutter_voip_push_notification: ^0.0.3
  connectivity: ^2.0.2
  audioplayers: ^0.17.0
  flutter_ringtone_player: ^2.0.0
  bugsnag_crashlytics: ^0.0.7
  flutter_dotenv: ^2.1.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

#  connectycube_sdk:
#    path: "D:/connectycube_sdk-0.4.2"
#     git: git@bitbucket.org:application/connectycube-sdk.git
#flutter_callkeep:
# path: packages/flutter_callkeep

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: ^1.15.7
  build_runner: ^1.10.7
  rx_bloc_generator: ^1.0.0
  retrofit_generator: ^1.4.0+2
  json_serializable: ^3.5.1
  auto_route_generator: ^0.6.10
  rx_bloc_test: ^1.0.0
  mockito: ^4.1.3

dependency_overrides:
  analyzer: ^0.41.1
  flutter_webrtc: ^0.5.7

```

Any explanations/assistance would be greatly appreciated
