### ISSUE TITLE
build_script_generate.dart ignores config command line option

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/build#2942]
This issue is based on a use-case or rather, a user assumption, which might be incorrent. If it is, I'd like to understand where I misinterpreted how to use build configs.

## Description 

My understanding is that  if `--config` option is added as command line argument, configurations from that yaml overwrites configs from `build.yaml`.

The process:

1. create snapshot for `build_runner`
2. generate `build.dart` file based on build.yaml
3. create snapshot for `build.dart`
4. run whatever command is I specified (serve in my case)

Problem is at step 2. My use-case dictates that `build.yaml` is empty and there is a builder specified for a special case (want to augment compiled code with extra metadata from env). 

So my assumptions is that issuing `pub run build_runner serve --config=local web:8040` command will result in a build.dart file that contains the builder I specified in `build.local.yaml` file. _It does not._

What I get instead is a warning in console:

```
[WARNING] Configuring `my_package:some_meta_builder` in target `my_package:my_package` but this is not a known Builder
```

but reality shows:

```yaml
# build.local.yaml
builders:
  some_meta_builder:
    import: "package:my_package/builders/some_meta_builder.dart"
    builder_factories: ["someMetaBuilder"]
    build_extensions: { ".env.txt": [".meta.dart"] }
    build_to: source
    auto_apply: root_package
    is_optional: false
```

## Cause

https://github.com/dart-lang/build/blob/master/build_runner/lib/src/build_script_generate/build_script_generate.dart#L71

```dart
  final buildConfigOverrides =
      await findBuildConfigOverrides(packageGraph, null);
```

2nd parameter is `null`, config is never passed to `findBuildConfigOverrides`, so all overrides with the file naming convention of `build.*.yaml` are ignored.

**Relevant versions**
1.9.0 .. HEAD

### Questions:

1. am I right assuming this use-case should be supported?
2. is there a way to provide a workaround for it until a fix lands (assuming that no. 1 is true)?
