### ISSUE TITLE
Q: build_runner_core.apply ignores package graph nodes, runs for root only - is that intended?

### ISSUE THREAD

**Issue by daniel-v** [dart-lang/build#2943]
I have a simple builder I want to run for all the packages in a dependency tree. A simple code would showcase what's up:

```dart
import 'dart:io' as io;

import 'package:build_runner/build_runner.dart';
import 'package:build_runner_core/build_runner_core.dart' as bc;
import 'package:my_package/builders/my_meta_builder.dart';

Future main(List<String> args) async {
  final graph = await bc.PackageGraph.forThisPackage();
  final pkgsNo = graph.allPackages.length;
  // tracks the number of pkgs builder was invoked for
  var appliedToPkgs = 0;
  final metaBuilder = bc.apply(
    'my_package:my_meta_builder',
    [myMetaBuilderFactory],
    (pkg) {
      appliedToPkgs++;
      return true;
    },
    hideOutput: false,
  );
  io.exitCode = await run(['build', ...args], [metaBuilder]);

  print('Expected to run for $pkgsNo packages; ran for $appliedToPkgs');
}
```

Builder definition in `my_package`:

```yaml
  i18n_css_builder:
    import: "package:my_package/builders/my_meta_builder.dart"
    builder_factories: ["myMetaBuilderFactory"]
#  ...    
    is_optional: false
    build_to: source
    auto_apply: all_packages
```

Output: `Expected to run for 120 packages; ran for 1`

My suspicion is this: that the builder would want to build to source and that is allowed only for root packages. Found some code that would indicate that. https://github.com/dart-lang/build/blob/master/build_runner_core/lib/src/package_graph/apply_builders.dart#L359

Do I understand it correctly? (In other words: am I trying to do something that is unsupported?)
