### ISSUE TITLE
Ignores annotations in .part files

### ISSUE THREAD

**Issue by KsVlad** [dart-lang/build#2949]
### Problem
Build_runner doesn't generate anything if annotation supposed to be affected is placed in .part file.

### Example
Checked for json_serializable and freezed, here is minimal example for json_serializable:

clazz.dart:
```dart
import 'package:json_annotation/json_annotation.dart';

part 'clazz.g.dart';
part 'clazz_part.dart';
```

clazz_part.dart:
```dart
part of 'clazz.dart';

@JsonSerializable()
class Clazz {
  final int index;

  Clazz(this.index);

  factory Clazz.fromJson(Map<String, dynamic> json) => _$ClazzFromJson(json);
  Map<String, dynamic> toJson() => _$ClazzToJson(this);
}
```
clazz.g.dart doesn't generated at all in this situation.

If we put something related in clazz.dart, for example:
```dart
import 'package:json_annotation/json_annotation.dart';

part 'clazz.g.dart';
part 'clazz_part.dart';

@JsonSerializable()
class Clazz_1 {
  final int index;

  Clazz_1(this.index);

  factory Clazz_1.fromJson(Map<String, dynamic> json) =>
      _$Clazz_1FromJson(json);
  Map<String, dynamic> toJson() => _$Clazz_1ToJson(this);
}
```
then generated clazz.g.dart contains data for both Clazz and Clazz_1

### Config & pubsec

Flutter doctor:
```
[√] Flutter (Channel stable, 1.22.5, on Microsoft Windows [Version 10.0.19042.685], locale ru-RU)
[√] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
[!] Android Studio (version 4.1.0)
    X Flutter plugin not installed; this adds Flutter specific functionality.
    X Dart plugin not installed; this adds Dart specific functionality.
[√] VS Code (version 1.52.0)
[√] Connected device (1 available)
```

pubsec.yaml:
```
name: example
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  freezed_annotation: ^0.12.0
  json_annotation: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.9
  freezed: ^0.12.5
  json_serializable: ^3.5.1
```

There is no build.yaml

### Additional comments
I have used such pattern before for bloc library with freezed events & states in .part files and everything worked well.
Can't tell for sure from wich version something goes wrong, but checked for 1.10.2 also.
