### ISSUE TITLE
Bad state: Unable to generate package graph

### ISSUE THREAD

**Issue by DevHachi** [dart-lang/build#2953]
` flutter pub run build_runner build`

```
Unhandled exception:
Bad state: Unable to generate package graph, no `/Users/patrickhausa/Documents/01 Projekte/Mobile/Flutter/movecat_nfc/.dart_tool/flutter_gen/pubspec.yaml` found.
     _pubspecForPath (package:build_runner_core/src/package_graph/package_graph.dart:235:5)
     _parsePackageDependencies (package:build_runner_core/src/package_graph/package_graph.dart:208:21)
      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:97:33)
<asynchronous suspension>
     PackageGraph.forThisPackage (package:build_runner_core/src/package_graph/package_graph.dart:110:20)
      main (file:///Users/patrickhausa/flutter/.pub-cache/hosted/pub.dartlang.org/build_runner-1.10.10/bin/build_runner.dart:27:49)
      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:299:32)
      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:168:12)
pub finished with exit code 255
```

Here is the pubspec.yaml in the root directory.

```
name: movecat_nfc
description: Demo project for NFC function test.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Internationalization support.
  flutter_localizations:
    sdk: flutter
  cupertino_icons:
  convert:
  nfc_manager:
  json_annotation:
  path_provider:
  intl:
  permission_handler:
  qrscan:
  flutter_search_bar:
  floor:

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:
  json_serializable:
flutter:
  generate: true
  uses-material-design: true
flutter_intl:
  enabled: true
```
When only the l10n and json was there everything works but as soon as floor_generator was added this error occured and I can't use the internationalizations anymore, no matter what I do.

Flutter Version: 1.22.5
Dart: 2.10.4
Build Runner: 1.10.10
