### ISSUE TITLE
How to know if files were correctly excluded in build

### ISSUE THREAD

**Issue by serendipity1004** [dart-lang/build#2989]
I have a build.yaml looking like below

```
targets:
  $default:
    sources:
      exclude:
        - **/*.example.jpg
        - **/*.example.png
```

and I haven't really changed anything on pubspec.yaml.

I would like to exclude all the files that have extensions of example.jpg and example.png when I build flutter app for both android and ios.

is the yaml setting above correct?

Do I have to include anything in pubspec.yaml as well?

If it is correct, how do I know/check if the files were correctly excluded?
