### ISSUE TITLE
Error running build_runner after upgrade Flutter to 2.0

### ISSUE THREAD

**Issue by BenjaminFarquhar** [dart-lang/build#3027]
Hi there,

When running `flutter pub run build_runner watch --delete-conflicting-outputs`, it is now giving me an error ever since I upgraded to Flutter 2.0. I'm using freezed with json_serializble for build tasks. I wonder if this is an issue with build_runner because everything else about my app still works. Apologies if it is not an issue with build_runner. Any help much appreciated.

* Dart SDK Version: 2.12.0
* build_runner: ^1.11.5
* MacOSX

The error:

```
The pubspec.lock file has changed since the .dart_tool/package_config.json file was generated, please run "pub get" again.
pub finished with exit code 65
```
My pubspec.yaml:

```
name: vepo
description: The Vepo mobile app.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  animate_do: ^1.7.5
  cloud_firestore: ^0.14.1+3
  dio: ^3.0.10
  enum_to_string: ^1.0.14
  firebase_analytics: ^6.0.2
  firebase_auth: ^0.18.1+2
  firebase_core: ^0.5.0+1
  flash: ^1.3.2
  flutter:
    sdk: flutter
  flutter_hooks: ^0.15.0
  flutter_icons: ^1.1.0
  flutter_launcher_icons: ^0.8.1
  flutter_native_splash: ^0.3.0
  flutter_riverpod: ^0.12.4
  flutter_typeahead: ^2.0.0
  font_awesome_flutter: ^8.11.0
  freezed: ^0.12.7
  freezed_annotation: ^0.12.0
  google_fonts: ^1.1.2
  google_maps_webservice: ^0.0.19
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  hive_generator: ^0.8.2
  hooks_riverpod: ^0.12.4
  image_cropper: ^1.3.1
  image_picker: ^0.6.7+22
  json_annotation: ^3.1.1
  json_serializable: ^3.5.1
  keyboard_avoider: ^0.1.2
  logger: ^0.9.4
  popup_menu: ^1.0.5
  reactive_forms: ^9.0.2
  rxdart: ^0.25.0
  smooth_page_indicator: ^0.2.0
  uuid: ^2.2.2

dependency_overrides:
  font_awesome_flutter:
    path: /Users/benjaminfarquhar/dev/font_awesome_flutter-master

dev_dependencies:
  build_runner: ^1.11.5
  faker: ^1.3.0
  firebase_auth_mocks: ^0.3.2
  flutter_driver:
    sdk: flutter
  flutter_gen: ^1.3.1
  flutter_test_ui: ^1.0.0
  integration_test: ^1.0.2+2
  mockito: ^4.1.4
  pedantic: ^1.9.2
  test: ^1.15.7

flutter:
  uses-material-design: true
  fonts:
    - family: VarelaRound
      fonts:
        - asset: assets/fonts/VarelaRound-Regular.ttf
    - family: Hind
      fonts:
        - asset: assets/fonts/Hind-Medium.ttf
  assets:
    - assets/images/

flutter_gen:
  output: lib/

flutter_icons:
  image_path: "assets/images/launcher_icon_ios.webp"
  android: false
  ios: true

flutter_native_splash:
  image: assets/images/splash_screen.png
  color: "#22F2A6"

```
