### ISSUE TITLE
Multi package aggregate builder

### ISSUE THREAD

**Issue by leisim** [dart-lang/build#3072]
I'm trying to create two builders. The first one (`myanalyzer`) should analyze all classes with a specific annotation and output a `*.info.json` file to the cache. Also classes in dependencies. The second builder (`mygenerator`) should aggregate all `*.info.json` files to a single `result.g.dart` file in the root package.

I tried several things but didn't find a working solution. The `mygenerator` builder does not find info files in dependencies and the `myanalyzer` builder gets a `UnexpectedOutputException` if it tries to write info files into the root package.

Do you have an idea how this can be implemented?

```yaml
myanalyzer:
  import: "package:my_package/generator.dart"
  builder_factories: ["getMyAnalyzer"]
  build_extensions: {'.dart': ['.info.json']}
  auto_apply: all_packages
  build_to: cache

mygenerator:
  import: "package:my_package/generator.dart"
  builder_factories: ["getCodeGenerator"]
  build_extensions:
    "$lib$": ["result.g.dart"]
    "$test": ["result.g.dart"]
  required_inputs: ['.info.json']
  auto_apply: all_packages
  build_to: source
```

* Dart SDK Version 2.12.0
* `build_runner`: 1.12.0
