### ISSUE TITLE
A library can't opt out of null safety by default, when using sound null safety.

### ISSUE THREAD

**Issue by jumperchen** [dart-lang/build#3078]
**Dart version**: 2.12.3

We follow [the guide](https://dart.dev/null-safety/unsound-null-safety#migrating-by-hand) to upgrade the Dart SDK to sound null safety, and disable some old version files with `// @dart = 2.10`. When running with `build_runner` as follows:
```dart --no-sound-null-safety run build_runner serve web:1234 --output=web:build/web --no-release```
The `--no-sound-null-safety` flag seems not to pass to `compiler: dart2js` with `dart2js_args` arguments in `build.yaml`, which contains some DDC and D2J output files.

Here is a pseudo `build.yaml` file like:
```yaml
global_options:
  build_web_compilers|entrypoint:
    options:
      # List any dart2js specific args here, or omit it.
      dart2js_args:
        - --minify
        - -O4

targets:
  $default:
    sources:
      include:
        - lib/**
        - web/foo/**
        - $package$
    builders:
      build_web_compilers:entrypoint:
        enabled: false
      build_web_compilers|dart_source_cleanup:
        enabled: true
        release_options:
          enabled: false
  main:
    auto_apply_builders: false
    sources:
      include:
        - web/foo/**
      exclude:
        - web/foo/worker/**
    dependencies:
      - $default
    builders:
      build_web_compilers|entrypoint:
        enabled: true
        generate_for:
          - web/foo/**.dart
        options:
          dart2js_args:
            - --fast-startup
  worker:
    auto_apply_builders: true
    sources:
      - web/foo/worker/**
    dependencies:
      - $default
    builders:
      build_web_compilers|entrypoint:
        enabled: true
        generate_for:
          - web/foo/worker/**.dart
        options:
          compiler: dart2js
``` 

The error is caused by `web/foo/worker/import_worker.dart` file

The error stack trace:
```
[SEVERE] build_web_compilers:entrypoint on web/foo/worker/import_worker.dart (cached):
ExitCode:1
StdOut:
org-dartlang-app:///packages/foo/src/js/js_map.dart@138+15:
Error: A library can't opt out of null safety by default, when using sound null safety.
....
Error: A library can't opt out of null safety by default, when using sound null safety.
....
```
