### ISSUE TITLE
Generating files on github actions yields Null check operator used on a null value error (works locally)

### ISSUE THREAD

**Issue by moseskarunia** [dart-lang/build#3125]
## Script which yields the error

```
flutter pub run build_runner build --delete-conflicting-outputs
```

Confusingly the error only happened on github action CI and not local, even though I use the exact same script on both local and remote.

## Error Log

<details>
  <summary>Log</summary>
  
  ```
  Run flutter pub run build_runner build --delete-conflicting-outputs
  flutter pub run build_runner build --delete-conflicting-outputs
  shell: /usr/bin/bash -e {0}
  env:
    FLUTTER_ROOT: /opt/hostedtoolcache/flutter/2.0.6-stable/x64
    PUB_CACHE: /opt/hostedtoolcache/flutter/2.0.6-stable/x64/.pub-cache

  Unhandled exception:
  Null check operator used on a null value
  #0      PackageGraph.forPath.<anonymous closure> (package:build_runner_core/src/package_graph/package_graph.dart:106:72)
  #1      MappedListIterable.elementAt (dart:_internal/iterable.dart:411:31)
  #2      ListIterator.moveNext (dart:_internal/iterable.dart:340:26)
  #3      List.addAll (dart:core-patch/growable_array.dart:308:13)
  #4      PackageGraph.forPath (package:build_runner_core/src/package_graph/package_graph.dart:106:12)
  <asynchronous suspension>
  #5      main (file:///opt/hostedtoolcache/flutter/2.0.6-stable/x64/.pub-cache/hosted/pub.dartlang.org/build_runner-2.0.4/bin/build_runner.dart:27:30)
  <asynchronous suspension>
  pub finished with exit code 255
  Error: Process completed with exit code 255.
  ```
</details>

## Github action

<details>
  <summary>Github action.yaml</summary>

  ```
  name: horeekaa-core
  
  on:
    push:
      branches: [master]
      paths:
        - ".github/workflows/horeekaa-core.yaml"
        - "horeekaa_core/**"
    pull_request:
      branches: [master, epic-**, init-**-epic-**]
      paths:
        - ".github/workflows/horeekaa-core.yaml"
        - "horeekaa_core/**"
  
  jobs:
    build:
      defaults:
        run:
          working-directory: horeekaa_core
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - uses: subosito/flutter-action@v1
          with:
            flutter-version: '2.0.6'
        - name: Copy Assets
          run: cp -R ../assets assets
        - name: Install dependencies
          run: flutter pub get
        - name: Generate files
          run: flutter pub run build_runner build --delete-conflicting-outputs
        - name: Format
          run: flutter format --set-exit-if-changed lib test
        - name: Analyze project source
          run: flutter analyze lib test
        - name: Test
          run: flutter test --coverage
        - name: Activate remove_from_coverage
          run: pub global activate remove_from_coverage
        - name: Remove autogenerated codes from coverage report
          run: pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.config.dart$' && pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.g.dart$' && pub global run remove_from_coverage:remove_from_coverage -f coverage/lcov.info -r '.freezed.dart$'
        - name: Report code coverage
          uses: zgosalvez/github-actions-report-lcov@v1.3.0
          with:
            working-directory: horeekaa_core
            coverage-files: horeekaa_core/coverage/lcov.info
            minimum-coverage: 95
            artifact-name: code-coverage-report
            github-token: ${{ secrets.GITHUB_TOKEN }}

  ```
</details>

To give some perspective, here's my folder structure:

<details>
  <summary>Folder structure</summary>
<img width="346" alt="Screen Shot 2021-06-11 at 18 45 28" src="https://user-images.githubusercontent.com/19493989/121681607-3b87a900-cae5-11eb-8385-bc5b6ace821d.png">
</details>

## My pubspec.yaml

<details>
  <summary>pubspec.yaml</summary>
  
  ```yaml
  name: horeekaa_core
  description: A flutter library containing core horeekaa codes
  version: 0.16.0
  
  environment:
    sdk: '>=2.12.0 <3.0.0'
    flutter: 2.0.6
  
  dependencies:
    flutter:
      sdk: flutter
    built_value: 8.0.6
    clock: 1.1.0
    copy_with_extension: 2.0.0-nullsafety.1
    cornerstone: 2.0.0-nullsafety.10
    dartz: 0.10.0-nullsafety.1
    dotted_border: 2.0.0-nullsafety.0
    equatable: 2.0.0
    firebase_auth: 1.0.2
    firebase_core: 1.3.0
    firebase_crashlytics: 2.0.0
    firebase_dynamic_links: 2.0.0-dev.1
    firebase_messaging: 10.0.2
    flutter_bloc: 7.0.0
    flutter_cafe: 0.0.2-dev.5
    flutter_i18n: 0.22.3
    freezed: 0.14.2
    get_it: 7.1.3
    google_fonts: 2.0.0
    google_sign_in: 5.0.1
    graphql_flutter: 5.0.0-nullsafety.2
    hive: 2.0.0
    hive_flutter: 1.0.0
    image_picker: 0.7.4
    injectable: 1.4.0
    intl: 0.17.0
    json_annotation: 4.0.1
    linked_scroll_controller: 0.2.0-nullsafety.0
    material_design_icons_flutter: 5.0.5955-rc.1
    meta: 1.3.0
    package_info: 2.0.0
  
  dev_dependencies:
    flutter_test:
      sdk: flutter
    bloc_test: 8.0.0
    build_runner: 2.0.4
    flutter_launcher_icons: 0.9.0
    injectable_generator: 1.4.0
    json_serializable: 4.1.2
    mocktail: 0.1.0
  
  flutter: null

  ```
</details>
