### ISSUE TITLE
 .json_serializable.g.part  from .dart which is not specified in the `build.yaml`

### ISSUE THREAD

**Issue by salman731** [dart-lang/build#3132]
Builder json_serializable:json_serializable outputs .json_serializable.g.part  from .dart which is not specified in the `build.yaml`

* Dart SDK version: 2.12.3
* build_runner 1.11.1
* Windows 10

I am trying to generate json_serialization and moor_generator code with following build.yaml

```
targets:
  run_moor:
    auto_apply_builders: false
    builders:
      moor_generator|preparing_builder:
        enabled: true
      moor_generator:
        enabled: true
      source_gen|combining_builder:
        enabled: true
        generate_for:
          - lib/Database/Tables/**
  $default:
    dependencies: [ ':run_moor' ]
    builders:
      moor_generator|preparing_builder:
        enabled: false
      moor_generator:
        enabled: false
```
