### ISSUE TITLE
How to use kiwi_generator 3.0.0 with this ? I get error after upgrade

### ISSUE THREAD

**Issue by kristijorgji** [dart-lang/build#3135]
`Dart SDK version: 2.13.1 (stable) (Fri May 21 12:45:36 2021 +0200) on "macos_x64"`
`Flutter 2.2.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision d79295af24 (11 days ago) • 2021-06-11 08:56:01 -0700
Engine • revision 91c9fc8fe0
Tools • Dart 2.13.3`

Using build_runner version: "2.0.4"

build.yml content:
```
targets:
  $default:
    builders:
      kiwi:

```

Running same script as before upgrade to new version is giving:

`flutter packages pub run build_runner build`
```
If you believe you have gotten this message in error, especially if using a new
feature, you may need to run `pub run build_runner clean` and then rebuild.

Invalid argument(s): line 4, column 7 of build.yaml: Unsupported value for "builders". Must not be null
  ╷
4 │       kiwi:
  │       ^^^^^
```

**Comment by jakemac53** [comment]
What are you trying to do accomplish with your config? What you have now isn't actually configuring anything, there needs to be something passed (which is why it is complaining about a `null`) value there.

**Comment by kristijorgji** [comment]
As mentioned, this is old configuration that worked fine before upgrade. I did not update any config

**Comment by jakemac53** [comment]
Again I would need to understand what the previous config was trying to achieve.... it isn't valid config. You could possibly just delete the whole `build.yaml` file?

**Comment by kristijorgji** [comment]
I don't know what was trying to achive, was documented in `kiwi_generator` and without it kiwi was not running.
It was working totally fine generating `injector.g` file for kiwi di container.

Now after upgrade does not work anymore, so the kiwi_geneartor builder is not called.

I am trying to create some config for the builder but without success. No idea what to fill those values with extension and factories

```
targets:
  $default:
    builders:
      build_runner:kiwi:
        enabled: true

builders:
  kiwi:
    import: "package:kiwi_generator/kiwi_generator.dart"
    builder_factories:
    build_extensions:

```

**Comment by kristijorgji** [comment]
I deleted `build.yaml` and runned 

```flutter packages pub run build_runner build```

and now it executed the generator worked...

So steps here were wrong in the 3rd party package saying to create that build.yaml....
![Screenshot 2021-06-22 at 17 27 27](https://user-images.githubusercontent.com/15630854/122953766-2e897600-d37f-11eb-806a-88f0630035f0.png)


https://pub.dev/packages/kiwi_generator

**Comment by jakemac53** [comment]
> How can i list available builders that are recognised automaticaly

You can use the `auto_apply_builders` option to disable this, and then explicitly list and enable the builders you want. Note that if  the `kiwi` builder requires some other builders to run, doing this may break it.

```
targets:
  $default:
    auto_apply_builders: false
    builders:
      build_runner:kiwi:
        enabled: true
```
