### ISSUE TITLE
build_runner fails on Windows with dependencies using git and path

### ISSUE THREAD

**Issue by technolion** [dart-lang/build#3137]
When using a dependency like this:

```
  menubar:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/menubar
```

build_runner fails parsing the path correctly **on Windows**:

```
dart run build_runner build
Could not find a file named "pubspec.yaml" in "C:\Users\tom\AppData\Local\Pub\Cache\git\flutter-desktop-embedding-e48abe7c3e9ebfe0b81622167c5201d4e783bb81\plugins%5Cmenubar".
```

As one can see from the error, it looks like the `path` parameter of the `git` dependency leads to an encoded backslash (%5C) which somehow messes up build_runner.

The above way to add a dependency via git is an officially supported syntax:
https://dart.dev/tools/pub/dependencies

* Dart SDK version: 2.14.0-188.5.beta (beta) (Thu Jun 24 15:29:20 2021 +0200) on "windows_x64"
* build_runner version 2.0.5
* Windows 10 operating system
