### ISSUE TITLE
Rename or generate files with different extension

### ISSUE THREAD

**Issue by markokosticdev** [dart-lang/build#3176]
OS: MacOS
Browser: Chrome
Dart:  2.13.4
build_runner: 2.1.1 

I am unable to rename or generate files with a different extension.
Is there plugin or some other way to do it?
Is it a generalized way or not?

I am using **injectable_generator**, **auto_route_generator** and **json_serializable**.

build.yaml
```
builders:
  auto_route_generator:
    import: "package:auto_route_generator/builder.dart"
    builder_factories: [ "autoRouteGenerator" ]
    build_extensions: {".dart": [".my_package.dart"]}
```
