### ISSUE TITLE
build_runner throws errors when executed on libraries importing Flutter

### ISSUE THREAD

**Issue by JensHor** [dart-lang/build#3188]
I am using `build_runner` within a package which requires the flutter SDK. However, running `build_runner` throws error messages indicating that flutter types and properties are not correctly understood.

For instance I see the following error message: 

> ../../flutter/packages/flutter/lib/src/material/about.dart:1654:86: Error: Getter not found: 'Radius'.
>               borderRadius: BorderRadius.vertical(top: Radius.circular(3.0), bottom: Radius.zero),

For the whole error log see the the file below:
[log.txt](https://github.com/dart-lang/build/files/7143415/log.txt)

I am assuming that running `build_runner` within packages that contain flutter dependencies is not working properly. But i did not find any documentation regarding these error messages. Am I doing something wrong? Is it possible to solve this problem?

### Flutter SDK Version: 

> Flutter 2.5.0 • channel stable • https://github.com/flutter/flutter.git
> Framework • revision 4cc385b4b8 (2 days ago) • 2021-09-07 23:01:49 -0700
> Engine • revision f0826da7ef
> Tools • Dart 2.14.0

### Dart SDK Version:

> Dart SDK version: 2.14.0 (stable) (Mon Sep 6 13:47:59 2021 +0200) on "macos_x64"

### Packages I am using

I checked in the `pubspec.lock` file and the versions from the `pubspec.yaml` and `.lock` file match. 

```
environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  analyzer: ^2.2.0
  build: ^2.1.0
  flutter:
    sdk: flutter
  source_gen: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
```

### What builders are you using
Here is a minimal example of the code I am using.
**build.yaml**

```
builders:
  annotation_builder:
    import: 'package:build_runner_flutter/main.dart'
    builder_factories: ['testBuilder']
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: dependents
    build_to: cache
```

**main.dart**

```
import 'package:analyzer/dart/element/element.dart' as analyzer;
import 'package:build/build.dart' as build;
import 'package:flutter/material.dart';
import 'package:source_gen/source_gen.dart';

// Define the builder
build.Builder testBuilder(build.BuilderOptions options) {
  return PartBuilder([
    TestGenerator(),
  ], '.g.dart');
}

// An annotation
class CustomAnnotation {
  final Widget widget;
  const CustomAnnotation({required this.widget});
}

@CustomAnnotation(widget: CustomWidget())
class CustomWidget extends StatelessWidget {
  const CustomWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Container();
  }
}

class TestGenerator extends GeneratorForAnnotation<CustomAnnotation> {
  @override
  String generateForAnnotatedElement(analyzer.Element element,
      ConstantReader annotation, build.BuildStep buildStep) {
    if (element is analyzer.ClassElement) {
      print('Read one!');
    }

    return '';
  }
}
```

**pubspec.yaml**

```
name: build_runner_flutter
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:

  analyzer: ^2.2.0
  build: ^2.1.0
  flutter:
    sdk: flutter
  source_gen: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
```

**CMD**

I run the following commands:

> flutter pub get
> flutter pub run build_runner build

### Operating System:

> **MacOS** Big Sur 11.4 on M1 MacMini

Let me know if you need more information. Thanks in advance 😊
