### ISSUE TITLE
Key 'my_task' is duplicated

### ISSUE THREAD

**Issue by cloneconf** [dart-lang/build#3230]
* Dart SDK Version (`dart --version`)

Dart SDK version: 2.14.4 (stable) (Wed Oct 13 11:11:32 2021 +0200) on "linux_x64"

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)

build_runner: ^2.1.7

* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.

I am using these builders:

- ferry_generator|req_builder
- gql_build|serializer_builder
- gql_build|data_builder
- gql_build|ast_builder
- gql_build|schema_builder

* Whether you are using Windows, MacOSX, or Linux (if applicable)

Linux XUbuntu

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)

Firefox and brave.

----

I am trying to generated multiple schemas for my app using `ferry`, but when I try to add new builder it says `Key 'ferry_generator' is duplicated `...

![Screenshot_2021-12-25_03-31-15](https://user-images.githubusercontent.com/88058138/147376146-a6188cce-4a3e-4ba5-a854-1ebbb6bdf73f.png)

Best Regars.

**Comment by natebosch** [comment]
You cannot have the same builder run multiple times on the same input with different configuration.

There used to be no sensible behavior for such a builder because the outputs would necessarily always conflict. Now that a builder can vary it's outputs based on configuration I wonder if that could be relaxed.

What is the use case? What inputs are you targeting with these builders?

**Comment by cloneconf** [comment]
> You cannot have the same builder run multiple times on the same input with different configuration.

Actually, i tried this ...
```
ferry_generator|req_builder:
	...
ferry_generator:req_builder
	...
```

And it seems to fool the build system 😄 

You can check <a href="https://github.com/gql-dart/ferry/issues/315#issuecomment-1001018068">this issue</a> out, that i opened on ferry repo.


> What is the use case? What inputs are you targeting with these builders? 

As i said, i want to be able to use the same builder (which is `ferry_generator` in this case) to be executed multiple times on different parts of the app/package.

**Comment by natebosch** [comment]
> The input are these two `schema.graphql` files.
> 
> They are both different.

In that case you might be able to split your package into multiple targets and have a different file in each target.
https://github.com/dart-lang/build/blob/master/build_config/README.md#dividing-a-package-into-build-targets

**Comment by cloneconf** [comment]
I tried to use multiple targets:
<details>
<summary>build.yaml</summary>

```yaml
targets:


  # Graphql schema for api 1
  $default:
    builders:


      gql_build|schema_builder:
        generate_for:
          - lib/graphql/api1/*
        enabled: true


      gql_build|ast_builder:
        generate_for:
          - lib/graphql/api1/*
        enabled: true


      gql_build|data_builder:
        generate_for:
          - lib/graphql/api1/*
        enabled: true
        options:
          schema: dart_application_1|lib/graphql/api1/schema.graphql


      gql_build|var_builder:
        generate_for:
          - lib/graphql/api1/*
        enabled: true
        options:
          schema: dart_application_1|lib/graphql/api1/schema.graphql


      gql_build|serializer_builder:
        generate_for:
          - lib/graphql/api1/*
        enabled: true
        options:
          schema: dart_application_1|lib/graphql/api1/schema.graphql

          
      ferry_generator|req_builder:
        generate_for:
          - lib/graphql/api1/*
        enabled: true
        options:
          schema: dart_application_1|lib/graphql/api1/schema.graphql
      


  # Graphql schema for api 2
  schema_api2:
    builders:


      gql_build|schema_builder:
        generate_for:
          - lib/graphql/api2/*
        enabled: true


      gql_build|ast_builder:
        generate_for:
          - lib/graphql/api2/*
        enabled: true


      gql_build|data_builder:
        generate_for:
          - lib/graphql/api2/*
        enabled: true
        options:
          schema: dart_application_1|lib/graphql/api2/schema.graphql


      gql_build|var_builder:
        generate_for:
          - lib/graphql/api2/*
        enabled: true
        options:
          schema: dart_application_1|lib/graphql/api2/schema.graphql


      gql_build|serializer_builder:
        generate_for:
          - lib/graphql/api2/*
        enabled: true
        options:
          schema: dart_application_1|lib/graphql/api2/schema.graphql


      ferry_generator|req_builder:
        generate_for:
          - lib/graphql/api2/*
        enabled: true
        options:
          schema: dart_application_1|lib/graphql/api2/schema.graphql
```
</details>

Though i got this error:
```
[INFO] Generating build script completed, took 304ms
[WARNING] Invalidated precompiled build script due to missing asset graph.
[INFO] Precompiling build script... completed, took 680ms
[SEVERE] Conflicting outputs
Both built_value_generator:built_value and built_value_generator:built_value may output bin/dart_application_1.built_value.g.part. Potential outputs must be unique across all builders. See https://github.com/dart-lang/build/blob/master/docs/faq.md#why-do-builders-need-unique-outputs
```

___

I tried to override them.. and it did actually work! :partying_face: 

Thanks you very much @natebosch !

the testing repo is here: [multiple_graphql_ferry](https://github.com/cloneconf/multiple_graphql_ferry)

https://user-images.githubusercontent.com/88058138/147610390-9c3ea4b8-a45b-4b93-b7fd-c99e6803c515.mp4


```yaml
targets:

  # schema for api 1
  $default:
    builders:
      gql_build|schema_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
      gql_build|ast_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
      gql_build|data_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api1/schema.graphql
      gql_build|var_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api1/schema.graphql
      gql_build|serializer_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api1/schema.graphql
      ferry_generator|req_builder:
        generate_for:
          - lib/graphql/api1/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api1/schema.graphql

      # override
      gql_build:schema_builder:
        generate_for:
          - lib/graphql/api1/**
      built_value_generator:built_value:
        generate_for:
          - lib/graphql/api1/**
      source_gen:combining_builder:
        generate_for:
          - lib/graphql/api1/**




  # schema for api 2
  schema_api_two:
    builders:
      gql_build|schema_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
      gql_build|ast_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
      gql_build|data_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api2/schema.graphql
      gql_build|var_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api2/schema.graphql
      gql_build|serializer_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api2/schema.graphql
      ferry_generator|req_builder:
        generate_for:
          - lib/graphql/api2/**
        enabled: true
        options:
          schema: multiple_graphql_ferry|lib/graphql/api2/schema.graphql
        
      
      # override
      gql_build:schema_builder:
        generate_for:
          - lib/graphql/api2/**
      built_value_generator:built_value:
        generate_for:
          - lib/graphql/api2/**
      source_gen:combining_builder:
        generate_for:
          - lib/graphql/api2/**
```

you may close the issue now ;)
