### ISSUE TITLE
`InvalidOutputException` when combing dart2js and dartdevc builders

### ISSUE THREAD

**Issue by simolus3** [dart-lang/build#3275]
I have a web application that I want to compile with `dartdevc` during development and with `dartj2s` for release builds. This web application also uses a web worker, which I always want to compile with `dart2js`.

I'm using the attached build configuration for this, but this causes duplicate outputs when extracting the dart2js archive:

```
[INFO] build_web_compilers:entrypoint on web/worker.dart:Compiled 9,487,497 characters Dart to 12,095 characters JavaScript in 0.41 seconds
Dart file org-dartlang-app:///web/worker.dart compiled to JavaScript: web/worker.dart.js


[SEVERE] Instance of 'Dart2JsArchiveExtractor' on example|web/worker.dart.js.tar.gz:

InvalidOutputException: example|web/worker.dart.js.deps
Asset already exists
[INFO] Running build completed, took 6.4s
```

To reproduce:

1. `dart create -t web-simple example`
2. `echo "void main() {}" > example/web/worker.dart`
3. Use the following build configuration, then run `dart run build_runner serve`

```yaml
targets:
  # We use dartdevc by default, but the worker should always be compiled with dart2js
  worker:
    auto_apply_builders: false
    dependencies: [":$default"]
    builders:
      build_web_compilers|entrypoint:
        enabled: true
        generate_for:
         - web/worker.dart
        options:
          compiler: dart2js

  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          # This one is compiled in the other target
          exclude:
            - "web/worker.dart"
```

**Comment by jakemac53** [comment]
It looks like post process builders are applying to all targets, and regardless of the `auto_apply_builders` setting.

The following does fix things, but there is probably a bug to fix here:

```yaml
targets:
  dart2js_archives:
    auto_apply_builders: false
    dependencies: [":$default", ":worker"]
    builders:
      build_web_compilers|dart2js_archive_extractor:
        enabled: true

  # We use dartdevc by default, but the worker should always be compiled with dart2js
  worker:
    auto_apply_builders: false
    dependencies: [":$default"]
    builders:
      build_web_compilers|dart2js_archive_extractor:
        enabled: false
      build_web_compilers|entrypoint:
        enabled: true
        generate_for:
         - web/worker.dart
        options:
          compiler: dart2js

  $default:
    builders:
      build_web_compilers|entrypoint:
        generate_for:
          # This one is compiled in the other target
          exclude:
            - "web/worker.dart"
      build_web_compilers|dart2js_archive_extractor:
        enabled: false
```
