### ISSUE TITLE
[Question] how to create a single builder, with single input and single output?

### ISSUE THREAD

**Issue by matanshukry** [dart-lang/build#3280]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`)
`Dart SDK version: 2.16.2 (stable) (Tue Mar 22 13:15:13 2022 +0100) on "windows_x64"`

* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  * _If you are not sure, try checking your `pubspec.lock` file._
a. `build_config`: "1.0.0"
b. `build`: "2.2.1"
  
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
LibraryBuilder. create a single file that is based on a single .json file

* Whether you are using Windows, MacOSX, or Linux (if applicable)
* Windows

* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
Chrome

* Any other packages or constraints we should know about
I'm using `source_gen`, `^1.2.1`.

Missing some or all of the above might make the issue take longer or be impossible to act on.

-----

I'm trying to create a single builder.
The input is a specific .json file in a specific directory, e.g. "mydir/myinput.json".
The output is a single dart file, e.g. "myoutput.dart".

I tried various options in build.yaml file, but all of them seems to result in my builder running once per .dart file in the running package.
e.g.
```
targets:
  $default:
    sources:
#      include:
#        - mydir/myinput.json
    builders:
      easy_config:
        enabled: true
        generate_for:
          include:
            - mydir/myinput.json

builders:
  easy_config:
    import: "package:my_builder/my_builder.dart"
    builder_factories: [ "easyMyBuilder" ]
    build_extensions  : { 'myinput.json': [ "myoutput.dart" ] }
    #    build_extensions: { ".dart": [ ".dart" ] }
    #      r'$lib$': ['exports.dart']
    build_to: source
    auto_apply: root_package
#    auto_apply: dependents
```
