### ISSUE TITLE
Cannot scan annotations for packages that the project depends on

### ISSUE THREAD

**Issue by arcticfox1919** [dart-lang/build#3292]
```
❯ dart --version
Dart SDK version: 2.15.1 (stable) (Tue Dec 14 13:32:21 2021 +0100) on "macos_x64"
```

```
build_runner: ^2.1.10
```
build.yaml
```
targets:
  $default:
    builders:
      test_generator:test_generator:
        enabled: true
        generate_for:
          include:
            - lib/**.dart
            - ../modul/**.dart

builders:
  test_generator:
    target: ":test_generator"
    import: "package:test_generator/generators.dart"
    builder_factories: ["generateTable"]
    build_extensions: { ".dart": [".g.dart"] }
    auto_apply: root_package
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
```

How can I configure it to scan annotations in packages that the project depends on? I set the generate_for => include attribute, but it doesn't work. If the annotations in the packages that the project depends on can be scanned, it will help to modules are split into different Dart packages.

**Comment by jakemac53** [comment]
Can you describe what you are trying to achieve?

In general modules in one package cannot contain files from other packages, which it looks like is what you are trying to do (by `../modul/**.dart`). There is probably a different solution to what you want to do but I would need to understand the use case.

**Comment by jakemac53** [comment]
@arcticfox1919 The way to control which packages a builder applies to, you use the `auto_apply` configuration of the builder.

You could have it apply to all packages with the `all_packages` value, but ideally you would add a dependency from the `modul` package on your builder if possible and then use the `dependents`.

**Comment by arcticfox1919** [comment]
`all_packages` doesn't seem to work.

Here is an example :

**generate_usage**

pubspec.yaml

```yaml
name: generate_usage
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  generate_demo:
    path: ../generate_demo/
  modul:
    path: ../modul/

dev_dependencies:
  build_runner: ^2.0.0
  lints: ^1.0.0
```

build.yaml

```yaml
# Read about `build.yaml` at https://pub.dev/packages/build_config
targets:
  $default:
    builders:
      # Configure the builder `pkg_name|builder_name`
      generate_demo|info:
        generate_for:
          - bin/usage.dart
      source_gen|combining_builder:
        options:
          ignore_for_file:
            - lint_a
            - lint_b
```

usage.dart

```dart
import 'package:generate_demo/annotations.dart';


@Info('bar')
class Foo{
  int? _id;
}
```

------

**generate_demo**

pubspec.yaml

```yaml
name: generate_demo
description: A simple package.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.3 <3.0.0'

dependencies:
  build: ^2.3.0
  source_gen: ^1.2.2
  code_builder: ^4.1.0


dev_dependencies:
  lints: ^1.0.0
```

build.yaml

```yaml
# Read about `build.yaml` at https://pub.dev/packages/build_config
builders:
  # name of the builder
  info:
    import: "package:generate_demo/builder.dart"
    builder_factories: ["generateInfo"]
    build_extensions: {".dart": [".info.dart"]}
    auto_apply: all_packages
    build_to: source

```

-----
