### ISSUE TITLE
"[SEVERE]  type 'YamlList' is not a subtype of type 'List<String>' in type cast" when overriding builder options

### ISSUE THREAD

**Issue by wujek-srujek** [dart-lang/build#3300]
I have a builder defined like this:
```yaml
builders:
  my_builder:
    import: my_package:my_builder/builder.dart
    builder_factories:
      - myBuilder
    build_extensions:
      $package$:
        - lib/generated/my_file.dart
    auto_apply: dependents
    build_to: source
    defaults:
      options:
        dirs:
          - dir_1
```
and then in a different project I use this bilder and overwrite its options to be:
```yaml
targets:
  $default:
    builders:
      my_package:my_builder:
        options:
          dirs:
            - dir_a
```
The builder factory is like this:
```dart
Builder myuilder(BuilderOptions options) {
  return MyBuilder(options.config['dirs']! as List<String>);
}
```
It works when I don't override the `dirs` configuration in a target, but when I do I get
```
SEVERE] 
type 'YamlList' is not a subtype of type 'List<String>' in type cast
```
When I debug the factory it the value really is a `YamlList`.

Is this expected? Why does it behave differently with and without the options being overridden in a dependent package?

**Comment by jakemac53** [comment]
This looks expected to me, we are parsing things as yaml, which allows for values other than strings in lists. It isn't safe to cast this to a `List<String>` here, you need to either `.cast<String>()` or create a new list (using `List.from` etc).

I don't know why this would work when you aren't overriding it, unless the builder was not applied at all? I would expect the same thing to happen with the default options.

**Comment by wujek-srujek** [comment]
It was auto applied and I can debug both situation and without the options being overwritten I get a List<String> hence the cast was working; when I overwrite the options I get a YamlList instead. Yeah, I changed the code to be
```dart
(options.config['asset_dirs']! as List<dynamic>).cast<String>()
```
and it works in both cases. But the change in behavior is pretty strange.

**Comment by natebosch** [comment]
I'm very surprised you'd ever get a `List<String>` where that cast would succeed, can you elaborate on the setup to see that behavior?

**Comment by wujek-srujek** [comment]
Sure. Here is the code:
```dart
import 'package:build/build.dart';

class MyBuilder implements Builder {
  final List<String> dirs;

  MyBuilder(this.dirs);

  @override
  final buildExtensions = const {
    r'$package$': ['lib/generated/my_file.dart'],
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    print('$dirs');
  }
}
```
```dart
import 'package:build/build.dart';

import 'src/my_builder.dart';

Builder myBuilder(BuilderOptions options) {
  print(options.config['dirs'].runtimeType); // prints List<String>
  return MyBuilder(
    options.config['dirs']! as List<String>,
  );
}

```
```yaml
builders:
  my_builder:
    import: package:my_package/builder.dart
    builder_factories:
      - myBuilder
    build_extensions:
      $package$:
        - lib/generated/my_file.dart
    auto_apply: root_package
    build_to: source
    defaults:
      options:
        dirs:
          - dir_a

# targets:
#   $default:
#     builders:
#       my_package:my_builder:
#         options:
#           dirs:
#             - dir_a
```
```yaml
name: my_package
version: 1.0.0+1

environment:
  sdk: '>=2.16.2 <3.0.0'

dependencies:
  build: ^2.3.0
  build_config: ^1.0.0
  build_runner: ^2.1.0
```
This works file. Uncomment the `targets` section in `build.yaml` and it results in the error mentioned above. I see `YamlList` in the debugger only when `targets` is active.
