### ISSUE TITLE
generate_for excludes not filtering out assets

### ISSUE THREAD

**Issue by wujek-srujek** [dart-lang/build#3302]
I have a builder whose input is `$package$` and uses `buildStep.findAssets(Glob('assets/**'))` internally to find input files to work on (it is actually more complex but this is the smallest reproducible sample). When applied to dependent packages the `assets` folder contains files and folders that I don't want the builder to consider, e.g. `.DS_Store` files etc. so I defined excludes in the user of the builder:
```yaml
targets:
  $default:
    builders:
      my_package:my_builder:
        generate_for:
          exclude:
            - '**/.DS_Store'
            - assets/fonts/**
```
But this doesn't change anything (the configuration is used, I can see errors/warnings in build_runner output when I use e.g. the wrong builder name. My understanding was that `generate_for` includes and excludes  are able to suppress the amount of files the builder sees.
