### ISSUE TITLE
Question: How can I generate code via annotation including in dependent packages?

### ISSUE THREAD

**Issue by NanoMichael** [dart-lang/build#3339]
I'm following the guide [writing an aggregate builder](https://github.com/dart-lang/build/blob/master/docs/writing_an_aggregate_builder.md) to collect all `dart` files, and it works well except for the files in dependent packages.

In my use case, I want to collect all the classes annotated with my custom annotation including dependent packages and generate a single source file from them.

I have a test project whose structure is:

```
test_gen
├── another_test
├── pubspec.yaml
├── test_gen_generator
```

`test_gen_generator` is the package to read all `dart` files, it just contains a single dart file:

```dart
import 'dart:async';

import 'package:analyzer/dart/element/element.dart';
import 'package:build/build.dart';
import 'package:glob/glob.dart';
import 'package:path/path.dart' as p;
import 'package:source_gen/source_gen.dart';

class ListAllFilesBuilder implements Builder {
  static final _allFilesInLib = Glob('**/**.dart'); // **/**.dart doest not help

  static AssetId _allFileOutput(BuildStep buildStep) {
    return AssetId(
      buildStep.inputId.package,
      p.join('lib', 'all_files.txt'),
    );
  }

  @override
  Map<String, List<String>> get buildExtensions {
    return const {
      r'$lib$': ['all_files.txt'],
    };
  }

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    final files = <String>[];
    await for (final input in buildStep.findAssets(_allFilesInLib)) {
      // TODO: read annotation from library
      final lib = await buildStep.resolver.libraryFor(input);
      final reader = LibraryReader(lib);
      // ------------------------------------------------------
      files.add(input.path);
    }
    final output = _allFileOutput(buildStep);
    return buildStep.writeAsString(output, files.join('\n'));
  }
}

Builder allFilesBuilder(BuilderOptions options) => ListAllFilesBuilder();
```

And its `build.yaml`:

```yaml
builders:
  all_files_builder:
    import: 'package:test_gen_generator/all_files_builder.dart'
    builder_factories: [ 'allFilesBuilder' ]
    build_extensions: { r'$lib$': [ 'all_files.txt' ] }
    auto_apply: dependents
    build_to: source
```

`another_test` is a package to test reading files from it.

And `test_gen`'s `pubspec.yaml`:

```yaml
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  another_test:
    path: another_test

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.2.0
  test_gen_generator:
    path: test_gen_generator
```

Now I can get all the dart files under package `test_gen`, except for the files in `another_test`.

I've searched for solutions but with no luck. Any ideas? Did I miss anything?

----------------------------------

**EDIT**

It really helps to implement an IoC container, especially for modulized projects. Imagine a flutter project which has multiple business modules, I want to generate a 'route map' from all pages annotated with `@Route` including those in the business modules, it could be a problem if we can't read these annotations from the submodules.
