### ISSUE TITLE
How to define an ordering of builders? 

### ISSUE THREAD

**Issue by wurikiji** [dart-lang/build#3345]
I saw [a document here](https://github.com/dart-lang/build/blob/master/build_config/README.md#adjusting-builder-ordering). But it's unclear because there is no example. 

Let's assume that my builders will run through the files, `file1.dart`, `file2.dart`, and `file3.dart`. 
I have two builder entry functions, e.g., `Builder preBuilder(BuilderOptions options) => PartBuilder();` and `Builder mainBuilder(BuilderOptions options) => PartBuilder();`.

I want to ensure that `preBuilder` preruns through the entire three files to generate output files, and then `mainBuilder` runs through the entire three files again. 

In this case, how could I configure the `build.yaml` with `runs_before`? Or should I use `post_process_builders`?

**Comment by jakemac53** [comment]
In the builder config for the `preBuilder`, you should set the `runs_before` configuration to list the builder key for the `mainBuilder`.

So for example (leaving off some of the non-relevant config):

```yaml
builders:
  pre_builder:
    import: "package:my_package/builder.dart"
    builder_factories: ["preBuilder"]
    runs_before: [":main_builder"]
  main_builder:
    import: "package:my_package/builder.dart"
    builder_factories: ["mainBuilder"]
```
