### ISSUE TITLE
[build_runner] Build single target

### ISSUE THREAD

**Issue by Zekfad** [dart-lang/build#3404]
`build.yaml` has capability to create multiple targets for builds, but there's no way (at least, there's no docs for that) to build particular targets ignoring the other, i.e. single target build.

It would be nice to be able to specify targets to build via command line arguments, for example to delay heavy builds until they are actually needed to run. That would be very helpful for developer experience.

* Dart SDK version: 2.19.0-382.0.dev (dev) (Wed Nov 9 05:31:23 2022 -0800) on "windows_x64"
* `build_runner` 2.3.2

**Comment by jakemac53** [comment]
See build filters https://github.com/dart-lang/build/blob/master/docs/partial_builds.md, you should be able to achieve what you want using those.

Targets are a bit weird - and yes we don't have a way to build them directly today. It could maybe be added but it doesn't match their intention.

**Comment by btrautmann** [comment]
@jakemac53 I've been trying to make sense of this for a little bit now and I'm hoping you could offer some clarification. We have an application which depends on several packages that offer builders. Our `build.yaml` looks something like this:

```yaml
targets:
  $default:
    sources:
      exclude:
        - ...
    builders:
      json_serializable:
        options: ...
        generate_for:
          - "**/*.dart"
      freezed:
        options: ...
        generate_for:
          include: 
            - "**/*.cg.dart"
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: features|lib/graphql/schema/schema.graphql
          ...
      ferry_generator|serializer_builder:
        enabled: true
        options:
          schema: features|lib/graphql/schema/schema.graphql
          ...
```
When we run `dart run build_runner build --delete-conflicting-outputs`, all of these builders run, which takes about 7 minutes or so. What we'd love to be able to do is just run our GQL related codegen and _avoid_ running `freezed` and `json_serializable`. The `ferry_generater` build.yaml is defined [like this](https://github.com/gql-dart/ferry/blob/master/packages/ferry_generator/build.yaml) which tells me its inputs (if I'm reading it correctly) are expected to be `*.graphql`. However, if I run the following as a test:

```console
dart run build_runner build \
--build-filter="lib/graphql/schema/schema.graphql"
```
I see a message telling me that X number of files exist on disk already (because I didn't pass `--delete-conflicting-outputs). When I _drop_ the `build-filter` flag, I see the same number X is being targeted. The conflicts (when listed) contain files that the `ferry_generator` builders would not produce, indicating to me that the filter is not having an impact.

Could you help me understand whether the issue is on my end (do I need to adjust my `build.yaml` file or my command?) or on the side of `ferry_generator`? I originally thought that perhaps the issue was that the generator was being overreaching by specifying `sources` value of `lib/**`, but when I changed this to something like `**/*.graphql` locally I got the following:

```console
The package `ferry_generator` does not include some required sources in any of its targets (see their build.yaml file).
The missing sources are:
  - lib/$lib$
```
