### ISSUE TITLE
builder don't find all yaml files in package

### ISSUE THREAD

**Issue by acorn371** [dart-lang/build#3413]
I'm writing a quite simple builder (It should be so...) to copy all yaml files it finds in a dependent package on the root directory.
I named the builder and the package containing it "dart_copy".
Dependent package root directory has 3 yaml files (pubspec.yaml, l10n.yaml, analysis_options.yaml) but my builder runs a buildStep for pubspec.yaml only and so pubspec.yaml only is copied.
As for issue #3358 I read and used tips in [How can I include additional sources in my build?](https://github.com/dart-lang/build/blob/master/docs/faq.md#how-can-i-include-additional-sources-in-my-build) and made some tests (as you can see in comments in the following build.yaml) but they didn't help me.
Below my build.yaml:
```
targets:
  $default:
#    sources:
#        - l10n.yaml
#        - pubspec.yaml
#        - lib/**
#        - $package$
    builders:
      dart_copy|dart_copy:
#        generate_for:
#          include:
#            - l10n.*
        enabled: true

builders:
  dart_copy:
    target: ":dart_copy"
    import: 'package:dart_copy/src/builder.dart'
    builder_factories: ["copyBuilder"]
    build_extensions: {"{{}}.yaml": ["lib/saved/{{}}.copy.yaml"]}
    auto_apply: dependents
    build_to: source

```
and here copy_builder.dart:
```
import 'package:build/build.dart';
class CopyBuilder implements Builder {

  @override
  final Map<String, List<String>>  buildExtensions = const {
    "^{{}}.yaml": ["lib/saved/{{}}.copy.yaml"]
  };

  @override
  Future<void> build(BuildStep buildStep) async {
    final inputId = buildStep.inputId;
    final name = inputId.pathSegments.last;
    final  contents = await buildStep.readAsString(inputId);

    final outputId = AssetId(
        inputId.package,
        "lib/saved/${inputId.path}".replaceFirst(".yaml", ".copy.yaml")
    );

    await buildStep.writeAsString(outputId, '// Copied from $inputId\n$contents');
  }
}
```

Below the environment I'm working with:

Windows 10
Dart SDK 2.18.4

dependencies:
  analyzer: ">=3.0.0 <=5.2.0"
  build: ^2.3.1
  yaml: ^3.1.1

dev_dependencies:
  build_runner: ^2.3.2
  build_config: ^1.1.1
  lints: ^2.0.0

How can I made my builder working ?
Thanks,
Marco
