### ISSUE TITLE
Build runner not generating files in correct directory

### ISSUE THREAD

**Issue by amkuchta** [dart-lang/build#3434]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`)
  * `Dart SDK version: 2.18.6 (stable) (Tue Dec 13 21:15:14 2022 +0000) on "windows_x64"` 
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  * `2.3.2`
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
  * I've created a generator package that uses `PartBuilder` to create new files. The builder runs, and the files are generated, but not in the correct directory. The generated files are being created in the same directory as the source files (`**/entity`), when they should be generating in a `dao` directory that is created in the same location as the source directory (so `**/../dao`). `build.yaml` below:

```yaml
targets:
  $default:
    builders:
      fletch_generator:
        enabled: true
        options:
          build_extensions:
            '^lib/{{dir}}/entity/{{file}}.dart': 'lib/{{dir}}/dao/{{file}}.fletch.dart'

builders:
  fletch_generator:
    import: 'package:fletch_generator/builder.dart'
    builder_factories: ['fletchBuilder']
    build_extensions: { '.dart': ['.fletch.dart'] }
    auto_apply: dependents
    build_to: source
```

* Whether you are using Windows, MacOSX, or Linux (if applicable)
  * Windows 
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
  * N/A  
* Any other packages or constraints we should know about
  * N/A

This may be something I am doing or missing, but I have followed every example I can find, and am not getting the expected output. Thank you in advance for the assistance!

Missing some or all of the above might make the issue take longer or be impossible to act on.

----

For general questions consider using Stack Overflow instead:
https://stackoverflow.com/questions/tagged/dart

Also consider our Gitter channel for light-weight/quick discussions:
https://gitter.im/dart-lang/build

-----
