### ISSUE TITLE
[build_runner] issue with deleted files inside code-gen package

### ISSUE THREAD

**Issue by CodingSoot** [dart-lang/build#3452]
Hello, I'm making a dart code-gen package and I use freezed files within it. The issue I am facing is that when running build_runner, the freezed files get deleted first which leads to errors in the package and ultimately causes the build to fail.

Here is my build.yaml for reference:

```yaml
targets:
  $default:
    builders:
      freezed:
        enabled: true
        generate_for:  
          exclude:
            - example/**
      mygenerator:
        enabled: true
        generate_for:
          - test/integration/*
          
builders:
  mygenerator:
    import: "package:mygenerator/builder.dart"
    builder_factories: ["generateStuff"]
    build_extensions: { ".dart": [".my.dart"] }
    auto_apply: dependents
    build_to: source
    required_inputs: [".freezed.dart"]
``` 

Is there a solution to this issue or a recommended workaround? Any help would be greatly appreciated.

Dart SDK version: 2.18.0
build_runner version: 2.3.3
