### ISSUE TITLE
How can I change the path of generated files ?

### ISSUE THREAD

**Issue by TheCarpetMerchant** [dart-lang/build#3475]
I have seen github discussions about `build_extensions`, but using it leads me to an `Unrecognized keys` error for it.
Edit : Apparently it needs to be under `options`, which is not what the docs here mention. Still, this leads to :
```
Invalid argument(s): Invalid output extension `[lib/generated/{{dir}}/{{file}}.g.dart]`. It should be a string ending with `.dart`
```

I'd just like to have my generated files be in a single folder, instead of cluttering the rest of the project.

Thanks !

**Comment by TheCarpetMerchant** [comment]
Ok, doing a google search _excluding_ results from github lead me to this [website](https://simonbinder.eu/posts/build_directory_moves/) which held the correct syntax.

However, it seems the build tool requires that the {{dir}} argument be present, which seems a bit arbitrary. Is it possible to remove this requirement and just paste the path as the user wishes, or is this a harcoded requirement to avoid file path collisions ?

**Comment by TheCarpetMerchant** [comment]
Okay, thanks for the confirmation. I guess it makes sense to have this restriction.
In terms of the docs, when you look [here](https://github.com/dart-lang/build/blob/master/docs/builder_author_faq.md), you see a `build_extensions` argument. Problem is, it's also a valid options such as :
```
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/generated/{{dir}}/{{file}}.g.dart'
```

I'd be nice to have this documented somewhere (Haven't seen it on the diverse docs linked on the README here).

**Comment by jakemac53** [comment]
I don't believe that is supported... the build extensions need to be a `Map<String, List<String>>`. Are you sure that works?

**Comment by TheCarpetMerchant** [comment]
Well, my files did get generated in the correct placement. Making it a list leads to :
```
Invalid argument(s): Invalid output extension `[lib/generated/{{dir}}/{{file}}.g.dart]`. It should be a string ending with `.dart`
```

**Comment by TheCarpetMerchant** [comment]
Here's the entire YAML :
```yaml
targets:
  $default:
    builders:
      source_gen:combining_builder:
        options:
          build_extensions:
            '^lib/{{dir}}/{{file}}.dart': 'lib/generated/{{dir}}/{{file}}.g.dart'
          ignore_for_file:
            - require_trailing_commas
```
