### ISSUE TITLE
Allow adding global custom header to each generated file

### ISSUE THREAD

**Issue by derolf** [dart-lang/build#3501]
I'd like to be able to specify a `header-line` in `build.yaml` that is added to each generated file at the top:

```
header: // @generated
targets:
  $default:
    builders:
      json_serializable:
        options:
          field_rename: snake
          explicit_to_json: true
```

This line should be included at the very top of each generated file:

```
// @generated
... other content ...
```
