### ISSUE TITLE
Order of generation problem

### ISSUE THREAD

**Issue by Sancene** [dart-lang/build#3509]
I use freezed, json_serializable and retrofit to generate DTO. And when generating with a new build_runner, this message appears:

MyDto must provide a `toJson()` method which return a Map.
It is programmer's responsibility to make sure the RequestBodyDto is properly serialized

It seems that the order of generation was somehow affected because everything was generating just fine on version 2.4.3 of build_runner.

Also it seems that 'runs_before' doesnt affect this in any way

```
builders:
  freezed:
    import: "package:freezed/builder.dart"
    builder_factories: [ "freezed" ]
    build_extensions: { ".dart": [ ".freezed.dart" ] }
    auto_apply: dependents
    build_to: source
    runs_before: [ "json_serializable|json_serializable" ]

  json_serializable:
    import: "package:json_serializable/builder.dart"
    builder_factories: [ "jsonSerializable" ]
    build_extensions: { ".dart": [ "json_serializable.g.part" ] }
    auto_apply: dependents
    build_to: source
    runs_before: [ "retrofit|retrofit" ]

  retrofit:
    target: ":retrofit"
    import: "package:retrofit_generator/retrofit_generator.dart"
    builder_factories: [ "retrofitBuilder" ]
    build_extensions: { ".dart": [ ".retrofit.g.part" ] }
    auto_apply: dependents
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ] 
```

Code above does not fix the problem

We need for [freezed](https://github.com/rrousselGit/freezed/blob/master/packages/freezed/build.yaml) to start generation before json_serializable, and json_serializable should start generation before retrofit:

We need to somehow add a queue for generation

Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK version: 3.0.0 (stable)
* build_runner 2.4.4, freezed 2.3.3, json_serializable 6.6.2, retrofit_generator 7.0.0
* Windows

 [Almost the same issue on the retrofit package](https://github.com/trevorwang/retrofit.dart/issues/570)

**Comment by jakemac53** [comment]
Yes this is a known issue that for builders which don't have any explicit ordering, the order did recently change (this was due to a change in package:graphs). We have since added a secondary sort which should prevent our ordering from changing again in the future, but ultimately you need to use `runs_before` to configure these things.

Regarding your build configuration, did you put those definitions inside your own `build.yaml` file? That probably won't do  what you want it to, instead you can use the global configuration options to specify the ordering:

```yaml
global_options:
  freezed:
    runs_before:
    - json_serializable
  json_serializable:
    runs_before:
    - retrofit
```

That should resolve things.

**Comment by Carapacik** [comment]
Maybe it's better to make a separate repository with the code?

**Comment by Carapacik** [comment]
@jakemac53 Could there be a problem in build.yaml [retrofit_generator](https://github.com/trevorwang/retrofit.dart/blob/master/generator/build.yaml)?
If you fix this file for this, then everything works:
```yaml
builders:
  retrofit_generator:
    import: "package:retrofit_generator/retrofit_generator.dart"
    builder_factories: ["retrofitBuilder"]
    build_extensions: { ".dart": [".retrofit.g.part"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
```
Could there be a problem in build_to(cache or source)? I don't know what `build_to` affects?
