### ISSUE TITLE
failure to run build_runner due to BuildForInputLogger class missing some implementations

### ISSUE THREAD

**Issue by bahag-chandrana** [dart-lang/build#3520]
Suddenly many of our build_runner commands fails with following error in our CI/CD pipeline. We couldn't identify what exactly the issue could be here. Hence created an issue.

```
Failed to build build_runner:build_runner:
../../../../../../.pub-cache/hosted/pub.dev/build_runner_core-7.2.7/lib/src/logging/build_for_input_logger.dart:13:7: Error: The non-abstract class 'BuildForInputLogger' is missing implementations for these members:
 - Logger.onLevelChanged
Try to either
 - provide an implementation,
 - inherit an implementation from a superclass or mixin,
 - mark the class as abstract, or
 - provide a 'noSuchMethod' implementation.

class BuildForInputLogger implements Logger {
      ^^^^^^^^^^^^^^^^^^^
../../../../../../.pub-cache/hosted/pub.dev/logging-1.2.0/lib/src/logger.dart:162:22: Context: 'Logger.onLevelChanged' is defined here.
  Stream<Level?> get onLevelChanged {
                     ^^^^^^^^^^^^^^
```

Following is our `pubspec.yaml` configuration.
```yaml
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  dio: '>=4.0.0 <5.0.0'
  freezed_annotation: '>=2.0.3 <3.0.0'
  json_annotation: '>=4.4.0 <5.0.0'

dev_dependencies:
  freezed: '>=2.0.3 <3.0.0'
  json_serializable: '>=6.1.4 <7.0.0'
  build_runner: any
  test: '>=1.16.0 <2.0.0'

```

* Dart SDK version: 2.19.6 (stable) 

* What builder(s) you are using (or writing yourself).  We mainly use `build_runner` as a dev dependency.
Following is an excerpt from the `pubspec.lock` file.
```yaml 
 build:
    dependency: transitive
    version: "2.3.1"
  build_config:
    dependency: transitive
    version: "1.1.1"
  build_daemon:
    dependency: transitive
    version: "3.1.1"
  build_resolvers:
    dependency: transitive
    version: "2.2.0"
  build_runner:
    dependency: "direct dev"
    version: "2.3.3"
  build_runner_core:
    dependency: transitive
    version: "7.2.7"
  json_annotation:
    dependency: "direct main"
    version: "4.8.1"
  json_serializable:
    dependency: "direct dev"
    version: "6.6.2"
  logging:
    dependency: transitive
    version: "1.2.0"
```
* We a re primarily running on macOS(M1)
