### ISSUE TITLE
Incomplete rebuild for relative dependencies

### ISSUE THREAD

**Issue by devtronic** [dart-lang/build#3522]
## Details
* Dart SDK version: 2.19.6 (stable) (Tue Mar 28 13:41:04 2023 +0000) on "macos_x64"
* What package(s) from this repo you are using:
```
dart pub deps | grep ' build\| build_*'
├── build 2.3.1
├── build_runner 2.3.3
│   ├── build...
│   ├── build_config...
│   ├── build_daemon 3.1.1
│   ├── build_resolvers...
│   ├── build_runner_core...
├── build_runner_core 7.2.7+1
│   ├── build...
│   ├── build_config 1.1.1
│   ├── build_resolvers 2.2.0
│   │   ├── build...
```
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
  * I'm the author of catalyst_builder (https://github.com/mintware-de/catalyst_builder), a dependency injection container builder.
  * It provides a 2 step aggregated builder
    1. Preflight: collect annotations and store the details as json files in the builder cache
    2. Build: Use the json files to generate a single dart that contains the dependency injection container.
* Whether you are using Windows, MacOSX, or Linux (if applicable)
  * macOS 
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
  * Chrome 
* Any other packages or constraints we should know about
  * No

## Problem description
```yaml
# build.yaml
builders:
  preflight:
    import: 'package:catalyst_builder/src/builder/preflight_builder.dart'
    builder_factories:
      - 'runPreflight'
    build_extensions: { '.dart': [ '.catalyst_builder.preflight.json' ] }
    build_to: cache
    auto_apply: dependents

  buildServiceProvider:
    import: 'package:catalyst_builder/src/builder/service_provider_builder.dart'
    builder_factories:
      - 'buildServiceProvider'
    build_extensions: { '.dart': [ '.catalyst_builder.g.dart' ] }
    build_to: source
    auto_apply: dependents
    required_inputs:
      - '.catalyst_builder.preflight.json'
    defaults:
      options:
        providerClassName: 'DefaultServiceProvider'
        includePackageDependencies: false
```
When using `dart run build_runner watch --delete-conflicting-outputs` the buildServiceProvider is only executed the first time when I'm running `dart run build_runner watch` or when code inside lib/ is changed.

Changes outside of lib/ only triggers the preflight step. I can't figure out why the second step is not executed.
When deleting the generated file, the buildServiceProvider step runs once and then the problem occurs again.

## Steps to reproduce
1. Checkout https://github.com/mintware-de/catalyst_builder
2. Run `dart run build_runner watch --delete-conflicting-outputs` inside the example directory
3. `example/lib/example.catalyst_builder.g.dart` should be emitted
4. Edit `example/lib/src/cool_chat_provider.dart` 
   - Add `#foo_bar` as a tag to the `@Service` annotation)
5. Check: the generated file (step 3) should now contain '#foo_bar'
6. Edit `test/third_party_dependency/lib/third_party_dependency.dart` 
   - Add `#foo_bar_two` as a tag to the `@Service` annotation of `ThirdPartyService`
7. Check: the generated file (step 3) should now contain '#foo_bar_two' but it don't.
8. Check: the output of the preflight step (`example/.dart_tool/build/generated/third_party_dependency/lib/third_party_dependency.catalyst_builder.preflight.json`) does contain `foo_bar_two`
9. Delete the generated file from step 3. The file should be regenerated immediately containing the expected tag.

I hope the problem explained well enough. I really don't unterstand why the second step isn't executed for that file.

**Comment by jakemac53** [comment]
The issue is you are not using the asset reader provided by the `BuildStep` - you are overriding it with your own `FileBasedAssetReader`. 

This circumvents all of our dependency tracking, so anything you read through that will not be tracked as a dependency.

**Comment by jakemac53** [comment]
(this is line 62 in `service_provider_builder.dart` fwiw)

**Comment by jakemac53** [comment]
In general you shouldn't be importing/using anything from build_runner_core - that is a support library for build_runner.

**Comment by devtronic** [comment]
> The issue is you are not using the asset reader provided by the `BuildStep` - you are overriding it with your own `FileBasedAssetReader`.
> 
> This circumvents all of our dependency tracking, so anything you read through that will not be tracked as a dependency.

But why is the first step (preflight) always executed? If I debug the build runner in idea and add a breakpoint in the first line of the build method in both builders, it stops only in the preflight builder but not in the buildServiceProvider

**Comment by jakemac53** [comment]
> But why is the first step (preflight) always executed?

Because that builders input (the dart file that you are editing) changed. That is a known input dependency so it re-runs.

The issue is that the next builder that consumes those files, does it in a way that we can't track the dependency. So even though the json file changed, we don't re-run the builder.

**Comment by devtronic** [comment]
Ok, thanks, I understand the problem. Is there a workaround for my use case?

**Comment by jakemac53** [comment]
Is there a reason you can't just use the `buildStep` directly as the asset reader?

**Comment by jakemac53** [comment]
Oh I see, using the custom asset reader it was actually reading from the `.dart_tool` dir directly, so that is why it was able to pick up the files from the other package. Definitely not what you want happening.

You aren't generally allowed to glob across all packages for compatibility reasons with blaze, and general performance/philosophical reasons. So you would need to have some way of knowing the asset ids for these other files that doesn't require globbing.

**Comment by jakemac53** [comment]
One option could be instead of `includePackageDependencies` you could ask users to explicitly list the assets they want to include.

If you don't want to do that, another approach is to make a builder which runs after the `preflight_builder` in each package. It does the glob for that package and outputs a list of all the json files to a new json file, that lives in a known location in the package (lets say, `lib/preflight_files.json`).

Then you just need to know the package names, and from that you could implicitly get all the json files. So you could require the user to just list the package names they want to collect from.

Or, if you just want to search for all packages (like it works now), you can use the new `buildStep.packageConfig` api which is supported for this use case (unlike using `PackageGraph` directly). That will give you a way to get all the package names, so you can then look for those special `preflight_files.json` files that way.

Does that make sense?

**Comment by devtronic** [comment]
> If you don't want to do that, another approach is to make a builder which runs after the `preflight_builder` in each package. It does the glob for that package and outputs a list of all the json files to a new json file, that lives in a known location in the package (lets say, `lib/preflight_files.json`).

That option sounds good. In which build.yaml do I need to declare this builder?

---

I tried something and found another way that do the trick (But it's ugly as hell 😂 ):
1. I don't need to change anything
2. The users need to `export 'package:other_package/other_package.dart`, in my case `export 'package:third_party_dependency/third_party_dependency.dart';`

Another approach I tried (but it doesn't work) is to specify the packages inside the `generate_for` in the main package build.yaml:
```yaml
targets:
  $default:
    auto_apply_builders: true
    builders:
      catalyst_builder|buildServiceProvider:
        options:
          providerClassName: 'ExampleProvider'
          includePackageDependencies: true
        generate_for:
          include:
            - lib/*.dart
            - package:third_party_dependency/*.dart # this
```

**Comment by jakemac53** [comment]
> That option sounds good. In which build.yaml do I need to declare this builder?

The same one that defines the preflight builder - you could actually combine them into the same builder definition if you want (you would list multiple builder factories, with the one that does the globbing second). And your build extensions would list the extensions for each, something like this:

``` yaml
builders:
  preflight:
    import: 'package:catalyst_builder/src/builder/preflight_builder.dart'
    builder_factories:
      - 'runPreflight'
      - 'collectPreflight'
    build_extensions:
      .dart: [ '.catalyst_builder.preflight.json' ]
      $package$:  ['lib/preflight_files.json']
    build_to: cache
    auto_apply: dependents
```
