### ISSUE TITLE
Too slow for a big project, any innovation planned to solve it thoroughly?

### ISSUE THREAD

**Issue by GerogeLeon** [dart-lang/build#3526]
* Dart SDK version: 3.0.3 (stable) 
* build_runner: ^2.4.4
* builders used:
    * chopper_generator: ^6.0.1
    * json_serializable: ^6.7.0
    * injectable_generator: ^2.1.6
    * floor_generator: ^1.4.2

I have configured the build.yaml, but still very slow.  For example, even if I change one line code, it takes 40 seconds above.
> [INFO] Succeeded after 41.8s with 255 outputs (514 actions)

I have searched a lots for a solution on Internet, but there is no efficient one.

Impact:   
The low speed greatly decreases the development effiency and user experience. It's excruciating!

My suggestion:  
Maybe we could learn from other languages or libraries. 
For example, the Java library Lombok,  it also generates codes but at compiling stage instead of coding stage. Every time we build or trigger reload,  it handles all code generation in a way that we are not even aware of  the code generation  existing.   It also has a IDE plugin that compresses its compiling errors that is caused by not-yet generated codes.  So, it does not block developer coding by the frequently long code-generation running as the dart build_runner does. 

I abstract its feature as these:  Lazy,  Insensible

I am not good at low-level software developing. The reason why I say much these is because I want to provide some possible references , and I hope the low speed problem can be solved in a way of innovation and thoroughness

build.yaml:
```yaml
targets:
  $default:
    sources:
      exclude:
        - lib/chat/**
        - lib/consultant/**
        - lib/contact/**
        - lib/discovery/**
        - lib/enums/**
        - lib/feed/**
        - lib/login/**
        - lib/myself/**
        - lib/nearby/**
        - lib/settings/**
        - lib/strategy/**
        - lib/widget/**
        - lib/example/**

    builders:
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/http/model/**.dart
            - lib/mqtt/model/**.dart
            - lib/repository/entity/**.dart
            - lib/repository/view/**.dart
            - lib/repository/model/**.dart
            - lib/repository/**/entity/**.dart
            - lib/repository/**/view/**.dart
            - lib/repository/**/model/**.dart

      #https://github.com/Milad-Akarie/injectable/blob/master/injectable_generator/build.yaml
      injectable_generator:injectable_builder:
        generate_for:
          include:
            - lib/inject/**.dart
            - lib/http/**.dart
            - lib/http/interceptor/**.dart
            - lib/mqtt/**.dart
            - lib/notification/**Preference.dart
            - lib/notification/**Service.dart
            - lib/notification2/**Preference.dart
            - lib/notification2/**Service.dart
            - lib/repository/**/**Dao.dart
            - lib/repository/**/**Preference.dart
            - lib/repository/**/**BeanDef.dart
            - lib/service/**/**.dart
            - lib/service/**.dart
            - lib/webrtc/**.dart
            - lib/router/**.dart
            - lib/pay/**.dart
      #https://github.com/Milad-Akarie/injectable/blob/master/injectable_generator/build.yaml
      injectable_generator:injectable_config_builder:
        generate_for:
          include:
            - lib/inject/injection.dart

      #https://github.com/lejard-h/chopper/blob/develop/chopper_generator/build.yaml
      chopper_generator:chopper_generator:
        generate_for:
          include:
            - lib/http/**/**.dart
            - lib/http/**.dart
      #https://github.com/pinchbv/floor/blob/develop/floor_generator/build.yaml
      floor_generator:floor_generator:
        generate_for:
          include:
            - lib/repository/**/**.dart


```
