### ISSUE TITLE
`build_runner` generates `InvalidType` for `dart:ui` Locale

### ISSUE THREAD

**Issue by a-wallen** [dart-lang/build#3527]
I have a `freezed` annotated class with a field of type `Locale` that generates `InvalidType` instead of `Locale` in the `appearance.freezed.dart` file. 

#### Information
* Dart SDK Version (`dart --version`)
`Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) 
on "windows_x64`
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
```
  build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      sha256: b0a8a7b8a76c493e85f1b84bffa0588859a06197863dba8c9036b15581fd9727
      url: "https://pub.dev"
    source: hosted
    version: "2.3.3"
```
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
`freezed` and `json_serializable`
* Whether you are using Windows, MacOSX, or Linux (if applicable)
`Windows`
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
