### ISSUE TITLE
Custom build script usage causes Invalid Argument error. 

### ISSUE THREAD

**Issue by samyakkkk** [dart-lang/build#3528]
Thank you for taking the time to file an issue!

In order to route, prioritize, and act on this as soon as possible please include:

* Dart SDK Version (`dart --version`)
Dart SDK version: 2.19.3 (stable) (Tue Feb 28 15:52:19 2023 +0000) on "macos_arm64"
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  build: ^2.0.0
  build_runner: ^2.0.0
  build_runner_core: ^7.0.0
* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
We're using a LibraryBuilder that takes annotated .dart files and generates unit tests for them using AI in the `/test` folder. Upon the outputs a second mocktio builder is ran to generate mocks of the output file.
* Whether you are using Windows, MacOSX, or Linux (if applicable)

-----
Hi, we're using a custom `bin/ai.dart` script that is triggered using `flutter pub run welltested:ai build` as discussed in #3262. 
```
import 'package:build_runner_core/build_runner_core.dart' as build_runner_core;
import 'package:welltested/builder.dart' as welltested;
import 'package:build_runner/build_runner.dart' as build_runner;
import 'package:mockito/src/builder.dart' as mockito;
import 'dart:io' as io;

final _builders = <build_runner_core.BuilderApplication>[
  build_runner_core.apply(
    r'welltested:ai',
    [welltested.welltestedGenerator],
    build_runner_core.toDependentsOf(r'welltested'),
    hideOutput: false,
  ),
  build_runner_core.apply(
    r'mockito:mockBuilder',
    [mockito.buildMocks],
    build_runner_core.toDependentsOf(r'welltested'),
    hideOutput: false,
  )
];
Future<void> main(List<String> args) async {
  build_runner_core.overrideGeneratedOutputDirectory('welltested_cache');
  final result = await build_runner.run(args, _builders);
  io.exitCode = result;
}
```
It does the job well except with a issue that every alternate run resulted into the error: 

`[WARNING] Invalidating asset graph due to build script update!`

Upon debugging we boiled down the issue to [snippet](https://github.com/dart-lang/build/blob/f2fee271d3e40229060c265c3dee227d9a2eb5ae/build_runner_core/lib/src/changes/build_script_updates.dart#LL52C1-L52C1) in build_script_updates.dart:

```
  allSources = _urisForThisScript
          .map((id) => _idForUri(id, rootPackage))
          .whereNotNull()
          .toSet();
```
giving error: `Invalid argument (Asset paths may not reach outside the package.): "../../welltested/bin/ai.dart"` that sets the `supportsIncrementalRebuilds` tag to false and triggers build script update on every alternate run. 

I think the error makes sense and #2851 explains why, but how can we fix this problem?

I'm sharing the code of welltested builder as well:

```
Builder welltestedGenerator(BuilderOptions options) {
  Map<String, String> possiblePaths = {};
  List.generate(100, (index) => index).forEach(
      (e) => possiblePaths['lib/{{$e}}.dart'] = 'test/{{$e}}/$e.wt.dart');
  return LibraryBuilder(WelltestedGenerator(),
      generatedExtension: ".wt.dart",
      allowSyntaxErrors: true,
      options: BuilderOptions({"build_extensions": possiblePaths}));
}
```

pubspec.yaml:
```
name: welltested
description: >
  WelltestedAI is a Testing AI Pilot helping developers add and maintain tests
  as they code and deliver stable welltested apps to users.

version: 1.0.2

repository: https://github.com/PixelAppsMobile/welltested
issue_tracker: https://github.com/PixelAppsMobile/welltested/issues

environment:
  sdk: ">=2.18.2 <3.0.0"

dependencies:
  analysis_server_lib: ^0.2.1
  analyzer: ^5.10.0
  analyzer_plugin: ^0.11.1
  build: ^2.0.0
  build_runner: ^2.0.0
  build_runner_core: ^7.0.0
  dotenv: ^4.0.0
  http: ^0.13.0
  mockito: ^5.0.10
  source_gen: ^1.2.2

dev_dependencies:
  build_test: ^2.1.6
```

Thanks in advance for the help.

**Comment by jakemac53** [comment]
How are you depending on/using this package? It seems like you probably aren't using it on itself, but that it contains a script under `bin` and then you are somehow invoking that.

If you are trying to use that as a globally activated package for instance,  then the build script invalidation won't work. You need a dependency on the package that the script is coming from and then you need to invoke it as a local script and not a global one.

It would also be possible for us to expose a way to configure the `BuildScriptUpdates` implementation potentially if you need to provide your own implementation although I would need more information to understand if that is necessary.

**Comment by jakemac53** [comment]
Hmm, looking at the code it looks like we are actually creating that relative URI from an absolute one https://github.com/dart-lang/build/blob/f2fee271d3e40229060c265c3dee227d9a2eb5ae/build_runner_core/lib/src/changes/build_script_updates.dart#L101 when we see any `file://` uri, which is likely the case  here.

**Comment by jakemac53** [comment]
@samyakkkk Can you try using a dependency override to test out this fix? https://github.com/dart-lang/build/pull/3530.

```yaml
dependency_overrides:
  build_runner_core:
    git:
      url: https://github.com/dart-lang/build.git
      ref: support-bin-scripts
      path: build_runner_core
```
