### ISSUE TITLE
build_runner fail when using local package inside pubspec.yaml

### ISSUE THREAD

**Issue by EArminjon** [dart-lang/build#3576]
* Dart SDK Version 
  - 2.19.6
* What package(s) from this repo you are using, and the version : 
  - build_runner: ^2.2.1
* What builder(s) you are using (or writing yourself). 
  - Freezed
* Whether you are using Windows, MacOSX, or Linux (if applicable)
  - MacOs
* Any other packages or constraints we should know about
  - I use a local package (a fork) of a dependency from pub.dev

I cannot run the following command : 
[huawei_location.zip](https://github.com/dart-lang/build/files/12599777/huawei_location.zip)

```
flutter pub run build_runner build --delete-conflicting-output
```
```
The pubspec.lock file has changed since the .dart_tool/package_config.json file was generated, please run "flutter pub get" again.
pub finished with exit code 65
```

I got this error since a add a local package inside my pubspec.yaml
```yaml
dependencies:
  huawei_location:
    path: forked/huawei_location
```

In attachment the zip of the fork (it's light).

**Comment by jakemac53** [comment]
This is an error from pub, did you try running `flutter pub get` as instructed?

**Comment by EArminjon** [comment]
Yes, issue apear only when I add a dependency using the local path.

**Comment by EArminjon** [comment]
```yaml
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.17.0
  visibility_detector: ^0.4.0+2
  shared_preferences: ^2.0.15
  flutter_bloc: ^8.1.1
  provider: ^6.0.5
  dartx: ^1.1.0
  rxdart: ^0.27.5
  equatable: ^2.0.5
  sqflite: ^2.2.6
  path_provider: ^2.0.11
  dio: ^4.0.6
  dartz: ^0.10.1
  cupertino_icons: ^1.0.5
  speech_to_text: ^6.0.0
  package_info_plus: ^3.0.1
  flutter_secure_storage: ^5.0.2
  connectivity_plus: ^2.3.9
  another_flushbar: ^1.12.31-dev.1
  flutter_pdfview: ^1.3.1
  permission_handler: ^10.1.0
  location: ^4.4.0
  flutter_svg: ^1.1.5
  firebase_core: ^2.1.1
  firebase_analytics: ^10.0.0
  firebase_crashlytics: ^3.0.4
  firebase_performance: ^0.9.0
  firebase_remote_config: ^4.2.4
  share_plus: ^6.1.0
  flutter_beep: ^1.0.0
  vibration: ^1.7.6
  flutter_spinkit: ^5.1.0
  app_tracking_transparency: ^2.0.2+4
  launch_review: ^3.0.1
  upgrader: ^5.1.0
  fluttertoast: ^8.0.9
  in_app_review: ^2.0.6
  mask_text_input_formatter: ^2.4.0
  font_awesome_flutter: ^10.3.0
  collection: ^1.16.0
  url_launcher: ^6.1.6
  device_info_plus: ^8.0.0
  logging: ^1.1.0
  disk_space: ^0.2.1
  infinite_scroll_pagination: ^3.2.0
  local_auth: ^2.1.2
  flutter_html: ^3.0.0-alpha.6
  screenshot: ^1.2.3
  crypto: ^3.0.2
  flutter_slidable: ^2.0.0
  flutter_mute: ^0.0.4
  flutter_native_splash: ^2.2.11
  cross_file: ^0.3.3+2
  flutter_inappwebview: ^5.7.2+3
  mime: ^1.0.2
  mobile_scanner: ^3.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
  get_it: ^7.2.0
  shimmer: ^2.0.0
  video_player: ^2.5.3
  youtube_player_iframe: ^4.0.4
  video_thumbnail: ^0.5.3
  photo_view:
    git:
      url: https://github.com/bluefireteam/photo_view.git
      ref: d2865d36766e5882bb4cccc91c1f64b91e287289
  carousel_slider: ^4.2.1
  currency_formatter: ^2.0.0
  flutter_datawedge: ^1.2.0
  synchronized: ^3.1.0
  alice: ^0.3.2
  cached_network_image: ^3.2.3
  jwt_decoder: ^2.0.1
  worldtime: ^1.0.9
  scrolls_to_top: ^2.1.0
  huawei_location:
    path: forked/huawei_location
  google_api_availability: ^5.0.0

# Temporary solve version issue with bloc_test requesting an older version of test and analyzer libraries
# which are not compatible with more recent packages like dart_code_metrics
dependency_overrides:
  analyzer: ^5.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  test: any

  dart_code_metrics: ^4.21.0
  bloc_test: ^9.1.0
  build_runner: ^2.2.1
  alchemist: ^0.6.1
  golden_toolkit: ^0.13.0
  lint: ^2.0.1
  sqflite_common_ffi: ^2.2.3
  freezed: ^2.3.2
  json_serializable: ^6.5.4
  flutter_gen: ^5.1.0+1
  source_gen: ^1.2.6
  mocktail: ^0.3.0
```
