### ISSUE TITLE
Proposal: allow to run Builder for whole directory

### ISSUE THREAD

**Issue by Alexqwesa** [dart-lang/build#3589]
Currently build_runner only pass files to Builder, which makes hard to write aggregation Builders, 

If it allowed to pass directory to Builder, it will be easy to track files creation/deletion...

maybe use `build_extensions` like in this example:
```yaml
builders:
  package|packBuilder:
    build_extensions: {r'$dir$assets/svg': ['lib/list_of_svg_assets.dart'], }   # this line!!!
    import: "package:package/src/builders/builders.dart"
    builder_factories: ["packBuilder"]
    auto_apply: root_package
    build_to: source
```
in this example, it suppose to watch modification of directory `assets/svg`, and run Builder each time file created/deleted.
