### ISSUE TITLE
(help) Issue with incremental build affecting additional unmodified sources

### ISSUE THREAD

**Issue by erick-ciudaz** [dart-lang/build#3644]
## Context:
I am creating a code generator for my dart frog project, My dart frog project has the following structure:

```bash
|
|-- lib/
|-- routes/
|
```
Both directories (lib and routes) are at the same level. To analyze the entire project, I have included the routes directory in the resources configuration of the build.yaml file.

## Problem:
When I make changes to files within the lib directory, the build system triggers the build not only for the modified files in lib but also for all additional sources declared in resources, including the routes directory. This results in unnecessary build execution for files that have not been directly modified.

Relevant Configuration:

```yaml
## build.yaml (dart_frog project)

targets:
  $default:
    sources:
      - lib/**
      - routes/**
     
      - pubspec.
      - $package$

 ```

```yaml
## build.yaml (dart generator)

  cache_builder:
    import: "package:custom_generator/custom_generator.dart"
    builder_factories: ["cacheBuilder"]
    build_extensions: {".dart":[".ctx.json"]}
    auto_apply: dependents
    build_to: source
    defaults:
      generate_for:
        exclude:
          - '**/**.g.dart'
          - '**/**.freezed.dart'


 ```

```dart
/// cache_builder.dart (dart generator)

class CacheBuilder extends Builder {
  CacheBuilder({required this.generator});
  final Generator generator;

  @override
  Map<String, List<String>> get buildExtensions => {
        '.dart': const ['.ctx.json'],
      };

  @override
  FutureOr<void> build(BuildStep buildStep) async {
    log.info("assetId path ${buildStep.inputId.path}");
    final generatedCode = _generate(buildStep);
    await _write(buildStep,generatedCode);
  }


  
}

```

Environment:

Operating System: 
```bash
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
```
Dart Version: Dart SDK version: 3.0.3 (stable) 
build_runner Version: 2.4.7 
build version: 2.4.1
source_gen version: 1.4.0
