### ISSUE TITLE
Unable to get the custom extension

### ISSUE THREAD

**Issue by EclipseAndrey** [dart-lang/build#3646]
Hello
I am trying to get the `example_model.fti.dart` file
However, I get only `example_model.fti.g.part` at the output

I've tried different variations of `build_extensions`
```
.fti.g.part
.fti.g.dart
.fti.part
.fti.dart
...
```
with my build.yaml

```yaml
builders:
  generators:
    target: ":generators"
    import: "package:generators/generators.dart"
    builder_factories: ["fti"]
    build_extensions: { ".dart": [".fti.dart"] }
    auto_apply: dependents
    build_to: source
    applies_builders: ["source_gen|combining_builder"]
#    runs_before:
#      - source_gen|combining_builder

```

My worst result is `example_model.fti.g.part`, and best `example_model.g.dart`
but `example_model.g.dart` conflicting with `json_serializable` 
How I can get `example_model.fti.dart`
