### ISSUE TITLE
[build_runner] More comprehensive measuring_performance.md

### ISSUE THREAD

**Issue by FufferKS** [dart-lang/build#3648]
Hi, I've embarked on a journey to decrease the time taken by the build_runner in my project.

It would be extremely helpful if we got a bit more info on the performance measuring.
https://github.com/dart-lang/build/blob/master/docs/measuring_performance.md

The docs are quite short, but I would like to learn more about how to interpret the results, different view options, what is the difference between real time and user time, how to interpret the async slices, how to read actions that take longer, what steps are optimisable and which are not, etc etc.

If there are any learning materials you recommend or would be able to add to the official docs, it would be greatly appreciated!

**Comment by Serena867** [comment]
Without touching on the part about measuring performance, I had some success speeding up my build time by making my `generate_for` targets fairly specific by using `includes` and `excludes`.

``` 
generate_for:
          include:
            - lib/ ...Add specific targets here
          exclude:
            - lib/ ...Exclude anything you don't need targeted here
```
 
 Thanks again to Jake and the rest of the Dart team on that one.
