### ISSUE TITLE
Unable to run a build_runner of one package before another

### ISSUE THREAD

**Issue by bilalrabibi** [dart-lang/build#3653]
```
targets:
  $default:
    builders:
      auto_models|auto_models:
        enabled: true

builders:
  auto_models:
    import: "package:auto_models/builder.dart"
    builder_factories: ["dataModalBuilder"]
    build_extensions: { '.dart': [ 'gen/.mapped.dart' ] }
    auto_apply: dependents
    build_to: source
    runs_before: 
              - drift:drift_dev
    applies_builders: [ 'source_gen' ]



```
I tried 
  runs_before: ['drift:drift_dev'] and ['drift:drift_dev'] too 

Please note both packages are added in pubspec.yaml file

I am trying to run this code generator before the one run by the `drift` database
but i am not able to get the order correct.

* Dart SDK Version (`Dart SDK version: 3.2.0 (stable)`)
* What package(s) from this repo you are using, and the version (i.e. `build_runner: ^2.0.0`)

* What builder(s) you are using (or writing yourself). Try to give a short summary of what they do.
- Generate model files for tables which are used by drift package

**Comment by jakemac53** [comment]
Try running `dart run build_runner doctor`, which should complain about an unknown builder key.

Specifically, this builder actually comes from the `drift_dev` package, so it should be something like `drift_dev` or `drift_dev:drift_dev`.

There are a lot of other builders too (see [here](https://github.com/simolus3/drift/blob/develop/drift_dev/build.yaml)), so depending on exactly what you want to achieve you might need to list some of those.

**Comment by bilalrabibi** [comment]
Thanks allot
I was able to resolve it using below code

```
auto_models:
    import: "package:auto_models/builder.dart"
    builder_factories: ["dataModalBuilder"]
    
    build_extensions: { ".dart": [ ".mapped.g.dart" ] }
    auto_apply: dependents
    build_to: source          
    runs_before: ["drift_dev|drift_dev"]
    applies_builders: ["source_gen|combining_builder"]

```

The only problem i am not able to generate the code in a different folder like /generate using this

**Comment by jakemac53** [comment]
> The only problem i am not able to generate the code in a different folder like /generate using this

Have you looked at using [capture groups](https://github.com/dart-lang/build/blob/master/docs/writing_a_builder.md#capture-groups)?

**Comment by bilalrabibi** [comment]
Yes sir. I have tried in main build.yaml file

```
auto_models:
        options:
  
          build_extensions:
            "{{}}.dart": '{{dir}}/generated/{{file}}.mapped.g.dart'

```

full yaml file is 

```
targets:
  $default:
    builders:
      
      
      #general purpose .g.dart builder
      source_gen|combining_builder:
        enabled: true
        
        generate_for:
          - lib/**.dart
        options:
          build_extensions:
            '^{{path}}/{{file}}.dart': '{{path}}/generated/{{file}}.g.dart'

      #chopper
      chopper_generator:
        options:
          # This assumes you want the files to end with `.chopper.g.dart`
          # instead of the default `.chopper.dart`.
          build_extensions:
            "^{{path}}/{{file}}.dart": '{{path}}/generated/{{file}}.chopper.g.dart'
     
 ````

Package yaml file 
```
targets:
  $default:
    builders:
      auto_models|auto_models:
        enabled: true

builders:

  auto_models:
    import: "package:auto_models/builder.dart"
    builder_factories: ["dataModalBuilder"]
    
    build_extensions: { ".dart": [ "generated/.mapped.g.dart" ] }
    auto_apply: dependents
    build_to: source          
    runs_before: ["drift_dev|drift_dev"]
    applies_builders: ["source_gen|combining_builder"]

```

also tried 

```    build_extensions: { ".dart": [ ".mapped.g.dart" ] } ```

but files are always generating inside same folder
