### ISSUE TITLE
Build runner stuck after precompiling

### ISSUE THREAD

**Issue by shayant98** [dart-lang/build#3655]
Hey all,

Recently i went back to an old flutter project to fix a bug, but was unable to generate code using build_runner
Running any build_runner command results in it getting stuck and consuming all memory till it hits exhaustion.

The command i'm trying to run: ```dart run build_runner build -v```

build_runner version: 2.4.8

flutter doctor:
```
[✓] Flutter (Channel stable, 3.19.1, on Microsoft Windows [Version 10.0.22000.2538], locale en-US)
    • Flutter version 3.19.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision abb292a07e (6 days ago), 2024-02-20 14:35:05 -0800
    • Engine revision 04817c99c9
    • Dart version 3.3.0
    • DevTools version 2.31.1

[✓] Windows Version (Installed version of Windows is version 10 or higher)

[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    • Android SDK at C:\Users\ssital\AppData\Local\Android\sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)
    • All Android licenses accepted.

[✓] Chrome - develop for the web
    • Chrome at C:\Program Files\Google\Chrome\Application\chrome.exe

[✓] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019 16.11.30)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.34031.81
    • Windows 10 SDK version 10.0.19041.0

[✓] Android Studio (version 2022.3)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 17.0.6+0-b2043.56-10027231)

[✓] VS Code, 64-bit edition (version 1.86.2)
    • VS Code at C:\Program Files\Microsoft VS Code
    • Flutter extension version 3.82.0

[✓] Connected device (3 available)
    • Windows (desktop) • windows • windows-x64    • Microsoft Windows [Version 10.0.22000.2538]
    • Chrome (web)      • chrome  • web-javascript • Google Chrome 120.0.6099.110
    • Edge (web)        • edge    • web-javascript • Microsoft Edge 122.0.2365.52

[✓] Network resources
    • All expected network resources are available.

• No issues found!
```

issue:
```
dart run build_runner build
Building package executable... (6.6s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 320ms
[INFO] Precompiling build script... completed, took 6.7s
```

Ps. running ```build_runner doctor``` or ```-v``` results in the same issue

**Comment by jakemac53** [comment]
I would need more information to diagnose this issue - ideally some form of reproduction case.

**Comment by shayant98** [comment]
@jakemac53 I would love to provide a case, but running it in a recent Flutter project does not seem to cause the issue.

here are de dependencies used in the project:
```yaml
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  stacked: ^3.1.0+3
  stacked_services: ^0.9.9
  font_awesome_flutter: ^10.2.1
  json_annotation: ^4.5.0
  freezed_annotation: ^2.0.3
  dio: ^5.0.0
  dio_cookie_manager: ^2.0.0
  connectivity: ^3.0.6
  expandable: ^5.0.1
  intl: ^0.18.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  geocoding: ^2.0.1
  url_launcher: ^6.0.17
  multi_select_flutter: ^4.0.0
  flutter_awesome_select: ^6.1.2-beta
  image_picker: ^0.8.4+4
  signature: ^5.0.0
  location: ^4.3.0
  websafe_svg: ^2.1.0
  firebase_crashlytics: ^3.0.12
  firebase_core: ^2.5.0
  firebase_analytics: ^10.1.1
  shimmer: ^2.0.0
  nanoid: ^1.0.0
  uuid: ^3.0.5
  permission_handler: ^10.0.2
  package_info_plus: ^3.0.3
  auto_size_text: ^3.0.0
  collection: ^1.16.0
  checkbox_grouped: ^1.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  stacked_generator: ^0.8.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.1.1
  logger:
  mockito: ^5.0.16
  hive_generator: ^2.0.0
  flutter_flavorizr: ^2.1.2

```

i tried updating all packages and project to the latest version, but it did not seem to help.
