### ISSUE TITLE
build_web_compilers' output is not served by webdev in Flutter web projects

### ISSUE THREAD

**Issue by andynewman10** [dart-lang/build#3659]
Context

- VS code 1.87.2
- Dart extension 3.84.0
- Flutter 3.19.3
- Windows 11

1. create a flutter web-only application using `flutter create --platforms=web testapp`.
2. add `build_runner` and `build_web_compilers` to your `pubspec.yaml` file
3. In your `web` folder, add a `sw.dart` file. A typical scenario for this is to write a service worker file in Dart. See [this](https://github.com/flutter/flutter/issues/145492) issue. For a quick test, just add `void main(List<String> args) {}` in this file.
5. create a `build.yaml` file and copy the contents from [this](https://github.com/isoos/service_worker/blob/master/example/build.yaml) file.
6. Issue a `dart run build_runner build` from the command line. The sw.dart.js file gets generated under `testapp/.dart_tool/build/generated/com_example_testapp/web`, not `testapp/web`.
7. Start a debug session from VS code. The web server will run over, eg., `http://localhost:12345/`, and will serve the `testapp/web` directory, so the `sw.dart.js` file generated in the `testapp/.dart_tool/build/generated/com_example_testapp/web` directory won't be served.

Isn't there a way to have `build_runner` or `build_web_compilers` generate the JS files in the `testapp/web` directory itself, rather than in the above mentionned directory under `.dart_tool`?
EDIT: I tried the `build_to: source` directive but it doesn't work:

```
# build.yaml (see above)
[...]
builders:
  entrypoint:
    import: "package:build_web_compilers/builders.dart"
    builder_factories:
       - webEntrypointBuilder
    build_extensions:
       .dart:
          - .dart.js
          - ...
    build_to: source
```
