### ISSUE TITLE
`AssetNotFoundException` when building two packages at the same time

### ISSUE THREAD

**Issue by lucavenir** [dart-lang/build#3668]
Hi there,

I've been re-routed here because `build_runner` said:
```
You have hit a bug in build_runner [...]
```

Here's my use case.

I have a `melos run generate` script that I run to generate code in my two packages.
```yaml
# melos.yaml
# ...
scripts:
  # ...
  generate:
    run: melos exec --depends-on=build_runner -- "dart run build_runner build -d"
    description: builds generated dart files for every package in this project
```
What this does is simply executing `dart run build_runner build -d` for my two packages, which have this following structure:
```
packages/
  - app
  - data
```

The important part is that `app` depends on `data`, i.e. `app` uses several classes from the `data` package - just `@freezed` some generated classes.
The command above works fine on the `data` package, which indeed doesn't depend on anything; alas, the command above *fails* for the `app` package; my guess is - because of this dependency.

Here's the full error reported to me:
<details>
 <summary>Logs</summary>

```logs
You have hit a bug in build_runner
Please file an issue with reproduction steps at https://github.com/dart-lang/build/issues

AssetNotFoundException: moto_it_data|lib/src/access/models/login_request.model.freezed.dart

package:build_runner_core/src/asset/file_based.dart 135:18           _fileForOrThrow.<fn>
dart:async                                                           _rootRunUnary
package:build_runner_core/src/asset/file_based.dart 35:13            FileBasedAssetReader.readAsBytes.<fn>
package:build/src/asset/reader.dart 53:13                            AssetReader.digest
package:build_runner_core/src/asset_graph/graph.dart 171:30          AssetGraph._setLastKnownDigests.<fn>
dart:async                                                           Future.wait.<fn>
package:build_runner_core/src/asset_graph/graph.dart 170:5           AssetGraph._setLastKnownDigests
package:build_runner_core/src/asset_graph/graph.dart 74:5            AssetGraph.build
package:build_runner_core/src/generate/build_definition.dart 253:24  _Loader.prepareWorkspace.<fn>
package:build_runner_core/src/logging/logging.dart 25:18            
 logTimedAsync
package:build_runner_core/src/generate/build_definition.dart 251:7   _Loader.prepareWorkspace
package:build_runner_core/src/generate/build_impl.dart 114:27        BuildImpl.create
package:build_runner_core/src/generate/build_runner.dart 34:26       BuildRunner.create
package:build_runner/src/generate/build.dart 109:17                  build
package:build_runner/src/entrypoint/build.dart 35:18                 BuildCommand._run
package:args/command_runner.dart 212:13                              CommandRunner.runCommand
package:build_runner/src/entrypoint/run.dart 26:18                   run
.dart_tool/build/entrypoint/build.dart 62:16                         main
```

</details>

Here's `build.yaml` for `app`:
```yaml
targets:
  $default:
    dependencies:
      - data # isn't this enough?
    builders:
      go_router_builder:
        generate_for:
          - lib/router/routes_config.dart
      riverpod_generator:
        generate_for:
          - lib/clients/connection_checker.provider.dart
          - lib/src/**/*.repository.dart
          - lib/src/**/*.provider.dart
          - lib/src/**/*.controller.dart
          - lib/src/**/*.service.dart
          - lib/core/moto_it_http.client.dart
          - lib/core/moto_it_db.client.dart
          - lib/core/cache.dart
          - lib/data/api.dart
          - lib/data/db.dart
          - lib/core/config/*.provider.dart
      freezed:
        generate_for:
          - lib/src/**/*.model.dart

global_options:
  freezed:
    runs_before:
      - riverpod_generator
      - go_router_builder
```
As you can see I've added a `dependencies` argument, hoping that the builder would catch on that.

## env info

* Dart SDK Version?
`Dart SDK version: 3.2.3 (stable) (Tue Dec 5 17:58:33 2023 +0000) on "linux_x64"`
* What package(s) from this repo you are using, and the version?
From `pubspec.yaml`:
```yaml
dev_dependencies:
  build_runner: ^2.4.6
  build_config: ^1.1.1
  flutter_flavorizr: ^2.2.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  go_router_builder: ^2.3.3
  riverpod_generator: ^2.3.2
  mocktail: ^1.0.3
  riverpod_lint: ^2.3.7
  custom_lint: ^0.5.3
  very_good_analysis: ^5.1.0
```
* What builder(s) you are using (or writing yourself)?
Mainly, `freezed` and `riverpod_generator`, as shown above
* Any other packages or constraints we should know about?
The dependencies between the two packages shown above

**Comment by jakemac53** [comment]
Most likely the issue is these builds need to run sequentially and not in parallel (and bottom up, dependency-wise).

I don't know if that is possible or not.

**Comment by lucavenir** [comment]
I'm sorry - I misunderstood what `dependencies` meant, then. I thought the two pacakges could build in parallel, given the dependency constraint.

I changed the `melos.yaml` like so:
```yaml
generate:
  run: flutter pub run build_runner build -d
  exec:
    orderDependents: true
  description: builds generated dart files for every package in this project
```

I'm closing this issue, everything works great now. I hope I did not waste your time; maybe someone else might find this useful, who knows.
