### ISSUE TITLE
Wasm compile crashes as build time

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#3746]
At https://github.com/dart-lang/build/commit/49d83f489236073212ce4c7ba8c6c19ec1a1037b

with this build.yaml
```yaml
# See https://github.com/dart-lang/build/tree/master/build_web_compilers#configuration
targets:
  $default:
    builders:
      build_web_compilers|dart2js_archive_extractor:
        options:
          filter_outputs: false
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        options:
          compilers:
            dart2wasm:
              args:
                - -O4
                - --no-strip-wasm
            dart2js:
              args:
                - --dump-info
                - --no-source-maps
                - --show-package-warnings
                - -O4
```

get this error

```
type 'YamlMap' is not a subtype of type 'Map<String, Object?>?' in type cast
dart:_internal                                                      MappedIterator.moveNext
package:build_web_compilers/src/web_entrypoint_builder.dart 171:62  new EntrypointBuilderOptions.fromOptions
package:build_web_compilers/src/web_entrypoint_builder.dart 279:58  new WebEntrypointBuilder.fromOptions
package:build_web_compilers/builders.dart 16:26                     webEntrypointBuilder
package:build_runner                                                BuildCommand._run
package:args/command_runner.dart 212:13                             CommandRunner.runCommand
package:build_runner                                                run
.dart_tool/build/entrypoint/build.dart 145:16                       main
```

CC @jakemac53
