### ISSUE TITLE
New wasm compile fails with JS fallback

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/build#3747]
At https://github.com/dart-lang/build/commit/49d83f489236073212ce4c7ba8c6c19ec1a1037b

with this build.yaml
```yaml
# See https://github.com/dart-lang/build/tree/master/build_web_compilers#configuration
targets:
  $default:
    builders:
      build_web_compilers|dart2js_archive_extractor:
        options:
          filter_outputs: false
      build_web_compilers|entrypoint:
        generate_for:
          - web/**.dart
        options:
          compilers:
            dart2wasm:
              args:
                - -O4
                - --no-strip-wasm
            dart2js:
              args:
                - --dump-info
                - --no-source-maps
                - --show-package-warnings
                - -O4
```

(and a fix for https://github.com/dart-lang/build/issues/3746)

We see a runtime crash in safari (JS mode)

```
[Error] Unhandled Promise Rejection: ReferenceError: Can't find variable: joinPathSegments
	resolveUrlWithSegments (main.dart.js:3)
	(anonymous function) (main.dart.js:25)
	(anonymous function) (main.dart.js:1)
	Global Code (main.dart.js:29)
```
