### ISSUE TITLE
Faster builds

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/build#3800]
I've been digging into `build_runner` performance, and in particular, scalability of analyzer-based generators as the codebase grows.

It looks like there is room for significant improvement, so that's good :)

It's _complicated_, so I will need to move carefully with details discussed as I go.

First job will be to add some benchmarks #1335.

**Comment by gmpassos** [comment]
I have a suggestion: Since most of the build runner's CPU time is spent reading code unit files and parsing them, I propose a more dynamic loading approach. For example, parsing could be split into levels:  

1. **Imports**  
2. **Parts** (sub-code units)  
3. **Top-level elements** (classes, enums, functions, variables, etc.)  
4. **Class fields and methods**  

### Why do this?  

You only need to process deeper levels when required—following the principle of auto-vivification:  

- If you only need the import tree, there’s no need to parse anything beyond the top-level entries.  
- If a builder doesn’t require class fields and methods, they can be skipped.  
- If a builder doesn’t need method content, parsing it becomes unnecessary.  

Currently, the analyzer parses, analyzes, and validates *everything*! This means that even if you import a file just to use a single function, the entire file gets parsed.  

One way to achieve this is by implementing and releasing the auto-vivification process in small steps. For example, if the import and top-level entry parsing steps are implemented first, they will significantly speed up the analyzer and build process.

**Comment by davidmorgan** [comment]
Thanks @gmpassos :)

I've actually been digging into build_runner performance for a couple of weeks, and have some concrete results and fixes in mind. For the cases I'm looking at, reading and parsing is actually not the problem, nor analysis: it's build_runner's own build graph handling code that is slowing down.

I'll be adding benchmarks very soon that measure these cases, which are pretty much just "what happens when your project has lots of files".

I expect that will already help with a lot of the slowness that people are seeing.

If people are aware of _small_ codebases that have unexpectedly slow builds, that would be interesting, and I'd love to hear about it--but it might be simpler to wait until the first round of improvement lands and see if they help :)

**Comment by davidmorgan** [comment]
The benchmark I'm adding in #3802 shows the problem pretty clearly,

json_serializable |   |   |  
-- | -- | -- | --
libraries | clean/ms | no changes/ms | incremental/ms
1 | 21573 | 2840 | 4278
100 | 23040 | 2974 | 6327
250 | 28098 | 3285 | 12578
500 | 42940 | 4288 | 35061
750 | 69483 | 6561 | 67670
1000 | 115941 | 9178 | 119308

notice the incremental build time for 500 libraries and 1000 libraries: it increases from 35s to 119s, an increase of x3.4. For double the number of libraries the time increase should be x2 :)

The benchmark also runs for `built_value`, `freezed` and `mockito`, numbers on the PR, the story is pretty similar, except:

 - `built_value` and `json_serializable` are about 2x as slow as `freezed` on the big build, it turns out this is purely because they use shared parts, filed #3803 for that sub-problem
 -  `mockito` is about 2x as fast as `freezed`, I believe that is because mockito adds a part file to the test where it does not become a dep of all the other generators; conversely `built_value`, `json_serializable` and `freezed` all add part files in the app code, doubling the number of deps of all the generators

Apart from these multipliers the numbers are very similar, I think it does not matter much what the generators are actually doing.

**Comment by tenhobi** [comment]
We also tried experimenting with caching and it had good results. Something could be also added to build_runner itself. Check https://pub.dev/packages/cached_build_runner

**Comment by rrousselGit** [comment]
I would be interested in making a third-party API for builders to optimize recomputation of code-generators.

For that purpose, could we maybe have a way to opt-out to the default "listen to all imported libraries"? Followed by a `listen(library)`

**Comment by davidmorgan** [comment]
Thanks @tenhobi, thanks @rrousselGit.

I'm going to start marking comments I've replied to on this thread as "resolved" to keep it focused, since lots of people are watching it :) but I do appreciate the input.

Caching can certainly help, but it doesn't address the underlying problems, which are 1) performance, 2) granularity of invalidation.

I've created a sub-issue https://github.com/dart-lang/build/issues/3810 for granular invalidation, Remi I'll reply to your question there :)

**Comment by rrousselGit** [comment]
Thanks!

I'd also suggest looking into https://github.com/dart-lang/build/issues/3454

It's a pain that any "pub get" kills the watch mode.  
It's an even bigger pain than it should be because most Flutter commands do an implicit "put get" ; and that stops build_runner even if nothing changed

Alongside that, I'd also suggest to not stop the watch mode if there's a compilation error in a builder.

**Comment by davidmorgan** [comment]
For anyone who wants to follow PR by PR, they will be on the sub-issue for scalable performance #3811 for now :)

**Comment by amrgetment** [comment]
@davidmorgan I tried `cached_build_runner` and here are the results cc @tenhobi 

`dart run build_runner build --delete-conflicting-outputs`
The result
<img width="434" alt="Image" src="https://github.com/user-attachments/assets/42b956f6-0f2b-4dbc-9396-d5490146318b" />

`dart run cached_build_runner build`

<img width="438" alt="Image" src="https://github.com/user-attachments/assets/cb003349-6f18-4958-a277-abfcfbcc41d2" />

```
dev_dependencies:
  build_runner: ^2.4.14
  cached_build_runner:
      path: /Users/amr/Desktop/cached_build_runner/

```

**Comment by gmpassos** [comment]
Any updates on how the new changes have already affected the benchmark?  

Best regards.

**Comment by davidmorgan** [comment]
The fastest proof of concept I have so far is about 6x faster on 1000 files, 120s incremental build -> 20s incremental build.

But I'm still laying the groundwork to make that landable, as I said, it's complicated :)

The benchmark right now at commit `7995cdd178` is

json_serializable |   |   |  
-- | -- | -- | --
libraries | clean/ms | no changes/ms | incremental/ms
1 | 23021 | 3838 | 5415
100 | 23047 | 4067 | 7286
250 | 28944 | 4462 | 12391
500 | 40523 | 5944 | 29306
750 | 54127 | 7291 | 55905
1000 | 82186 | 10385 | 93929

which at 120s->94s is only 1.25x faster ;)

The code I'm merging is not actually live, needs `BuildAssetUriResolver.sharedInstance` changing to the new `AnalysisDriverModel` to use it; I'm considering whether there should be a temporary `use-experimental-resolver` flag to make it easier to try+compare. But anyway it should be more than 1.25x faster first ;)

**Comment by gmpassos** [comment]
Thanks for the hard work @davidmorgan 👍🏻

Any advice on using the current HEAD of the build packages?

I'm the author of the package [reflection_factory](https://pub.dev/packages/reflection_factory), and I which to run some benchmarks with-real world projects and share the results here.

**Comment by davidmorgan** [comment]
@gmpassos it will be annoying to try without a flag; a flag will also be useful for me, so I'll look at adding one #3831.

In terms of feedback, performance measurements are actually not particularly useful yet as I still have a lot to do there :) but it would be helpful for people to start checking to see if I actually _broke_ something, i.e. if the new version is incorrect somehow.

Here are dependency overrides that use my PR adding the flag, so if you put this in your `pubspec.yaml` and pass `--use-experimental-resolver` when you run `build_runner build` or `build_runner watch` then that's the new codepath :)

```
dependency_overrides:
  build:
    git:
      url: https://github.com/dart-lang/build
      path: build
      ref: 6e752db2bb54e2ff043364888e1489883d54eb99
  build_config:
    git:
      url: https://github.com/dart-lang/build
      path: build_config
      ref: 6e752db2bb54e2ff043364888e1489883d54eb99
  build_modules:
    git:
      url: https://github.com/dart-lang/build
      path: build_modules
      ref: 6e752db2bb54e2ff043364888e1489883d54eb99
  build_resolvers:
    git:
      url: https://github.com/dart-lang/build
      path: build_resolvers
      ref: 6e752db2bb54e2ff043364888e1489883d54eb99
  build_runner:
    git:
      url: https://github.com/dart-lang/build
      path: build_runner
      ref: 6e752db2bb54e2ff043364888e1489883d54eb99
  build_runner_core:
    git:
      url: https://github.com/dart-lang/build
      path: build_runner_core
      ref: 6e752db2bb54e2ff043364888e1489883d54eb99
  build_test:
    git:
      url: https://github.com/dart-lang/build
      path: build_test
      ref: 6e752db2bb54e2ff043364888e1489883d54eb99
  build_web_compilers:
    git:
      url: https://github.com/dart-lang/build
      path: build_web_compilers
      ref: 6e752db2bb54e2ff043364888e1489883d54eb99
```
