### ISSUE TITLE
Failed to precompile build script `.dart_tool/build/entrypoint/build.dart.`

### ISSUE THREAD

**Issue by moha-b** [dart-lang/build#3893]
I tried a lot to solve this without a clear result for why this is happening so suddenly.
``` shell
[WARNING] /Pub/Cache/hosted/pub.dev/flutter_gen_core-5.9.0/lib/flutter_generator.dart:37:38: Error: Member not found: 'latestLanguageVersion'.
      languageVersion: DartFormatter.latestLanguageVersion,
                                     ^^^^^^^^^^^^^^^^^^^^^
/Pub/Cache/hosted/pub.dev/flutter_gen_core-5.9.0/lib/flutter_generator.dart:37:7: Error: No named parameter with the name 'languageVersion'.
      languageVersion: DartFormatter.latestLanguageVersion,
      ^^^^^^^^^^^^^^^
/Pub/Cache/hosted/pub.dev/dart_style-2.3.2/lib/src/dart_formatter.dart:51:3: Context: Found this candidate, but the arguments don't match.
  DartFormatter(
  ^^^^^^^^^^^^^
[INFO] Precompiling build script... completed, took 1.6s
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```
### flutter doctor result
```shell
[√] Flutter (Channel stable, 3.29.0, on Microsoft Windows [Version 10.0.26100.3194], locale en-US)
[√] Windows Version (11 Home 64-bit, 24H2, 2009)
[√] Android toolchain - develop for Android devices (Android SDK version 35.0.0-rc3)
[√] Chrome - develop for the web
[√] Visual Studio - develop Windows apps (Visual Studio Community 2022 17.12.5)
[√] Android Studio (version 2024.2)
[√] Android Studio (version 2023.3)
[√] IntelliJ IDEA Ultimate Edition (version 2024.2)
[√] Connected device (3 available)
[√] Network resources
```
I am using ` build_runner: ^2.4.13` if I use the last version which is `2.4.15` I got another error 
```shell
Because build_runner >=2.4.15 depends on build_resolvers ^2.4.4 which depends on analyzer >=6.9.0 <8.0.0, build_runner >=2.4.15 requires analyzer >=6.9.0 <8.0.0.
And because isar_generator 3.1.0+1 depends on analyzer >=4.6.0 <6.0.0 and no versions of isar_generator match >3.1.0+1 <4.0.0, build_runner >=2.4.15 is incompatible with isar_generator ^3.1.0+1.
So, because sanad depends on both isar_generator ^3.1.0+1 and build_runner ^2.4.15, version solving failed.

You can try the following suggestion to make the pubspec resolve:
* Consider downgrading your constraint on build_runner: flutter pub add dev:build_runner:^2.4.13
Failed to update packages.
```
it goes if I override `analyzer: ^7.3.0`  but other issue appear 🙂

it was working fine until I added [Isar](https://pub.dev/packages/isar) the issue appeared I removed it and the issue still appears
```yaml
dependencies:
  flutter:
    sdk: flutter
  # UI
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  cached_network_image: ^3.4.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  equatable: ^2.0.7
  iconic: ^0.1.0
  shimmer: ^3.0.0
  syncfusion_flutter_charts: ^28.2.7
  syncfusion_flutter_datepicker: ^28.2.7
  dotted_border: ^2.1.0
  lottie: ^3.3.1
  file_picker: ^9.0.2
  cupertino_icons: ^1.0.8
  flutter_gen: ^5.9.0
  # Network
  dio: ^5.8.0+1
  connectivity_plus: ^6.1.3
  # Local Storage
  shared_preferences: ^2.5.2
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  flutter_secure_storage: ^9.2.4
  # State Management
  flutter_bloc: ^9.0.0
  # DI
  get_it: ^8.0.3
  injectable: ^2.5.0
  flutter_local_notifications: ^18.0.1
  photo_view: ^0.15.0
  in_app_update: ^4.2.3
  upgrader: ^11.3.1
  package_info_plus: ^8.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  pretty_dio_logger: ^1.4.0
  flutter_lints: ^5.0.0
  isar_generator: ^3.1.0+1
  flutter_gen_runner:
  build_runner: ^2.4.15

dependency_overrides:
  analyzer: ^7.3.0
```
