### ISSUE TITLE
build_runner fails to start up due to missing command `frontend_server.dart.snapshot`

### ISSUE THREAD

**Issue by Hu1buerger** [dart-lang/build#3945]
* The Dart SDK Version (Dart SDK version: 3.7.2 (stable) (Tue Mar 11 04:27:50 2025 -0700) on "macos_x64") and 
* What package(s) from this repo you are using, and the version (i.e. `build_runner 0.7.12`)
  * _If you are not sure, try checking your `pubspec.lock` file._
   <details>

   ```
   build_runner:
    dependency: "direct dev"
    description:
      name: build_runner
      sha256: "10c6bcdbf9d049a0b666702cf1cee4ddfdc38f02a19d35ae392863b47519848b"
      url: "https://pub.dev"
    source: hosted
    version: "2.4.6"
  build_runner_core:
    dependency: transitive
    description:
      name: build_runner_core
      sha256: c9e32d21dd6626b5c163d48b037ce906bbe428bc23ab77bcd77bb21e593b6185
      url: "https://pub.dev"
    source: hosted
    version: "7.2.11"
  ```

</details>
* What builder(s) you are using (or writing yourself). json_serializable
* Whether you are using Windows, MacOSX, or Linux (if applicable) (macos, and linux in devcontainer
* Whether you are using Chrome, Safari, Firefox, Edge (if applicable)
* Any other packages or constraints we should know about

See the attached minimal crashing example. I have tried to run `dart run build_runner run` or watch or clean, inside the devcontainer in 3.7.2 and 3.5.0, and on my host after i installed and zapped dart off of it.
Additionally i tried running build_runner with multiple versions of build_runner(2.3.3, 2.4.0, 2.4.15) and json_serialisable (6.9.4, 6.8.0). 

All of these runs resulted in the same error `Precompiling build script......Could not find a command named "/usr/local/Cellar/dart-sdk/3.7.2/libexec/bin/snapshots/frontend_server.dart.snapshot".`.

<details>

```
dart run build_runner watch
Building package executable... (5.6s)
Built build_runner:build_runner.
[INFO] Generating build script completed, took 438ms
[INFO] Precompiling build script......Could not find a command named "/usr/local/Cellar/dart-sdk/3.7.2/libexec/bin/snapshots/frontend_server.dart.snapshot".

Usage: dart <command|dart-file> [arguments]

Global options:
-v, --verbose               Show additional command output.
    --version               Print the Dart SDK version.
    --enable-analytics      Enable analytics.
    --disable-analytics     Disable analytics.
    --suppress-analytics    Disallow analytics for this `dart *` run without changing the analytics configuration.
-h, --help                  Print this usage information.

Available commands:
  analyze    Analyze Dart code in a directory.
  compile    Compile Dart to various formats.
  create     Create a new Dart project.
  devtools   Open DevTools (optionally connecting to an existing application).
  doc        Generate API documentation for Dart projects.
  fix        Apply automated fixes to Dart source code.
  format     Idiomatically format Dart source code.
  info       Show diagnostic information about the installed tooling.
  pub        Work with packages.
  run        Run a Dart program.
  test       Run tests for a project.

Run "dart help <command>" for more information about a command.
See https://dart.dev/tools/dart-tool for detailed documentation.
[INFO] Precompiling build script... completed, took 155ms
[SEVERE] Failed to precompile build script .dart_tool/build/entrypoint/build.dart.
This is likely caused by a misconfigured builder definition.
```

</details>
```

[example.zip](https://github.com/user-attachments/files/19393013/example.zip)
