### ISSUE TITLE
`build_runner` processes the files which are NOT pointed in `generate_for` key of targets/builders section

### ISSUE THREAD

**Issue by bambinoua** [dart-lang/build#3954]
I don't know if it is a bug or maybe I did something wrong. Here is the only place where I can get the competent answer. I am playing with builders and source generation and the first vision it is too complex.

Here it is my `build.yaml` where I specified that the builder must `generate_for` the single directory.

```yaml
targets:
  $default:
    builders:
      validable_generator:enum_extractor:
        enabled: true
        generate_for:
          - lib/example/domain/*.dart

builders:
  validable_generator:enum_extractor:
    import: "package:validable_generator/builder.dart"
    builder_factories: 
      - enumExtractBuilder
    build_extensions: {
      ".dart": [".enum_extract.json"]
    }
    auto_apply: dependents
    build_to: cache
```
And the question is why do I see in debug session the `.dart` files which **are not** in the specified directory? As you can see the break point was on file `package:validable/src/base.dart` which **is not** in the analyzed directory?

![Image](https://github.com/user-attachments/assets/4ee3837b-03c9-49ca-a46a-ee2e0a30ebc9)

**Comment by davidmorgan** [comment]
Hmmmm my guess is `auto_apply: dependents` means it gets applied with default config to dependents, and that's the config you're seeing.

I think in the same section you could set `defaults` and set `generate_for` there, to change that default configuration for auto applied runs.

https://pub.dev/packages/build_config

**Comment by bambinoua** [comment]
@davidmorgan unfortunately I didn't understand what you mean.

In my current `build.yaml` I configure the builder `validable:enum_extractor` in `target`'s `builders` section so it will `generate_for` only for a specific files `lib/example/domain/*.dart`. Then I configure `auto_apply` to `dependents` (Apply this Builder to the package with a direct dependency on the package exposing the builder). So what I did wrong?

> I think in the same section you could set defaults and set generate_for there, to change that default configuration for auto applied runs.

Erm... Where (and why) do I need to crete `generate_for` if I already set it?

Below is the part of `build.yaml` of `json_serializable`

```yaml
targets:
  $default:
    builders:
...
      json_serializable:
        generate_for:
        - example/*
        - test/default_value/*
        - test/field_matrix_test.field_matrix.dart
        - test/generic_files/*
        - test/integration/*
        - test/kitchen_sink/*
        - test/literal/*
        - test/supported_types/*
        - tool/readme/*
...

builders:
 json_serializable:
    import: "package:json_serializable/builder.dart"
    builder_factories: ["jsonSerializable"]
    build_extensions: {".dart": ["json_serializable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
```

And I didn't noticed they have additional sections in configure `builders` section.

P.S. That is why I said "it is too complex"...

**Comment by davidmorgan** [comment]
If you set `auto_apply` to none and nothing changed then indeed, that's not the problem.

Debug is hard to repro, can you make it just print the element name it's running on, run a single build with one command and post both the command you ran and the output? Then it's a bit clearer what's happening :)

**Comment by bambinoua** [comment]
Sorry for my stupidity. Maybe I've just describe the problem.
I am going to create 2 packages:
1. annotations which will be used in other projects to annotate classes/fields
2. generators which will generate some code on basis of annotated classes/fields.

As I understand I need to create the `build.yaml` in generator package with some general (default?) configuration:
```yaml
targets:
  $default:
    builders:
      validable_generator:enum_extractor:
        enabled: true
        generate_for:
          - 'lib/**.dart'

builders:
  validable_generator:enum_extractor:
    import: "package:validable_generator/builder.dart"
    builder_factories: 
      - enumExtractBuilder
    build_extensions: {
      ".dart": [".enum_extract.json"]
    }
    auto_apply: dependents
    build_to: cache
```

For current momemnt I want to extract all enums and save them in the cache. I would like that the generator has a possibility to analyze specific directories of target project (the one which will use annotations).

How can I force the generator to do not use value from `generate_for` but use my own list of directories of the target project? Do I need to create an additional `build.yaml` in target project with some overrides or options?
