### ISSUE TITLE
Can two builders from the same package share options?

### ISSUE THREAD

**Issue by rrousselGit** [dart-lang/build#3988]
A common pattern with code-generators is to define project-level configurations in the `build.yaml`.   
At the same time, an implementation detail of some code-generators may be to split their generation in multiple builders.

In that scenario, it is possible to have all builders use the same options without having to duplicate the configuration?

What I'd like to avoid:

```yaml
targets:
  $default:
    builders:
      my_generator|a:
        options:
          my_option: true
      my_generator|b:
        options:
          my_option: true
```

What I'd like:

```yaml
targets:
  $default:
    builders:
      my_generator: # no builder name specified, all builders use the same option
        options:
          my_option: true

```
