### ISSUE TITLE
How to test retrofit services with mockito

### ISSUE THREAD

**Issue by irangareddy** [dart-lang/build#4480]
Regarding how to write valid tests with Mockito to test the retrofit service, I have perused an ample amount of online resources and read a few blogs, but to no avail. I attempted to write tests for both the service and repository, but encountered the same error each time. I have exhausted all available options, including closed and open, in an attempt to rectify the issue. Please provide assistance in writing this test effectively. 

## Version
```yaml
environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bloc: ^8.1.2
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  freezed_annotation: ^2.4.1
  get_it: ^7.6.4
  go_router: ^12.1.1
  intl: ^0.18.0
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  mockito: ^5.4.2
  provider: ^6.0.5
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  storybook_flutter: ^0.14.0

dev_dependencies:
  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  mocktail: ^1.0.0
  retrofit_generator: ^8.0.3
  very_good_analysis: ^5.1.0
```

> Added all required code samples for understanding the code properly

#### Issue while running tests
```bash
type 'Null' is not a subtype of type 'Future<HttpResponse<OnSuccess>>'
test/auth_service_test.dart 9:7    MockAuthService.registerPhoneNumber
test/auth_service_test.dart 29:16  main.<fn>.<fn>
```

### AuthServiceTest
```dart
import 'package:dio/dio.dart';
import '../data/data_sources.dart';
import '../utils/utils.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';
import 'package:mockito/mockito.dart';
import 'package:retrofit/retrofit.dart';

class MockAuthService extends Mock implements AuthService {}

class MockAuthRepository extends Mock implements AuthRepository {}

@GenerateMocks([MockAuthService, MockAuthRepository])
void main() {
  late MockAuthService mockAuthService;
  late MockAuthRepository mockAuthRepository;

  setUp(() {
    mockAuthService = MockAuthService();
    mockAuthRepository = MockAuthRepository();
  });

  group('Auth Validation Tests', () {
    const validMobileNumber = 'xxxxxxxxxxxxx';

    test('sucessfully OTP Sent', () async {
      // Arrange
      when(
        mockAuthService.registerPhoneNumber(Mobile(mobile: validMobileNumber)),
      ).thenReturn(
        Future.value(
          HttpResponse(
            OnSuccess(
              isSuccess: true,
              message: 'Successfully OTP sent to the user.',
            ),
            Response(requestOptions: RequestOptions()),
          ),
        ),
      );

      // Act
      final result = await mockAuthRepository.phoneLogin(validMobileNumber);

      // Assert
      expect((result as DataSuccess).data, isA<OnSuccess>());
      verify(
        mockAuthService.registerPhoneNumber(Mobile(mobile: validMobileNumber)),
      );
    });
  });
}

```

### OnSuccess
```dart
import 'package:json_annotation/json_annotation.dart';

part 'on_success.g.dart';

@JsonSerializable()
class OnSuccess {
  OnSuccess({
    required this.isSuccess,
    required this.message,
  });
  factory OnSuccess.fromJson(Map<String, dynamic> json) =>
      _$OnSuccessFromJson(json);
  @JsonKey(name: 'isSuccess')
  bool isSuccess;
  @JsonKey(name: 'message')
  String message;

  Map<String, dynamic> toJson() => _$OnSuccessToJson(this);
}
```

### Mobile
```dart
import 'package:json_annotation/json_annotation.dart';

part 'mobile.g.dart';

@JsonSerializable()
class Mobile {
  Mobile({
    required this.mobile,
  });

  factory Mobile.fromJson(Map<String, dynamic> json) => _$MobileFromJson(json);

  @JsonKey(name: 'mobile')
  String mobile;

  Map<String, dynamic> toJson() => _$MobileToJson(this);
}
```
### DataState

```dart
import 'package:dio/dio.dart';

abstract class DataState<T> {
  const DataState({this.data, this.exception});

  final T? data;
  final DioException? exception;
}

class DataSuccess<T> extends DataState<T> {
  const DataSuccess(T data) : super(data: data);
}

class DataFailed<T> extends DataState<T> {
  const DataFailed(DioException exception) : super(exception: exception);
}

class DataLoading<T> extends DataState<T> {
  const DataLoading() : super();
}
```
### AuthService
```dart
import 'package:dio/dio.dart';
import 'package:feebac/data/auth/models/mobile.dart';
import 'package:feebac/data/states/on_success.dart';
import 'package:retrofit/retrofit.dart';

part 'auth_service.g.dart';

@RestApi(baseUrl: K.BASE_URL)
abstract class AuthService {
  factory AuthService(Dio dio, {String baseUrl}) = _AuthService;

  @POST('/login')
  Future<HttpResponse<OnSuccess>> registerPhoneNumber(
    @Body() Mobile mobile,
  );

  @POST('/verify-otp')
  Future<HttpResponse<OnSuccess>> verifyOTP(
    @Body() Map<String, dynamic> requestBody,
  );

}
```

### AuthRepository
```dart
import 'dart:io';
import 'package:dio/dio.dart';
import '../data/data_sources.dart';
import '../utils/utils.dart';

class AuthRepository {
  AuthRepository(this._authService);
  final AuthService _authService;

  Future<DataState<OnSuccess>> phoneLogin(String mobileNumber) async {
    try {
      final httpResponse = await _authService.registerPhoneNumber(
        Mobile(mobile: mobileNumber),
      );

      if (httpResponse.response.statusCode == HttpStatus.created) {
        return DataSuccess(httpResponse.data);
      } else {
        return DataFailed(
          DioException(
            error: httpResponse.response.statusMessage,
            response: httpResponse.response,
            requestOptions: httpResponse.response.requestOptions,
          ),
        );
      }
    } on DioException catch (e) {
      return DataFailed(e);
    }
  }
}
```
