### ISSUE TITLE
[Bug] Generated mock is not a subtype of mocked type

### ISSUE THREAD

**Issue by Pante** [dart-lang/build#4556]
Flutter version: `3.0.1`
Mockito version: `5.2.0`

I'm not sure if this is related to https://github.com/dart-lang/build/issues/4551, but the following snippet of code:
```dart
import 'package:cross_file/cross_file.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:mockito/annotations.dart';

import 'sample_test.mocks.dart';

@GenerateMocks([XFile])
void main() {
  late XFile file;

  setUp(() => file = MockXFile());
}
```

Fails to compile when running `flutter test` and emits the following error message:
```
test/sample_test.dart:11:22: Error: A value of type 'MockXFile' can't be assigned to a variable of type 'XFile'.
 - 'MockXFile' is from 'test/sample_test.mocks.dart'.
 - 'XFile' is from 'package:cross_file/src/types/io.dart' ('../../../../../.pub-cache/hosted/pub.dartlang.org/cross_file-0.3.3+1/lib/src/types/io.dart').
  setUp(() => file = MockXFile());
                     ^
```

Strangely, no errors or warnings are shown in the editor by the IDE. Neither is `flutter analyze` picking up any issues. This is true even after manually removing all the `ignore_for_file: ` comments in the generated mocks file. I've since kind of realized that it's silly to mock `XFile` but nevertheless still worth filing an issue about.

Full pubspec.yaml:
```yaml
name: bug_report
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  cross_file: ^0.3.3+1
  flutter:
    sdk: flutter

dev_dependencies:
  build_runner: ^2.1.6
  flutter_test:
    sdk: flutter
  mockito: ^5.2.0

```
