### ISSUE TITLE
Allow passing command line args to set builder options

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/build#801]
Today the only way to pass config through the `BuilderOptions` object is via a custom `build.yaml`, but it would also be useful to be able to do this in a one-off fashion based on command line args.

The driving use case for this today would be to switch your web compiler between `dart2js` and `dartdevc` on the fly (without having to edit the `build.yaml`).

My proposed syntax for this would be `--define=<builder_key>=<option>=<value>`. All values would first attempt to be parsed as JSON, and if that fails then they would be treated as a raw String. You would not be able to override the top level settings like `generate_for` and `enabled`, only the builder options.

**Pros**:
- Supports overriding all options regardless of expected type.

**Cons**:
- It is quite verbose, enabling dart2js would look like this `--define=build_web_compilers|entrypoint=compiler=dart2js`.
- Options that require map/list values would be clunky and look a bit different than the typical yaml, for example `--define "some_package|some_builder=custom_option={\"foo\": true}"`.

**Comment by jakemac53** [comment]
We would also have to decide if this should override that setting for all builders globally or just the root package, and if that would need to be configurable.

**Comment by natebosch** [comment]
> We would also have to decide if this should override that setting for all builders globally or just the root package, and if that would need to be configurable.

In bazel an argument on the command line overrides the option for all uses of that builder across all targets.

> It is quite verbose

We could consider adding shorthand for some common ones. Or we could look at adding something like 'option groups'

```yaml
targets:
  my_package:
    builders:
      build_web_compilers|entrypoint:
        option_groups:
          dev:
            compiler: ddc
          prod:
            compiler: dart2js
```

```shell
pub run build_runner build --options=dev
```

**Comment by jakemac53** [comment]
> In bazel an argument on the command line overrides the option for all uses of that builder across all targets.

Ya, I think that makes the most sense for build_runner as well.

> We could consider adding shorthand for some common ones. Or we could look at adding something like 'option groups'

Ya, I was thinking that we could punt on this specific thing and instead just add a debug/release mode which are built in as well. That covers most things, but it would end up invalidating _all builders_ instead of just the ones that actually do something with the mode.

**Comment by jakemac53** [comment]
Another option here could be allowing creators of builders to define explicit aliases for certain options.

For instance the ddc builder could look like:

```yaml
  ddc:
    target: "build_web_compilers"
    import: "package:build_web_compilers/builders.dart"
    builder_factories:
      - moduleBuilder
      - unlinkedSummaryBuilder
      - linkedSummaryBuilder
      - devCompilerBuilder
    build_extensions:
      .dart:
        - .module
        - .linked.sum
        - .unlinked.sum
        - .ddc.js.errors
        - .ddc.js
        - .ddc.js.map
    is_optional: True
    auto_apply: all_packages
    required_inputs: [".dart"]
    option_aliases:
      - web_compiler:
        option: compiler
        description: "Sets the web compiler for your dart project"
```

That would add the `web_compiler` flag, which would be an alias for `--define "build_web_compilers|ddc=compiler"`.
