### ISSUE TITLE
"web/index.html"'s ETag never invalidates

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#894]
Simple reproduction case:

Files:

```
web/
  index.html
```

Pubspec:

```yaml
name: angular_hello_world

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+4

dev_dependencies:
  build_runner: ^0.7.8
  build_web_compilers: ^0.2.1

dependency_overrides:
  analyzer: ^0.31.0-alpha.1
```

Terminal:

```bash
pub run build_runner serve
```

-----

As viewed by @natebosch as well, a hard-refresh of the browser is required to see changes.

We suspect the ETag is not being invalidated. We might want to add testing around ETag in general.

**Comment by natebosch** [comment]
Strangely I can't repro this with `e2e_example`...

**Comment by matanlurey** [comment]
Here is my lock file: https://gist.github.com/matanlurey/d57d173097cb9ade269795fa44d22a14

Here is my `pubspec.yaml`:

```yaml
name: angular_hello_world

environment:
  sdk: '>=2.0.0-dev <2.0.0'

dependencies:
  angular: ^5.0.0-alpha+4

dev_dependencies:
  build_runner: ^0.7.8
  build_web_compilers: ^0.2.1

dependency_overrides:
  analyzer: ^0.31.0-alpha.1
```

`Dart VM version: 2.0.0-dev.19.0 (Fri Jan 19 08:01:12 2018 +0100) on "macos_x64"`

I do see this:

```
[FINEST] Watch: Got modify event for "asset:angular_hello_world/web/index.html in /Users/matanl/git/build_playground/angular_hello_world/./
[INFO] Watch: Starting Build
[INFO] Build: Updating asset graph completed, took 0ms
[INFO] Build: Running build completed, took 66ms
[INFO] Build: Caching finalized dependency graph completed, took 60ms
[INFO] Build: Succeeded after 128ms with 0 outputs
```

... but I get a `304 Not Modified` in Chrome.
