### ISSUE TITLE
Allow "private" builders (in tool/**)

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/build#919]
In `code_builder`, I want to create and provide a builder (today, using `built_value`)... but I only want to use it for myself (i.e. as a dev_dependency, and then I check in the resulting `.g.dart` files as part of my package). This is to get off the legacy workflow of a manual `build.dart` file.

It works (sort of), though it does require the following configuration:

```yaml
targets:
  $default:
    builders:
      "|_built_value":

builders:
  _built_value:
    target: ":code_builder"
    import: "../../../tool/src/builder.dart"
    builder_factories:
      - "builtValueBuilder"
    build_extensions:
      ".dart": ".g.dart"
    build_to: "source"
```

I noticed that `import` is not validated (even though docs say otherwise).

It should probably check that:

* It is a `package:` reference OR
* It is a reference to a file that exists in the current package (i.e. `tool/src/builder.dart`)

I don't know if there is a good way to denote the builder as "private" (maybe anything but a `package:` scheme does this implicitly?), but we need to be able to make sure others don't try to use this builder themselves.
